part of 'workspace_workbench_view.dart';

class const _WorkbenchLayoutView({
  required final Workspace workspace,
  required final WorkspaceSourceControlScope? sourceControlScope,
  required final List<WorkspaceTabRecord> tabs,
  required final WorkbenchLayout layout,
  required final WorkbenchLayoutNode node,
  required final List<int> nodePath,
  required final TerminalRuntime terminalRuntime,
  required final WorkbenchMobileDriverPresence? mobileDriverPresence,
  required final Map<String, AgentStatusEntry> agentStatuses,
  required final CreateTerminalTabCallback onCreateTab,
  required final CreateAgentTabCallback onCreateAgentTab,
  required final OpenFileTabCallback onOpenEditorTab,
  required final OpenFileTabCallback onOpenMarkdownViewerTab,
  required final SelectWorkspaceTabCallback onSelectTab,
  required final ValueChanged<String> onCloseTab,
  required final ValueChanged<List<String>> onCloseTabs,
  required final RenameWorkspaceTabCallback onRenameTab,
  final OpenExternalTerminalCallback? onOpenExternalTerminal,
  required final OpenWorkspaceFileCallback onOpenEditor,
  required final OpenWorkspaceFileCallback onOpenMermanPreview,
  required final MoveWorkspaceTabCallback onMoveTab,
  required final SplitWorkbenchGroupCallback onSplitGroup,
  required final MergeWorkbenchGroupCallback onMergeGroup,
  required final ActivateWorkbenchGroupCallback onActivateGroup,
  required final UpdateWorkbenchSplitRatioCallback onUpdateSplitRatio,
}) extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final groupId = node.groupId;
    if (groupId != null) {
      return _WorkbenchPane(
        workspace: workspace,
        sourceControlScope: sourceControlScope,
        tabs: tabs,
        layout: layout,
        groupId: groupId,
        terminalRuntime: terminalRuntime,
        mobileDriverPresence: mobileDriverPresence,
        agentStatuses: agentStatuses,
        onCreateTab: onCreateTab,
        onCreateAgentTab: onCreateAgentTab,
        onOpenEditorTab: onOpenEditorTab,
        onOpenMarkdownViewerTab: onOpenMarkdownViewerTab,
        onSelectTab: onSelectTab,
        onCloseTab: onCloseTab,
        onCloseTabs: onCloseTabs,
        onRenameTab: onRenameTab,
        onOpenExternalTerminal: onOpenExternalTerminal,
        onOpenEditor: onOpenEditor,
        onOpenMermanPreview: onOpenMermanPreview,
        onMoveTab: onMoveTab,
        onSplitGroup: onSplitGroup,
        onMergeGroup: onMergeGroup,
        onActivateGroup: onActivateGroup,
      );
    }
    return _WorkbenchSplitView(
      workspace: workspace,
      sourceControlScope: sourceControlScope,
      tabs: tabs,
      layout: layout,
      node: node,
      nodePath: nodePath,
      terminalRuntime: terminalRuntime,
      mobileDriverPresence: mobileDriverPresence,
      agentStatuses: agentStatuses,
      onCreateTab: onCreateTab,
      onCreateAgentTab: onCreateAgentTab,
      onOpenEditorTab: onOpenEditorTab,
      onOpenMarkdownViewerTab: onOpenMarkdownViewerTab,
      onSelectTab: onSelectTab,
      onCloseTab: onCloseTab,
      onCloseTabs: onCloseTabs,
      onRenameTab: onRenameTab,
      onOpenExternalTerminal: onOpenExternalTerminal,
      onOpenEditor: onOpenEditor,
      onOpenMermanPreview: onOpenMermanPreview,
      onMoveTab: onMoveTab,
      onSplitGroup: onSplitGroup,
      onMergeGroup: onMergeGroup,
      onActivateGroup: onActivateGroup,
      onUpdateSplitRatio: onUpdateSplitRatio,
    );
  }
}

class const _WorkbenchSplitView({
  required final Workspace workspace,
  required final WorkspaceSourceControlScope? sourceControlScope,
  required final List<WorkspaceTabRecord> tabs,
  required final WorkbenchLayout layout,
  required final WorkbenchLayoutNode node,
  required final List<int> nodePath,
  required final TerminalRuntime terminalRuntime,
  required final WorkbenchMobileDriverPresence? mobileDriverPresence,
  required final Map<String, AgentStatusEntry> agentStatuses,
  required final CreateTerminalTabCallback onCreateTab,
  required final CreateAgentTabCallback onCreateAgentTab,
  required final OpenFileTabCallback onOpenEditorTab,
  required final OpenFileTabCallback onOpenMarkdownViewerTab,
  required final SelectWorkspaceTabCallback onSelectTab,
  required final ValueChanged<String> onCloseTab,
  required final ValueChanged<List<String>> onCloseTabs,
  required final RenameWorkspaceTabCallback onRenameTab,
  final OpenExternalTerminalCallback? onOpenExternalTerminal,
  required final OpenWorkspaceFileCallback onOpenEditor,
  required final OpenWorkspaceFileCallback onOpenMermanPreview,
  required final MoveWorkspaceTabCallback onMoveTab,
  required final SplitWorkbenchGroupCallback onSplitGroup,
  required final MergeWorkbenchGroupCallback onMergeGroup,
  required final ActivateWorkbenchGroupCallback onActivateGroup,
  required final UpdateWorkbenchSplitRatioCallback onUpdateSplitRatio,
}) extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final axis = node.axis!;
    final first = _WorkbenchLayoutView(
      workspace: workspace,
      sourceControlScope: sourceControlScope,
      tabs: tabs,
      layout: layout,
      node: node.first!,
      nodePath: <int>[...nodePath, 0],
      terminalRuntime: terminalRuntime,
      mobileDriverPresence: mobileDriverPresence,
      agentStatuses: agentStatuses,
      onCreateTab: onCreateTab,
      onCreateAgentTab: onCreateAgentTab,
      onOpenEditorTab: onOpenEditorTab,
      onOpenMarkdownViewerTab: onOpenMarkdownViewerTab,
      onSelectTab: onSelectTab,
      onCloseTab: onCloseTab,
      onCloseTabs: onCloseTabs,
      onRenameTab: onRenameTab,
      onOpenExternalTerminal: onOpenExternalTerminal,
      onOpenEditor: onOpenEditor,
      onOpenMermanPreview: onOpenMermanPreview,
      onMoveTab: onMoveTab,
      onSplitGroup: onSplitGroup,
      onMergeGroup: onMergeGroup,
      onActivateGroup: onActivateGroup,
      onUpdateSplitRatio: onUpdateSplitRatio,
    );
    final second = _WorkbenchLayoutView(
      workspace: workspace,
      sourceControlScope: sourceControlScope,
      tabs: tabs,
      layout: layout,
      node: node.second!,
      nodePath: <int>[...nodePath, 1],
      terminalRuntime: terminalRuntime,
      mobileDriverPresence: mobileDriverPresence,
      agentStatuses: agentStatuses,
      onCreateTab: onCreateTab,
      onCreateAgentTab: onCreateAgentTab,
      onOpenEditorTab: onOpenEditorTab,
      onOpenMarkdownViewerTab: onOpenMarkdownViewerTab,
      onSelectTab: onSelectTab,
      onCloseTab: onCloseTab,
      onCloseTabs: onCloseTabs,
      onRenameTab: onRenameTab,
      onOpenExternalTerminal: onOpenExternalTerminal,
      onOpenEditor: onOpenEditor,
      onOpenMermanPreview: onOpenMermanPreview,
      onMoveTab: onMoveTab,
      onSplitGroup: onSplitGroup,
      onMergeGroup: onMergeGroup,
      onActivateGroup: onActivateGroup,
      onUpdateSplitRatio: onUpdateSplitRatio,
    );
    return _TransientSplitLayout(
      axis: axis,
      persistedRatio: node.ratio!,
      first: first,
      second: second,
      onPersistRatio: (ratio) {
        onUpdateSplitRatio(nodePath: nodePath, ratio: ratio);
      },
    );
  }
}
