part of 'alera_localizations.dart';

const Map<String, String> _traditionalChineseShell = <String, String>{
  // Workspace and editor shell.
  'Add Project': '新增專案',
  'New Workspace': '新增工作區',
  'Open Settings': '開啟設定',
  'Quick Start': '快速開始',
  'Keyboard Shortcuts': '鍵盤快速鍵',
  'Explorer': '檔案總管',
  'Source Control': '原始碼控制',
  'Pull Request': 'Pull Request',
  'Pull Requests': 'Pull Requests',
  'Automations': '自動化',
  'New Terminal': '新增終端機',
  'New Tab': '新增分頁',
  'Open in Zed': '在 Zed 中開啟',
  'Open in Alera': '在 Alera 中開啟',
  'Copy path': '複製路徑',
  'Copy relative path': '複製相對路徑',
  'New file': '新增檔案',
  'New folder': '新增資料夾',
  'Collapse All': '全部收合',
  'Save all files': '儲存所有檔案',

  'No projects yet': '尚無專案',
  'Add a git repository to create workspaces with terminal tabs.':
      '新增 Git 儲存庫以建立含終端機分頁的工作區。',
  'Add Your First Project': '新增第一個專案',
  'Unpin Workspace': '取消釘選工作區',
  'Pin Workspace': '釘選工作區',
  'Pin Workspace Tree': '釘選工作區樹',
  'Unpin Workspace Tree': '取消釘選工作區樹',
  'Manage Tags': '管理標籤',
  'Set Parent Workspace': '設定父工作區',
  'Clear Parent Workspace': '清除父工作區',
  'Set Section': '設定區段',
  'Clear Section': '清除區段',
  'Open in Browser': '在瀏覽器中開啟',
  'Open in Project Settings': '在專案設定中開啟',
  'Copy Path': '複製路徑',
  'Sleep': '休眠',
  'Folder name': '資料夾名稱',
  'File name': '檔案名稱',
  'Name': '名稱',
  'Path copied': '已複製路徑',
  'Relative path copied': '已複製相對路徑',
  'Duplicate': '建立副本',
  'Show ignored files': '顯示忽略的檔案',
  'Hide ignored files': '隱藏忽略的檔案',
  'Show hidden items': '顯示隱藏項目',
  'Hide hidden items': '不顯示隱藏項目',
  'Source control root': '原始碼控制根目錄',
  'Clear Source Control Root': '清除原始碼控制根目錄',
  'Use As Source Control Root': '設為原始碼控制根目錄',
  'Collapse folder': '收合資料夾',
  'Move this item to the trash?': '要將此項目移到資源回收筒嗎？',
  'Open File': '開啟檔案',
  'Reveal in Explorer': '在檔案總管中顯示',
  'Stage': '暫存',
  'Unstage': '取消暫存',
  'Discard': '捨棄',
  'All Changes': '所有變更',
  'Show Flat List': '顯示平面清單',
  'Show Tree': '顯示樹狀檢視',
  'Show All Changes': '顯示所有變更',
  'Group By Staged State': '依暫存狀態分組',
  'Hide File Filter': '隱藏檔案篩選',
  'Search Files': '搜尋檔案',
  'Expand All': '全部展開',
  'Filter files...': '篩選檔案…',
  'Stop generating commit message': '停止產生 Commit 訊息',
  'Generate commit message with AI': '使用 AI 產生 Commit 訊息',
  'Source Control Actions': '原始碼控制操作',
  'Commit': 'Commit',
  'Commit & Push': 'Commit 並 Push',
  'Commit & Sync': 'Commit 並同步',
  'Commit Amend': '修改上一筆 Commit',
  'Stage All': '全部暫存',
  'Unstage All': '全部取消暫存',
  'Discard All': '全部捨棄',
  'Open Changes in Zed': '在 Zed 中開啟變更',
  'Fetch': 'Fetch',
  'Pull': 'Pull',
  'Push': 'Push',
  'Sync': '同步',
  'Publish Branch': '發佈分支',
  'Stash': 'Stash',
  'Stash Pop': '套用 Stash',
  'Quick Open': '快速開啟',
  'Search workspace files': '搜尋工作區檔案',
  'Use Up and Down to navigate, Enter to open, or Escape to close.':
      '使用上、下方向鍵移動，Enter 開啟，Escape 關閉。',
  'Loading workspace files...': '正在載入工作區檔案…',
  'Could not load workspace files.': '無法載入工作區檔案。',
  'No files are available in this workspace.': '此工作區沒有可用的檔案。',
  'No files match': '沒有符合的檔案：',
  'Command Palette': '指令面板',
  'Search commands': '搜尋指令',
  'Use Up and Down to navigate, Enter to run, or Escape to close.':
      '使用上、下方向鍵移動，Enter 執行，Escape 關閉。',
  'No commands are available.': '目前沒有可用的指令。',
  'No commands match': '沒有符合的指令：',
  'No shortcut': '無快速鍵',
  'How shortcuts behave while a terminal is focused.': '設定終端機取得焦點時快速鍵的行為。',
  'When a Terminal Is Focused': '終端機取得焦點時',
  'App first lets Alera capture combinations the shell would otherwise receive. Terminal first defers to the shell.':
      '「應用程式優先」會讓 Alera 攔截原本會傳給 Shell 的組合鍵；「終端機優先」則優先交由 Shell 處理。',
  'Stop Recording': '停止錄製',
  'Change Shortcut': '變更快速鍵',
  'Press keys… (Esc to cancel)': '請按下快速鍵…（Esc 取消）',
  'Disabled': '已停用',
  'Unassigned': '未指派',
  'Shortcut already in use': '快速鍵已被使用',
  'Reassign': '重新指派',
  'Enter a shortcut like Ctrl+Shift+P.': '請輸入快速鍵，例如 Ctrl+Shift+P。',
  'A shortcut can only have one main key.': '快速鍵只能有一個主要按鍵。',
  'Add a main key, like P or Enter.': '請加入主要按鍵，例如 P 或 Enter。',
  'Use either Mod or a platform-specific modifier, not both.':
      '請使用 Mod 或平台專用修飾鍵其中一種，不要同時使用。',
  'Include at least one modifier key.': '請至少包含一個修飾鍵。',
  'Press a non-modifier key too.': '請再按下一個非修飾鍵。',
  'Unsupported key.': '不支援此按鍵。',
  'Go to Tab 1': '前往分頁 1',
  'Go to Tab 2': '前往分頁 2',
  'Go to Tab 3': '前往分頁 3',
  'Go to Tab 4': '前往分頁 4',
  'Go to Tab 5': '前往分頁 5',
  'Go to Tab 6': '前往分頁 6',
  'Go to Tab 7': '前往分頁 7',
  'Go to Tab 8': '前往分頁 8',
  'Go to Last Tab': '前往最後一個分頁',
  'Open the settings dialog.': '開啟設定對話框。',
  'Open the runtime-local automation manager.': '開啟此執行環境的自動化管理器。',
  'Search and open a file in the active workspace.': '搜尋並開啟目前工作區中的檔案。',
  'Search and run an Alera command.': '搜尋並執行 Alera 指令。',
  'Open the add-project dialog.': '開啟新增專案對話框。',
  'Collapse or expand the project sidebar.': '收合或展開專案側邊欄。',
  'Create a linked workspace for the active Git project.':
      '為目前的 Git 專案建立連結工作區。',
  'Open the active workspace in the configured external editor.':
      '在已設定的外部編輯器中開啟目前工作區。',
  'Go to the previously selected workspace.': '前往先前選取的工作區。',
  'Go to the next workspace in navigation history.': '前往導覽紀錄中的下一個工作區。',
  'Open workspace search.': '開啟工作區搜尋。',
  'Search the active terminal scrollback.': '搜尋目前終端機的捲動緩衝內容。',
  'Show or hide the prompt composer for the active terminal.':
      '顯示或隱藏目前終端機的提示詞輸入區。',
  'Open workspace search and replace.': '開啟工作區搜尋與取代。',
  'Save the active editor file.': '儲存目前編輯器檔案。',
  'Open a terminal tab in the active workspace.': '在目前工作區開啟終端機分頁。',
  'Close the active terminal tab.': '關閉目前的終端機分頁。',
  'Select the next tab in the active pane.': '選取目前窗格中的下一個分頁。',
  'Select the previous tab in the active pane.': '選取目前窗格中的上一個分頁。',
  'Select the first tab in the active pane.': '選取目前窗格中的第一個分頁。',
  'Select the second tab in the active pane.': '選取目前窗格中的第二個分頁。',
  'Select the third tab in the active pane.': '選取目前窗格中的第三個分頁。',
  'Select the fourth tab in the active pane.': '選取目前窗格中的第四個分頁。',
  'Select the fifth tab in the active pane.': '選取目前窗格中的第五個分頁。',
  'Select the sixth tab in the active pane.': '選取目前窗格中的第六個分頁。',
  'Select the seventh tab in the active pane.': '選取目前窗格中的第七個分頁。',
  'Select the eighth tab in the active pane.': '選取目前窗格中的第八個分頁。',
  'Select the last tab in the active pane.': '選取目前窗格中的最後一個分頁。',
  'Split the active pane to the right with a new terminal.':
      '在目前窗格右側分割並開啟新的終端機。',
  'Split the active pane downward with a new terminal.': '在目前窗格下方分割並開啟新的終端機。',
  'Merge the active pane back into its sibling.': '將目前窗格合併回相鄰窗格。',
  'Global': '全域',
  'Workspace': '工作區',
  'Tabs': '分頁',
  'Panes': '窗格',
  'Open Automations': '開啟自動化',
  'Open Workspace in External Editor': '在外部編輯器中開啟工作區',
  'Toggle Sidebar': '切換側邊欄',
  'Go Back': '返回',
  'Go Forward': '前進',
  'Find in Files': '在檔案中尋找',
  'Find in Terminal': '在終端機中尋找',
  'Toggle Terminal Composer': '切換終端機輸入區',
  'Replace in Files': '在檔案中取代',
  'Save File': '儲存檔案',
  'New Terminal Tab': '新增終端機分頁',
  'Close Tab': '關閉分頁',
  'Next Tab': '下一個分頁',
  'Previous Tab': '上一個分頁',
  'Split Right': '向右分割',
  'Split Down': '向下分割',
  'Close Split': '關閉分割窗格',
  'Select Folder': '選擇資料夾',
  'Select Parent Folder': '選擇父資料夾',
  'Choose Parent Folder': '選擇父資料夾',
  'Choose an existing local folder or clone a Git repository from a URL.':
      '選擇現有本機資料夾，或從 URL 複製 Git 儲存庫。',
  'Local Folder': '本機資料夾',
  'Clone From URL': '從 URL 複製',
  'Project Path': '專案路徑',
  'Destination Folder': '目的地資料夾',
  'Auth Method': '認證方式',
  'Authentication': '驗證方式',
  'Key': '金鑰',
  'Password': '密碼',
  'Platform': '平台',
  'Architecture': '架構',
  'Parent Workspace': '父工作區',
  'No Parent': '無父工作區',
  'Section Name': '區段名稱',
  'Terminal Title': '終端機標題',
  'Configuration is stored in your Alera account and can be read by the service. Review custom commands and prompts for embedded secrets. Credentials and device permissions stay local.':
      '設定會儲存在你的 Alera 帳戶中，服務可讀取這些設定。請檢查自訂命令與提示詞是否包含機密資訊；憑證與裝置權限仍只保留在本機。',
  'Review Changes': '檢視變更',
  'History': '歷史記錄',
  'Retry Pending Upload': '重試待上傳項目',
  'Shared version': '共用版本',
  'Comparing': '比較版本',
  'differences': '項差異',
  'unresolved': '項未解決',
  'Keep All Local': '全部保留本機版本',
  'Keep All Remote': '全部保留遠端版本',
  'Both sides changed this value. Choose what to keep.':
      '本機與遠端都修改了此值，請選擇要保留哪一個。',
  'Local': '本機',
  'Remote': '遠端',
  'Choose A Value': '選擇一個值',
  'Keep Local': '保留本機版本',
  'Keep Remote': '保留遠端版本',
  'Action Name': '動作名稱',
  'Profile Name': '設定檔名稱',
  'Result': '結果',
  'Unresolved': '未解決',
  '(Removed)': '（已移除）',
  'These changes apply only to': '這些變更只會套用到',
  'Apply To Device': '套用到裝置',
  'Apply And Upload': '套用並上傳',
  'Leaving this screen without applying keeps your configuration unchanged. If upload fails after applying, local changes remain pending.':
      '離開此畫面而不套用時，設定會保持不變。若套用後上傳失敗，本機變更會保留為待上傳狀態。',
  'Version': '版本',
  'Compare': '比較',
  'Shell environment reloaded': 'Shell 環境已重新載入',
  'PATH entries': '個 PATH 項目',
  'Could not reload shell environment': '無法重新載入 Shell 環境',
  'Could not open link': '無法開啟連結',
  'No external editor is installed.': '未安裝支援的外部編輯器。',
  'Could not open file in the external editor.': '無法在外部編輯器中開啟檔案。',
  'Existing Branch *': '現有分支 *',
  'New Branch Name *': '新分支名稱 *',
  'Workspace Name (Optional)': '工作區名稱（選填）',
  'Search projects': '搜尋專案',
  'Search Workspaces': '搜尋工作區',
  'Search workspaces': '搜尋工作區',
  'Replace': '取代',
  'Files to include': '要包含的檔案',
  'Files to exclude': '要排除的檔案',
  'Hide details': '隱藏詳細資料',
  'Show details': '顯示詳細資料',
  'Hide replace': '隱藏取代欄位',
  'Show replace': '顯示取代欄位',
  'Search Terminal': '搜尋終端機',
  'Search PDF': '搜尋 PDF',
  'Add tag…': '新增標籤…',
  'Add project…': '新增專案…',
  'Terminal Input': '終端機輸入',
  'Display Name (Optional)': '顯示名稱（選填）',
  'Alera will detect whether the folder is a Git repository. Non-Git folders only get a primary workspace.':
      'Alera 會偵測資料夾是否為 Git 儲存庫；非 Git 資料夾只會建立主要工作區。',
  'Alera will run git clone into the destination folder and register the cloned repository.':
      'Alera 會在目的地資料夾執行 git clone，並登錄複製完成的儲存庫。',
  'Native folder picker is not available; paste path manually.':
      '無法使用系統資料夾選擇器，請手動貼上路徑。',

  'Edit': '編輯',
  'Back': '返回',
  'Next': '下一步',
  'Done': '完成',
  'Add': '新增',
  'Start': '啟動',
  'Stop': '停止',
  'Select': '選擇',
  'Confirm': '確認',
  'Update': '更新',
  'Download': '下載',
  'Approve': '核准',
  'Reject': '拒絕',
  'Open Usage': '開啟用量',
  'Remove Token': '移除 Token',
  'Check For Updates': '檢查更新',
  'Resume': '繼續執行',
  'Extend': '延長',
  'Run': '執行',
  'Continue Active': '繼續目前執行',
  'Cancel Active': '取消目前執行',
  'Save Automation': '儲存自動化',
  'Run Now': '立即執行',
  'Restore': '還原',
  'Trash': '移至垃圾桶',
  'New Automation': '新增自動化',
  'Post Comment': '發佈留言',
  'Link': '連結',
  'Create Stack': '建立 Stack',
  'Link Existing Pull Request': '連結現有 Pull Request',
  'Create Pull Request': '建立 Pull Request',
  'Test Command': '測試指令',
  'Add CCS Profile': '新增 CCS 設定檔',
  'Save Profile': '儲存設定檔',
  'Check Environment': '檢查環境',
  'Take Back This Terminal': '取回此終端機',
  'Take Back All Terminals': '取回所有終端機',
  'Take Back': '取回',
  'Add Git Project': '新增 Git 專案',
  'Use Custom Command': '使用自訂指令',
  'Continue Manually': '手動繼續',
  'Open Workspace': '開啟工作區',
  'Retry Agent': '重試 Agent',
  'Create And Start Agent': '建立並啟動 Agent',
  'Cancel Download': '取消下載',
  'Remove Model': '移除模型',
  'Update Runtime': '更新 Runtime',
  'Kill All': '全部終止',
  'A reading diff is an AI-guided, non-applicable abbreviation of the original diff.':
      '閱讀 Diff 是由 AI 引導產生、不可直接套用的原始 Diff 精簡版本。',
  'This overview explains the behavioral changes selected while condensing the diff. It does not identify bugs or security findings. Open Condensed Diff to inspect the retained source changes, or return to the original diff for the complete patch.': '此總覽說明精簡 Diff 時保留的行為變更，不代表錯誤或資安檢查結果。請開啟「精簡 Diff」檢視保留的原始碼變更，或返回原始 Diff 查看完整 Patch。',
  'Cached Result': '快取結果',
  'Preparing reading diff': '正在準備閱讀 Diff',
  'Loading cached reading diff': '正在載入快取的閱讀 Diff',
  'Loading the immutable diff and splitting it at safe boundaries.':
      '正在載入不可變更的 Diff，並於安全邊界分割。',
  'Using a previously generated and validated result.': '使用先前已產生並驗證的結果。',
  'The agent is proposing safe elisions; Rust validates the plan.':
      'Agent 正在提出安全的省略方案；Rust 會驗證該方案。',
  'Rust rejected the plan; the agent is replacing it once.':
      'Rust 已拒絕此方案；Agent 正在重新產生一次替代方案。',
  'Rust is merging the validated chunks into the final reading diff.':
      'Rust 正在將已驗證的區塊合併為最終閱讀 Diff。',
  'Reading diff generation failed': '閱讀 Diff 產生失敗',
  'This manually runs the configured AI Assist agent and may consume subscription quota or other provider usage. The complete selected patch is provided, including portions hidden by preview truncation.': '這會手動執行已設定的 AI Assist Agent，可能消耗訂閱額度或其他 Provider 用量。系統會提供完整的所選 Patch，包括預覽截斷而隱藏的部分。',
  'The result opens with a behavioral overview and a condensed, non-applicable diff. It is not a bug or security review.':
      '結果會先顯示行為總覽及不可直接套用的精簡 Diff；這不是錯誤或資安審查。',
  'Agent': 'Agent',
  'Model': '模型',
  'Effort': '推理強度',
  'Access': '存取權限',
  'Diff Size': 'Diff 大小',
  'Chunks': '區塊數',
  'Agent Default': 'Agent 預設值',
  'Repository Read Only': 'Repository 唯讀',
  'Diff Only': '僅限 Diff',
  'Could not prepare': '無法準備',
  'condensed diff': '精簡 Diff',

  'Generate Reading Diff': '產生閱讀 Diff',
  'Install Update': '安裝更新',
  'Restart Alera': '重新啟動 Alera',
  'Run Update': '執行更新',
  'View Output': '檢視輸出',
  'New Action': '新增動作',
  'Cancel Offer': '取消配對邀請',
  'Add Copy Rule': '新增複製規則',
  'Add Setup Command': '新增設定指令',
  'Use Repo File': '使用儲存庫檔案',
  'Plan': '規劃',
  'Bootstrap': '初始化',
  'Copy Output': '複製輸出',
  'Restart Terminal': '重新啟動終端機',
  'Reconnect': '重新連線',
  'Amend': '修改 Commit',

  'Run Precheck': '執行前置檢查',
  'Audited Draft Test': '稽核草稿測試',
  'Approve Exact Revision': '核准指定版本',
  'Skip': '略過',
  'Queue': '排入佇列',
  'Run Latest Once': '執行最新版本一次',
  'Force Parallel': '強制平行執行',
  'Pause Automation': '暫停自動化',
  'Choose what to do with active runs.': '選擇如何處理目前執行中的工作。',
  'Loading automation policy...': '正在載入自動化政策…',
  'Automation Policy Unavailable': '無法取得自動化政策',
  'Automation Permissions': '自動化權限',
  'Choose whether this profile may administer active definitions and whether it may execute them.':
      '選擇此設定檔是否可管理作用中的自動化定義，以及是否可執行它們。',
  'May Activate Or Edit Active Automations': '可啟用或編輯作用中的自動化',
  'Allow a managed agent using this profile to activate or edit an active definition.':
      '允許使用此設定檔的受管理 Agent 啟用或編輯作用中的自動化定義。',
  'May Execute Automations': '可執行自動化',
  'Opt this profile into scheduled and manual automation execution.':
      '允許此設定檔執行排程與手動自動化。',
  'Project Automation Policy Unavailable': '無法取得專案自動化政策',
  'Automation Policy': '自動化政策',
  'Repository declaration is read from alera.toml. Local approval can only restrict execution.':
      'Repository 宣告會從 alera.toml 讀取；本機核准只能進一步限制執行。',
  'Repository Declares Automations': 'Repository 宣告自動化',
  'The repository declares automation use in alera.toml.':
      'Repository 已在 alera.toml 宣告使用自動化。',
  'Add an automation declaration to alera.toml before execution.':
      '執行前請先在 alera.toml 新增自動化宣告。',
  'Require Local Approval': '需要本機核准',
  'Require an explicit human approval in addition to the repository declaration.':
      '除了 Repository 宣告外，還需要明確的人工作業核准。',
  'Local Approval Granted': '已授予本機核准',
  'Grant the local approval required by a restrictive project policy.':
      '授予限制性專案政策所要求的本機核准。',
  'Loading Automation Settings': '正在載入自動化設定',
  'Reading runtime automation settings.': '正在讀取執行環境的自動化設定。',
  'Automation Settings Unavailable': '無法取得自動化設定',
  'Automation History And Autostart': '自動化歷程與自動啟動',
  'Keep scheduled work available without a window and control local retention.':
      '讓排程工作在沒有視窗時仍可執行，並控制本機保留期限。',
  'Start Automations At Login': '登入時啟動自動化',
  'Start the persistent local automation host when you sign in. This is off by default.':
      '登入時啟動常駐的本機自動化 Host；預設為關閉。',
  'Run History Retention': '執行歷程保留期限',
  'Keep final runs for at most this many days.': '最多保留已完成執行紀錄這麼多天。',
  'Audit Retention': '稽核保留期限',
  'Keep automation audit events for at most this many days.':
      '最多保留自動化稽核事件這麼多天。',
  'Trash Retention': '垃圾桶保留期限',
  'Permanently remove trashed definitions after this many days.':
      '垃圾桶中的定義超過此天數後永久刪除。',
  'days': '天',

  'Notify On Success': '成功時通知',
  'Prompt Preview': '提示詞預覽',
  'Automation unavailable': '無法取得自動化',
  'Pause': '暫停',
  'Runs': '執行紀錄',
  'Audit': '稽核',
  'Slug': 'Slug',
  'Schedule': '排程',
  'Cron / time': 'Cron / 時間',
  'Target': '目標',
  'Policies': '政策',
  'Limits': '限制',
  'Tags': '標籤',
  'Revision': '版本',
  'Prompt': '提示詞',
  'Effective Policy': '生效政策',
  'Signature Timeline': '簽章時間軸',
  'Overlap': '重疊處理',

  'No active run or upcoming occurrence.': '目前沒有執行中或即將開始的工作。',
  'Scheduled occurrence': '排程執行',
  'No runs yet.': '尚無執行紀錄。',
  'No audit events yet.': '尚無稽核事件。',
  'Import Automations': '匯入自動化',
  'Edit Automation': '編輯自動化',
  'Project (Optional)': '專案（選填）',
  'Tag Ids (Comma-separated)': '標籤 ID（以逗號分隔）',
  'Prompt Template': '提示詞範本',
  'Five-field Cron': '五欄 Cron',
  'Run At (UTC)': '執行時間（UTC）',
  'IANA Timezone': 'IANA 時區',
  'Start At (Optional ISO-8601 UTC)': '開始時間（選填，ISO-8601 UTC）',
  'End At (Optional ISO-8601 UTC)': '結束時間（選填，ISO-8601 UTC）',
  'Maximum Scheduled Runs (Optional)': '最大排程執行次數（選填）',
  'Source Workspace': '來源工作區',
  'Tab': '分頁',
  'Agent Conversation ID': 'Agent 對話 ID',
  'Agent Profile': 'Agent 設定檔',
  'Source Branch': '來源 Branch',
  'Workspace Name Template': '工作區名稱範本',
  'Precheck Command (Optional)': '前置檢查指令（選填）',
  'Precheck Timeout (Seconds)': '前置檢查逾時（秒）',
  'Setup': '設定',
  'Misfire': '錯過排程',
  'Cleanup': '清理',
  'Queue Cap (Maximum 10)': '佇列上限（最多 10）',
  'Inactivity Timeout (Seconds)': '閒置逾時（秒）',
  'Heartbeat Interval (Seconds)': 'Heartbeat 間隔（秒）',
  'Retry Attempts (Maximum 3)': '重試次數（最多 3）',
  'Retry Backoff (Seconds)': '重試退避（秒）',
  'Circuit Failure Threshold': 'Circuit 失敗門檻',
  'Circuit Open (Seconds)': 'Circuit 開啟時間（秒）',
  'Select...': '請選擇…',
  'One-time': '單次',
  'Existing Tab': '現有分頁',
  'Fresh Tab': '新分頁',
  'Managed Workspace': '受管理工作區',
  'Name, slug, and prompt template are required.': '名稱、slug 與提示詞範本為必填。',
  'The existing tab requires workspace, tab, and conversation ids.':
      '現有分頁需要 workspace、tab 與 conversation ID。',
  'The selected target requires its ids.': '所選目標需要填寫對應 ID。',
  'Prompt template contains an unmatched closing delimiter.':
      '提示詞範本包含未配對的結束分隔符。',
  'Prompt template contains an unterminated variable.': '提示詞範本包含未結束的變數。',
  'Versioned JSON Catalog': '版本化 JSON Catalog',
  'Source Key To Local Id JSON': '來源 Key 到本機 ID 的 JSON',
  'Map every source key to an existing local id.': '將每個來源 Key 對應到既有的本機 ID。',
  'Automation created': '已建立自動化',
  'Automation saved': '已儲存自動化',
  'Automation cloned': '已複製自動化',
  'Automation catalog copied to clipboard': '自動化 Catalog 已複製到剪貼簿',
  'Automation catalog imported as drafts': '自動化 Catalog 已以草稿匯入',
  'Automation approved': '已核准自動化',
  'Automation run started': '自動化執行已開始',
  'Automation paused': '自動化已暫停',
  'Automation resumed': '自動化已繼續',
  'Automation cancellation requested': '已要求取消自動化',
  'Waiting run resumed': '等待中的執行已繼續',
  'Waiting run extended': '已延長等待中的執行',
};
