part of 'alera_localizations.dart';

const Map<String, String> _japaneseAgents = <String, String>{
  'Map Imported Targets': 'インポートしたターゲットを対応付け',
  'App First': 'アプリ優先',
  'Terminal First': 'ターミナル優先',
  'From Prompt': 'プロンプトから',
  'Manual': '手動',
  'Daily Activity': '日次アクティビティ',
  'Usage': '使用量',
  'Local Host': 'ローカル Host',
  'Updating': '更新中',
  'Showing saved usage while new data loads in the background.':
      '新しいデータをバックグラウンドで読み込みながら、保存済みの使用量を表示しています。',
  'Update Failed': '更新に失敗しました',
  '7 Days': '7 日間',
  '30 Days': '30 日間',
  '90 Days': '90 日間',
  'Usage Unavailable': '使用量を取得できません',
  'No usage data is available for this host.': 'この Host で利用できる使用量データはありません。',
  'Processed Tokens': '処理済みトークン',
  'API-Equivalent Cost': 'API 換算コスト',
  'Sessions': 'セッション',
  'Cached Input': 'キャッシュされた入力',
  'Cache Savings': 'キャッシュによる削減',
  'Compared with full input rates': '通常の入力料金との比較',
  'Tokens read from Claude Code, Codex, and Grok Build transcripts on this host.':
      'この Host 上の Claude Code、Codex、Grok Build のトランスクリプトから読み取ったトークン数です。',
  'Breakdown': '内訳',
  'No Activity': 'アクティビティがありません',
  'No Daily Activity': '日次アクティビティがありません',
  'Provider-reported costs': 'プロバイダーが報告したコスト',
  'Current model rates': '現在のモデル料金',
  'Cached model rates': 'キャッシュされたモデル料金',
  'Pricing unavailable': '料金情報を取得できません',
  'Some model costs may be unavailable because pricing could not be loaded.':
      '料金情報を読み込めなかったため、一部のモデルのコストが表示されない場合があります。',

  'Profiles': 'プロファイル',
  'Grouped': 'グループ化',
  'Models': 'モデル',
  'Tokens': 'トークン',
  'Cost': 'コスト',
  'Responses': '応答数',
  'Terminal unavailable': 'ターミナルを利用できません',
  'Restart Terminal?': 'ターミナルを再起動しますか？',
  'This Device': 'このデバイス',
  'IP Address': 'IP アドレス',
  'DNS Hostname': 'DNS ホスト名',
  'Private Interface': 'プライベートネットワークインターフェイス',
  'All changes for file': 'このファイルのすべての変更',
  'Amend Commit': 'Commit を修正',
  'Overview': '概要',
  'Condensed Diff': '要約 Diff',
  'What Changed': '変更内容',
  'Chunk Analysis': 'チャンクの分析',
  'Side-by-Side View': '並列表示',
  'Unified View': '統合表示',
  'Full File View': 'ファイル全体表示',
  'Switch to Side-by-Side View': '並列表示に切り替え',
  'Switch to Unified View': '統合表示に切り替え',
  'Switch to Full File View': 'ファイル全体表示に切り替え',
  'Switch to Diff Only': '差分のみの表示に切り替え',
  'Switch to Single-Column View': '1 列表示に切り替え',
  'Original': '変更前',
  'Modified': '変更後',
  'Empty': '空',
  'Deleted': '削除済み',
  'Refresh Worktrees': 'Worktree を再読み込み',
  'Confirm Before Closing Busy Terminals': '処理中のターミナルを閉じる前に確認',
  'Ask for confirmation before closing tabs with running processes or active agents.':
      '実行中のプロセスやアクティブな Agent があるタブを閉じる前に確認します。',
  'Close Unsaved Editor?': '保存していないエディターを閉じますか？',
  'Close Unsaved Editors?': '保存していないエディタータブを閉じますか？',
  'Stop Running Agent?': '実行中の Agent を停止しますか？',
  'Stop Running Command?': '実行中のコマンドを停止しますか？',
  'Close Busy Terminals?': '処理中のターミナルを閉じますか？',
  'Stop And Close': '停止して閉じる',
  'Closing will end the command and every process it started. Anything halfway through will stay halfway through.':
      '閉じると、このコマンドと、そこから起動されたすべてのプロセスが終了します。途中の処理は途中のまま残ります。',
  'New Branch': '新しいブランチ',
  'Existing Branch': '既存のブランチ',
  'Loading files...': 'ファイルを読み込んでいます…',
  'No file changes': 'ファイルの変更はありません',
  'None': 'なし',
  'Project': 'プロジェクト',
  'Section': 'セクション',
  'All': 'すべて',
  'Default': '既定',
  'Non-Default': '既定以外',
  'Copy Command': 'コマンドをコピー',
  'Clone': '複製',
  'Collapse': '折りたたむ',
  'Expand': '展開',
  'Fonts': 'フォント',
  'No themes found.': 'テーマが見つかりません。',
  'Block': 'ブロック',
  'Bar': '縦線',
  'Underline': '下線',
  'New Host': '新規 Host',
  'SSH Targets': 'SSH ターゲット',
  'Connection': '接続',
  'SSH target used by the runtime host.': 'Runtime Host が使用する SSH ターゲットです。',
  'Runtime Bootstrap': 'Runtime のブートストラップ',
  'Install the Alera runtime sidecar on this host.':
      'この Host に Alera の Runtime サイドカーをインストールします。',
  'Bootstrap Plan': 'ブートストラップ計画',
  'Remote hosts unavailable': 'リモート Host を取得できません',
  'No remote hosts': 'リモート Host がありません',
  'Add an SSH target to bootstrap a runtime.':
      'Runtime をブートストラップするには SSH ターゲットを追加してください。',
  'Remote runtime error': 'リモート Runtime のエラー',
  'Not installed': '未インストール',
  'Planned': '計画済み',
  'Installing': 'インストール中',
  'Installed': 'インストール済み',
  'Failed': '失敗',
  'Cancelled': 'キャンセル済み',
  'Auto': '自動',
  'Alias, host, and username are required': 'エイリアス、ホスト、ユーザー名は必須です。',
  'Port must be between 1 and 65535': 'ポートは 1 から 65535 の範囲で指定してください。',
  'Cancel or wait for bootstrap before changing this host':
      'この Host を変更する前に、ブートストラップをキャンセルするか完了を待ってください。',
  'Remote runtime install started': 'リモート Runtime のインストールを開始しました',
  'No copy rules': 'コピールールがありません',
  'No setup commands': 'セットアップコマンドがありません',
  'Overwrite existing destination': '既存の保存先を上書き',
  'Remove Copy Rule': 'コピールールを削除',
  'Remove Setup Command': 'セットアップコマンドを削除',
  'Delete Device': 'デバイスを削除',
  'Rename Device': 'デバイス名を変更',
  'Revoke Device': 'デバイスを無効化',
  'Select Runner': 'Runner を選択',
  'Refresh models': 'モデルを再読み込み',
  'Refresh Models': 'モデルを再読み込み',
  'Refresh Personas': 'Persona を再読み込み',
  'Edit CCS Profile': 'CCS プロファイルを編集',
  'Remove CCS Profile': 'CCS プロファイルを削除',
  'Reorder Agent Profile': 'Agent プロファイルを並べ替え',
  'Clone Profile': 'プロファイルを複製',
  'New Profile': '新規プロファイル',
  'Disable Shortcut': 'ショートカットを無効化',
  'Close Image Preview': '画像プレビューを閉じる',
  'Close Terminal': 'ターミナルを閉じる',
  'Copy Version': 'バージョンをコピー',
  'Application Menu': 'アプリケーションメニュー',
  'Refresh Usage': '使用量を再読み込み',
  'Move Toolbar': 'ツールバーを移動',
  'Previous Match': '前の一致箇所',
  'Next Match': '次の一致箇所',
  'Close Search': '検索を閉じる',
  'Resource Manager': 'リソースマネージャー',
  'The runtime host is not responding. Use the host chip to restart it.':
      'Runtime Host が応答していません。Host チップから再起動してください。',
  'Total CPU across Alera and every terminal it spawned, as a share of everything this machine can run at once.':
      'Alera と、そこから起動されたすべてのターミナルの CPU 使用量の合計を、このマシンが同時に処理できる量に対する割合で示します。',
  'Resident memory of Alera, the runtime host, and every terminal process.':
      'Alera、Runtime Host、およびすべてのターミナルプロセスが現在使用している物理メモリです。',
  'Share of the machine memory these processes hold.':
      'これらのプロセスがマシン全体のメモリに占める割合です。',
  'Memory': 'メモリ',
  'Measuring resource usage': 'リソース使用量を計測しています',
  'No terminal sessions are running': '実行中のターミナルセッションはありません',
  'remote': 'リモート',
  'Unattributed Terminals': '帰属不明のターミナル',
  'Kill Orphan Terminal': '孤立したターミナルを強制終了',
  'Close Terminal Session': 'ターミナルセッションを閉じる',
  'App': 'アプリ',
  'Runtime Host': 'Runtime Host',

  'Pane actions': 'ペインの操作',
  'Dismiss Error': 'エラーを閉じる',
  'New Workspace in This Project': 'このプロジェクトに新規ワークスペース',
  'Expand panel': 'パネルを展開',
  'Collapse panel': 'パネルを折りたたむ',
  'View Diff': 'Diff を表示',
  'Discard Changes': '変更を破棄',
  'Open Preview': 'プレビューを開く',
  'View options': '表示オプション',
  'Refresh Commits': 'Commit を再読み込み',
  'Previous match': '前の一致箇所',
  'Next match': '次の一致箇所',
  'Zoom out': '縮小',
  'Zoom in': '拡大',
  'Hide outline': 'アウトラインを非表示',
  'Replace in file': 'ファイル内を置換',
  'Replace match': '一致箇所を置換',
  'Delete Tag': 'タグを削除',
  'Commit Actions': 'Commit の操作',
  'Clear search results': '検索結果をクリア',
  'Move Up': '上へ移動',
  'Move Down': '下へ移動',
  'Remove Workspace': 'ワークスペースを削除',
  'Open Pull Request Diff': 'Pull Request の Diff を開く',
  'Open Comment': 'コメントを開く',
  'Open Comment Location': 'コメントの位置を開く',
  'Match case': '大文字と小文字を区別',
  'Match whole word': '単語単位で一致',
  'Use regular expression': '正規表現を使用',
  'Preserve case': '大文字と小文字を保持',
  'Replace all': 'すべて置換',
  'Open source file': 'ソースファイルを開く',
  'Open Editor': 'エディターを開く',
  'Open Check': 'チェックを開く',
  'Pull Request Actions': 'Pull Request の操作',
  'Checks': 'チェック',
  'No checks reported': '報告されたチェック結果はありません',
  'Edit Pull Request': 'Pull Request を編集',
  'Open In Browser': 'ブラウザーで開く',
  'Title': 'タイトル',
  'Base Branch': 'ベースブランチ',
  'The base branch is managed by the pull request stack.':
      'ベースブランチは Pull Request Stack が管理しています。',
  'Draft': 'ドラフト',
  'Merged': 'マージ済み',
  'Closed': 'クローズ済み',
  'Comments': 'コメント',
  'Start Conversation': '会話を開始',
  'Add Comment': 'コメントを追加',
  'Add a comment': 'コメントを追加',
  'No comments yet': 'まだコメントはありません',
  'Resolved': '解決済み',
  'No details available': '利用できる詳細はありません',
  'Workflow': 'ワークフロー',
  'Event': 'イベント',
  'Description': '説明',
  'Started': '開始',
  'Completed': '完了',
  '#123 or pull request URL': '#123 または Pull Request の URL',
  'Suggested pull request': '候補の Pull Request',
  'CLI not found': 'CLI が見つかりません',
  'Not authenticated': '認証されていません',
  'No remote': 'Remote がありません',
  'This repository has no remote to detect a provider from.':
      'このリポジトリにはプロバイダーを判定できる Remote がありません。',
  'Provider not detected': 'プロバイダーを検出できません',
  'Could not detect the git hosting provider. Set it in project settings.':
      'Git ホスティングプロバイダーを検出できませんでした。プロジェクト設定で指定してください。',
  'Unsupported provider': 'サポートされていないプロバイダー',
  'This hosting provider is not supported yet.':
      'このホスティングプロバイダーはまだサポートされていません。',

  'Create Options': '作成オプション',
  'Automations unavailable': 'オートメーションを取得できません',
  'No automations': 'オートメーションがありません',
  'Select an automation': 'オートメーションを選択',
  'State': '状態',
  'Profile': 'プロファイル',
  'Tag': 'タグ',

  'No automation details available.': '利用できるオートメーションの詳細はありません。',
  'Create a schedule to run approved work in a runtime-owned target.':
      '承認済みの処理を Runtime 管理下のターゲットで実行するスケジュールを作成します。',
  'Choose an automation to inspect its schedule, target, and runs.':
      'オートメーションを選択すると、スケジュール、ターゲット、実行記録を確認できます。',
  'Linked workspaces require a Git project. Add one to get started.':
      'リンクされたワークスペースには Git プロジェクトが必要です。まずプロジェクトを追加してください。',
  'Create an action to replace selected text with AI.':
      '選択したテキストを AI で置き換える操作を作成します。',
  'Choose an action or create a new one.': '既存の操作を選ぶか、新しい操作を作成してください。',
  'This action and its settings will be removed.': 'この操作とその設定が削除されます。',
  'No usage was found in this range.': 'この期間の使用量データは見つかりませんでした。',
  'No Claude Code, Codex, or Grok Build usage was found in this range.':
      'この期間に Claude Code、Codex、Grok Build の使用量は見つかりませんでした。',
  'Default workspace': '既定のワークスペース',
  'Pinned workspace': 'ピン留めされたワークスペース',
  'Workspace path copied': 'ワークスペースのパスをコピーしました',
  'Workspace slept': 'ワークスペースをスリープしました',
  'No git remote configured for this workspace.':
      'このワークスペースには Git remote が設定されていません。',
  'Could not open the browser.': 'ブラウザーを開けませんでした。',
  'This editor tab has no file.': 'このエディタータブにはファイルがありません。',
  'No commits yet': 'Commit はまだありません',
  'Could not load diff.': 'Diff を読み込めませんでした。',
  'No diff available.': '利用できる Diff はありません。',
  'No stashes to pop': '適用できる Stash がありません',

  'Edit Message': 'メッセージを編集',
  'Message': 'メッセージ',
  'Saving': '保存中',
  'Save And Restart': '保存してやり直す',
  'Save Message': 'メッセージを保存',
  'Saving stops the active turn and replaces this message and all later responses. Files and actions already performed are not undone. Queued messages remain paused.': '保存すると現在のターンが停止し、このメッセージと以降のすべての応答が置き換えられます。すでに実行されたファイル変更や操作は元に戻りません。キュー内のメッセージは一時停止のままです。',
  'The message could not be saved. Your edit is still here.':
      'メッセージを保存できませんでした。編集内容はそのまま残っています。',
  'Queued': 'キュー待ち',
  'Paused': '一時停止中',
  'Resume Queue': 'キューを再開',
  'Pause Queue': 'キューを一時停止',
  'Collapse Queue': 'キューを折りたたむ',
  'Expand Queue': 'キューを展開',
  'Check Delivery': '送信状況を確認',
  'Attachment': '添付ファイル',
  'Sending': '送信中',
  'Steer': '方向づけ',
  'Remove Queued Message': 'キュー内のメッセージを削除',
  'Message Actions': 'メッセージの操作',

  'Ship Changes?': '変更をリリースしますか？',
  'Ship only staged changes, or stage all changes first and include them in the commit.':
      'ステージ済みの変更だけをリリースするか、すべての変更を先にステージして Commit に含めます。',
  'Ship Staged Changes': 'ステージ済みの変更をリリース',
  'Ship All Changes': 'すべての変更をリリース',
  'Runtime Still Has Work': 'Runtime に処理が残っています',
  'Quit And Leave Runtime Open': 'Alera を終了して Runtime は起動したままにする',
  'Force Stop And Quit': '強制停止して Alera を終了',
  'Force Stop Runtime': 'Runtime を強制停止',
  'Force Stop': '強制停止',
  'The runtime still has active work.': 'Runtime にはまだ実行中の処理があります。',
  'The runtime still has active work. Force stop terminates them.':
      'Runtime にはまだ実行中の処理があります。強制停止するとそれらは終了します。',
  'The runtime still has active work. You can quit and leave the runtime running, or force stop it.': 'Runtime にはまだ実行中の処理があります。Alera を終了して Runtime を起動したままにすることも、強制停止することもできます。',

  'Active Run': '実行中のジョブ',
  'Update With': '更新方法',
};
