part of 'alera_localizations.dart';

const Map<String, String> _simplifiedChineseAgents = <String, String>{
  'Map Imported Targets': '对应导入目标',
  'App First': '应用程序优先',
  'Terminal First': '终端优先',
  'From Prompt': '从提示词',
  'Manual': '手动',
  'Daily Activity': '每日活动',
  'Usage': '用量',
  'Local Host': '本地 Host',
  'Updating': '更新中',
  'Showing saved usage while new data loads in the background.':
      '正在后台加载新数据，同时显示已保存的用量数据。',
  'Update Failed': '更新失败',
  '7 Days': '7 天',
  '30 Days': '30 天',
  '90 Days': '90 天',
  'Usage Unavailable': '无法取得用量',
  'No usage data is available for this host.': '此 Host 当前没有可用的用量数据。',
  'Processed Tokens': '已处理 Token',
  'API-Equivalent Cost': 'API 等值成本',
  'Sessions': '会话',
  'Cached Input': '缓存输入',
  'Cache Savings': '缓存节省',
  'Compared with full input rates': '与完整输入费率相比',
  'Tokens read from Claude Code, Codex, and Grok Build transcripts on this host.':
      '从此 Host 上的 Claude Code、Codex 与 Grok Build 转录文本读取的 Token。',
  'Breakdown': '明细',
  'No Activity': '没有活动',
  'No Daily Activity': '没有每日活动',
  'Provider-reported costs': 'Provider 回报的成本',
  'Current model rates': '当前模型费率',
  'Cached model rates': '缓存的模型费率',
  'Pricing unavailable': '无法取得定价',
  'Some model costs may be unavailable because pricing could not be loaded.':
      '由于无法加载定价，部分模型成本可能无法取得。',

  'Profiles': '配置文件',
  'Grouped': '分组',
  'Models': '模型',
  'Tokens': 'Token',
  'Cost': '成本',
  'Responses': '响应数',
  'Terminal unavailable': '终端无法使用',
  'Restart Terminal?': '重启终端？',
  'This Device': '此设备',
  'IP Address': 'IP 地址',
  'DNS Hostname': 'DNS 主机名称',
  'Private Interface': '专用网络接口',
  'All changes for file': '此文件的所有变更',
  'Amend Commit': '修改 Commit',
  'Overview': '概览',
  'Condensed Diff': '精简 Diff',
  'What Changed': '变更内容',
  'Chunk Analysis': '区块分析',
  'Side-by-Side View': '并排视图',
  'Unified View': '统一视图',
  'Full File View': '完整文件视图',
  'Switch to Side-by-Side View': '切换至并排视图',
  'Switch to Unified View': '切换至统一视图',
  'Switch to Full File View': '切换至完整文件视图',
  'Switch to Diff Only': '切换至仅显示差异',
  'Switch to Single-Column View': '切换至单栏视图',
  'Original': '原始',
  'Modified': '修改后',
  'Empty': '空白',
  'Deleted': '已删除',
  'Refresh Worktrees': '刷新工作树',
  'Confirm Before Closing Busy Terminals': '关闭忙碌终端前确认',
  'Ask for confirmation before closing tabs with running processes or active agents.':
      '关闭仍有运行中程序或作用中代理的标签页前先要求确认。',
  'Close Unsaved Editor?': '关闭未保存的编辑器？',
  'Close Unsaved Editors?': '关闭未保存的编辑器标签页？',
  'Stop Running Agent?': '停止运行中的代理？',
  'Stop Running Command?': '停止运行中的命令？',
  'Close Busy Terminals?': '关闭忙碌的终端？',
  'Stop And Close': '停止并关闭',
  'Closing will end the command and every process it started. Anything halfway through will stay halfway through.':
      '关闭后会终止此命令及它启动的所有程序。任何尚未完成的操作都会停在当前状态。',
  'New Branch': '新分支',
  'Existing Branch': '现有分支',
  'Loading files...': '正在加载文件…',
  'No file changes': '没有文件变更',
  'None': '无',
  'Project': '项目',
  'Section': '区段',
  'All': '全部',
  'Default': '默认',
  'Non-Default': '非默认',
  'Copy Command': '复制命令',
  'Clone': '创建副本',
  'Collapse': '折叠',
  'Expand': '展开',
  'Fonts': '字体',
  'No themes found.': '找不到主题。',
  'Block': '方块',
  'Bar': '直线',
  'Underline': '下划线',
  'New Host': '新建主机',
  'SSH Targets': 'SSH 目标',
  'Connection': '连接',
  'SSH target used by the runtime host.': 'Runtime Host 使用的 SSH 目标。',
  'Runtime Bootstrap': '运行时初始化',
  'Install the Alera runtime sidecar on this host.':
      '在此主机安装 Alera Runtime sidecar。',
  'Bootstrap Plan': '初始化计划',
  'Remote hosts unavailable': '无法取得远程主机',
  'No remote hosts': '尚无远程主机',
  'Add an SSH target to bootstrap a runtime.': '添加 SSH 目标以初始化运行时。',
  'Remote runtime error': '远程运行时错误',
  'Not installed': '尚未安装',
  'Planned': '已计划',
  'Installing': '安装中',
  'Installed': '已安装',
  'Failed': '失败',
  'Cancelled': '已取消',
  'Auto': '自动',
  'Alias, host, and username are required': '别名、主机与用户名为必填。',
  'Port must be between 1 and 65535': '端口必须介于 1 到 65535。',
  'Cancel or wait for bootstrap before changing this host':
      '变更此主机前，请取消初始化或等待初始化完成。',
  'Remote runtime install started': '远程运行时已开始安装',
  'No copy rules': '尚无复制规则',
  'No setup commands': '尚无设置命令',
  'Overwrite existing destination': '覆盖现有目标',
  'Remove Copy Rule': '移除复制规则',
  'Remove Setup Command': '移除设置命令',
  'Delete Device': '删除设备',
  'Rename Device': '重命名设备',
  'Revoke Device': '撤销设备',
  'Select Runner': '选择执行器',
  'Refresh models': '刷新模型',
  'Refresh Models': '刷新模型',
  'Refresh Personas': '刷新 Persona',
  'Edit CCS Profile': '编辑 CCS 配置文件',
  'Remove CCS Profile': '移除 CCS 配置文件',
  'Reorder Agent Profile': '重新排序 Agent 配置文件',
  'Clone Profile': '复制配置文件',
  'New Profile': '新建配置文件',
  'Disable Shortcut': '禁用快捷键',
  'Close Image Preview': '关闭图片预览',
  'Close Terminal': '关闭终端',
  'Copy Version': '复制版本',
  'Application Menu': '应用程序菜单',
  'Refresh Usage': '刷新用量',
  'Move Toolbar': '移动工具栏',
  'Previous Match': '上一个匹配项',
  'Next Match': '下一个匹配项',
  'Close Search': '关闭搜索',
  'Resource Manager': '资源管理器',
  'The runtime host is not responding. Use the host chip to restart it.':
      'Runtime Host 没有响应。请使用 Host 状态按钮重启。',
  'Total CPU across Alera and every terminal it spawned, as a share of everything this machine can run at once.':
      'Alera 与其启动之所有终端的 CPU 总用量，以此机器可同时执行的总容量为基准。',
  'Resident memory of Alera, the runtime host, and every terminal process.':
      'Alera、Runtime Host 与所有终端程序当前占用的物理内存。',
  'Share of the machine memory these processes hold.': '这些程序占用整台机器内存的比例。',
  'Memory': '内存',
  'Measuring resource usage': '正在测量资源用量',
  'No terminal sessions are running': '当前没有运行中的终端会话',
  'remote': '远程',
  'Unattributed Terminals': '未归属的终端',
  'Kill Orphan Terminal': '终止孤立终端',
  'Close Terminal Session': '关闭终端会话',
  'App': '应用程序',
  'Runtime Host': 'Runtime Host',

  'Pane actions': '窗格操作',
  'Dismiss Error': '关闭错误',
  'New Workspace in This Project': '在此项目新建工作区',
  'Expand panel': '展开面板',
  'Collapse panel': '折叠面板',
  'View Diff': '查看 Diff',
  'Discard Changes': '丢弃变更',
  'Open Preview': '打开预览',
  'View options': '查看选项',
  'Refresh Commits': '刷新 Commits',
  'Previous match': '上一个匹配项',
  'Next match': '下一个匹配项',
  'Zoom out': '缩小',
  'Zoom in': '放大',
  'Hide outline': '隐藏大纲',
  'Replace in file': '在文件中替换',
  'Replace match': '替换匹配项',
  'Delete Tag': '删除标签',
  'Commit Actions': 'Commit 操作',
  'Clear search results': '清除搜索结果',
  'Move Up': '上移',
  'Move Down': '下移',
  'Remove Workspace': '移除工作区',
  'Open Pull Request Diff': '打开 Pull Request Diff',
  'Open Comment': '打开评论',
  'Open Comment Location': '打开评论位置',
  'Match case': '区分大小写',
  'Match whole word': '全字匹配',
  'Use regular expression': '使用正则表达式',
  'Preserve case': '保留大小写',
  'Replace all': '全部替换',
  'Open source file': '打开源文件',
  'Open Editor': '打开编辑器',
  'Open Check': '打开检查',
  'Pull Request Actions': 'Pull Request 操作',
  'Checks': '检查',
  'No checks reported': '尚未回报任何检查结果',
  'Edit Pull Request': '编辑 Pull Request',
  'Open In Browser': '在浏览器中打开',
  'Title': '标题',
  'Base Branch': '基础分支',
  'The base branch is managed by the pull request stack.':
      '基础分支由 Pull Request Stack 管理。',
  'Draft': '草稿',
  'Merged': '已合并',
  'Closed': '已关闭',
  'Comments': '评论',
  'Start Conversation': '开始对话',
  'Add Comment': '添加评论',
  'Add a comment': '添加评论',
  'No comments yet': '当前还没有评论',
  'Resolved': '已解决',
  'No details available': '没有可用的详细信息',
  'Workflow': '工作流程',
  'Event': '事件',
  'Description': '说明',
  'Started': '开始时间',
  'Completed': '完成时间',
  '#123 or pull request URL': '#123 或 Pull Request URL',
  'Suggested pull request': '建议的 Pull Request',
  'CLI not found': '找不到 CLI',
  'Not authenticated': '尚未验证身份',
  'No remote': '没有 Remote',
  'This repository has no remote to detect a provider from.':
      '此 Repository 没有 Remote，无法据此检测 Provider。',
  'Provider not detected': '未检测到 Provider',
  'Could not detect the git hosting provider. Set it in project settings.':
      '无法检测 Git Hosting Provider，请在项目设置中指定。',
  'Unsupported provider': '不支持的 Provider',
  'This hosting provider is not supported yet.': '当前尚不支持此 Hosting Provider。',

  'Create Options': '创建选项',
  'Automations unavailable': '无法取得自动化',
  'No automations': '没有自动化',
  'Select an automation': '选择自动化',
  'State': '状态',
  'Profile': '配置文件',
  'Tag': '标签',

  'No automation details available.': '没有可用的自动化详细信息。',
  'Create a schedule to run approved work in a runtime-owned target.':
      '创建计划，在运行时管理的目标上执行已批准工作。',
  'Choose an automation to inspect its schedule, target, and runs.':
      '选择自动化以查看计划、目标与执行记录。',
  'Linked workspaces require a Git project. Add one to get started.':
      '关联工作区需要 Git 项目；请先添加项目。',
  'Create an action to replace selected text with AI.': '创建操作，使用 AI 替换选中的文本。',
  'Choose an action or create a new one.': '选择现有操作或创建新操作。',
  'This action and its settings will be removed.': '此操作及其设置将被移除。',
  'No usage was found in this range.': '此范围内没有用量数据。',
  'No Claude Code, Codex, or Grok Build usage was found in this range.':
      '此范围内没有 Claude Code、Codex 或 Grok Build 用量数据。',
  'Default workspace': '默认工作区',
  'Pinned workspace': '已固定工作区',
  'Workspace path copied': '已复制工作区路径',
  'Workspace slept': '工作区已休眠',
  'No git remote configured for this workspace.': '此工作区未设置 Git remote。',
  'Could not open the browser.': '无法打开浏览器。',
  'This editor tab has no file.': '此编辑器标签页没有文件。',
  'No commits yet': '尚无 Commit',
  'Could not load diff.': '无法加载 Diff。',
  'No diff available.': '没有可用的 Diff。',
  'No stashes to pop': '没有可应用的 Stash',

  'Edit Message': '编辑消息',
  'Message': '消息',
  'Saving': '保存中',
  'Save And Restart': '保存并重新开始',
  'Save Message': '保存消息',
  'Saving stops the active turn and replaces this message and all later responses. Files and actions already performed are not undone. Queued messages remain paused.':
      '保存会停止当前的回合，并替换此消息及之后的所有回复。已执行的文件变更与操作不会撤销，队列中的消息会维持暂停。',
  'The message could not be saved. Your edit is still here.':
      '无法保存消息，你的编辑内容仍保留在这里。',
  'Queued': '已排入队列',
  'Paused': '已暂停',
  'Resume Queue': '继续队列',
  'Pause Queue': '暂停队列',
  'Collapse Queue': '折叠队列',
  'Expand Queue': '展开队列',
  'Check Delivery': '检查发送状态',
  'Attachment': '附件',
  'Sending': '发送中',
  'Steer': '引导',
  'Remove Queued Message': '移除队列消息',
  'Message Actions': '消息操作',

  'Ship Changes?': '要发布变更吗？',
  'Ship only staged changes, or stage all changes first and include them in the commit.':
      '仅发布已暂存的变更，或先暂存所有变更并将其纳入 Commit。',
  'Ship Staged Changes': '发布已暂存变更',
  'Ship All Changes': '发布所有变更',
  'Runtime Still Has Work': '运行时仍有工作进行中',
  'Quit And Leave Runtime Open': '结束 Alera 并让运行时保持运行',
  'Force Stop And Quit': '强制停止并结束 Alera',
  'Force Stop Runtime': '强制停止运行时',
  'Force Stop': '强制停止',
  'The runtime still has active work.': '运行时仍有进行中的工作。',
  'The runtime still has active work. Force stop terminates them.':
      '运行时仍有进行中的工作。强制停止会终止这些工作。',
  'The runtime still has active work. You can quit and leave the runtime running, or force stop it.':
      '运行时仍有进行中的工作。你可以结束 Alera 并让运行时保持运行，或强制停止它。',

  'Active Run': '运行中工作',
  'Update With': '使用以下方式更新',
};
