part of 'alera_localizations.dart';

const Map<String, String> _simplifiedChineseShell = <String, String>{
  // Workspace and editor shell.
  'Add Project': '添加项目',
  'New Workspace': '新建工作区',
  'Open Settings': '打开设置',
  'Quick Start': '快速开始',
  'Keyboard Shortcuts': '键盘快捷键',
  'Explorer': '资源管理器',
  'Source Control': '源代码控制',
  'Pull Request': 'Pull Request',
  'Pull Requests': 'Pull Requests',
  'Automations': '自动化',
  'New Terminal': '新建终端',
  'New Tab': '新建标签页',
  'Open in Zed': '在 Zed 中打开',
  'Open in Alera': '在 Alera 中打开',
  'Copy path': '复制路径',
  'Copy relative path': '复制相对路径',
  'New file': '新建文件',
  'New folder': '新建文件夹',
  'Collapse All': '全部折叠',
  'Save all files': '保存所有文件',

  'No projects yet': '尚无项目',
  'Add a git repository to create workspaces with terminal tabs.':
      '添加 Git 仓库以创建含终端标签页的工作区。',
  'Add Your First Project': '添加第一个项目',
  'Unpin Workspace': '取消固定工作区',
  'Pin Workspace': '固定工作区',
  'Pin Workspace Tree': '固定工作区树',
  'Unpin Workspace Tree': '取消固定工作区树',
  'Manage Tags': '管理标签',
  'Set Parent Workspace': '设置父工作区',
  'Clear Parent Workspace': '清除父工作区',
  'Set Section': '设置区段',
  'Clear Section': '清除区段',
  'Open in Browser': '在浏览器中打开',
  'Open in Project Settings': '在项目设置中打开',
  'Copy Path': '复制路径',
  'Sleep': '休眠',
  'Folder name': '文件夹名称',
  'File name': '文件名称',
  'Name': '名称',
  'Path copied': '已复制路径',
  'Relative path copied': '已复制相对路径',
  'Duplicate': '创建副本',
  'Show ignored files': '显示忽略的文件',
  'Hide ignored files': '隐藏忽略的文件',
  'Show hidden items': '显示隐藏项目',
  'Hide hidden items': '不显示隐藏项目',
  'Source control root': '源代码控制根目录',
  'Clear Source Control Root': '清除源代码控制根目录',
  'Use As Source Control Root': '设为源代码控制根目录',
  'Collapse folder': '折叠文件夹',
  'Move this item to the trash?': '要将此项目移到回收站吗？',
  'Open File': '打开文件',
  'Reveal in Explorer': '在资源管理器中显示',
  'Stage': '暂存',
  'Unstage': '取消暂存',
  'Discard': '丢弃',
  'All Changes': '所有变更',
  'Show Flat List': '显示平铺列表',
  'Show Tree': '显示树状视图',
  'Show All Changes': '显示所有变更',
  'Group By Staged State': '按暂存状态分组',
  'Hide File Filter': '隐藏文件筛选',
  'Search Files': '搜索文件',
  'Expand All': '全部展开',
  'Filter files...': '筛选文件…',
  'Stop generating commit message': '停止生成 Commit 消息',
  'Generate commit message with AI': '使用 AI 生成 Commit 消息',
  'Source Control Actions': '源代码控制操作',
  'Commit': 'Commit',
  'Commit & Push': 'Commit 并 Push',
  'Commit & Sync': 'Commit 并同步',
  'Commit Amend': '修改上一个 Commit',
  'Stage All': '全部暂存',
  'Unstage All': '全部取消暂存',
  'Discard All': '全部丢弃',
  'Open Changes in Zed': '在 Zed 中打开变更',
  'Fetch': 'Fetch',
  'Pull': 'Pull',
  'Push': 'Push',
  'Sync': '同步',
  'Publish Branch': '发布分支',
  'Stash': 'Stash',
  'Stash Pop': '应用 Stash',
  'Sleep Project': '休眠项目',
  'Sleep Project?': '要让项目休眠吗？',
  'Sleep All': '全部休眠',
  'Project workspaces slept': '项目工作区已休眠',
  'Open with Default Application': '使用默认应用程序打开',
  'Refresh Outline': '刷新大纲',
  'Outline': '大纲',
  'No symbols': '没有符号',
  'Show Outline': '显示大纲',
  'Diff Overview': '差异概览',
  'All Branches': '所有分支',
  'Current Branch': '当前分支',
  'Current': '当前',
  'Search branches': '搜索分支',
  'No matching branches': '没有匹配的分支',
  'Branch Perspective': '分支视图',
  'Branch': '分支',
  'Waiting for input': '等待输入',
  'Blocked': '受阻',
  'Interrupted': '已中断',
  'Done (Unread)': '完成（未读）',
  'Show Agent Runs': '显示 Agent 执行',
  'Hide Agent Runs': '隐藏 Agent 执行',
  'Copy Commit Hash': '复制 Commit Hash',
  'Copy Commit Subject': '复制 Commit 标题',
  'Add Tag…': '添加标签…',
  'Create Branch Here…': '在此创建分支…',
  'Create Worktree Here…': '在此创建 Worktree…',
  'Checkout Commit': 'Checkout 此 Commit',
  'Cherry Pick': 'Cherry Pick',
  'Revert Commit': '还原 Commit',
  'Drop Commit': '移除 Commit',
  'Merge Into Current Branch': '合并到当前分支',
  'Rebase Current Branch Onto This Commit': '将当前分支 Rebase 到此 Commit',
  'Reset Current Branch Here': '将当前分支重置到此处',
  'Soft': 'Soft',
  'Mixed': 'Mixed',
  'Hard': 'Hard',
  'Create Archive…': '创建归档档…',
  'Copy Tag Name': '复制标签名称',
  'Copy Branch Name': '复制分支名称',
  'Switch to Branch': '切换到分支',
  'Rename Branch...': '重命名分支…',
  'Delete Branch': '删除分支',
  'Merge into Current Branch': '合并到当前分支',
  'Create Archive...': '创建归档档…',
  'Open in New Worktree': '在新 Worktree 中打开',
  'Checkout Remote Branch': 'Checkout 远程分支',
  'Delete Remote Branch': '删除远程分支',
  'Pull into Current Branch': 'Pull 到当前分支',
  'Open in New Worktree...': '在新 Worktree 中打开…',
  'Push Tag': 'Push 标签',
  'Stash Changes': 'Stash 变更',
  'Discard All Changes': '丢弃所有变更',
  'Commit Changes...': 'Commit 变更…',
  'Create Branch Here': '在此创建分支',
  'Branch Name': '分支名称',
  'Create Branch': '创建分支',
  'Create Worktree': '创建 Worktree',
  'Create Archive': '创建归档档',
  'Archive Path': '归档档路径',
  'Add Tag': '添加标签',
  'Tag Name': '标签名称',
  'Message (Optional)': '消息（可选）',
  'Tag name is required': '标签名称为必填。',
  'Drop Commit?': '要移除此 Commit 吗？',
  'Drop': '移除',
  'Merge Commit?': '要合并此 Commit 吗？',
  'Merge': '合并',
  'Rebase Current Branch?': '要 Rebase 当前分支吗？',
  'Rebase': 'Rebase',
  'File saved': '文件已保存',
  'Changes discarded': '变更已丢弃',
  'File overwritten': '文件已覆盖',
  'Autosave paused because the file changed on disk.': '文件已在磁盘上变更，因此已暂停自动保存。',
  'File changed on disk': '文件已在磁盘上变更',
  'Overwrite the file with the editor contents?': '要用编辑器内容覆盖文件吗？',
  'Overwrite': '覆盖',
  'File cannot be edited': '无法编辑此文件',
  'File not found': '找不到文件',
  'File is outside the workspace': '文件位于工作区外',
  'File is protected': '文件受到保护',
  'File operation failed': '文件操作失败',
  'Item already exists': '项目已存在',
  'Path is protected': '路径受到保护',
  'Path is outside the workspace': '路径位于工作区外',
  'Operation is unsupported': '不支持此操作',
  'Item not found': '找不到项目',
  'Quick Open': '快速打开',
  'Search workspace files': '搜索工作区文件',
  'Include Git-ignored files': '包含 Git 忽略的文件',
  'Use Up and Down to navigate, Enter to open, or Escape to close.':
      '使用上、下方向键移动，Enter 打开，Escape 关闭。',
  'Loading workspace files...': '正在加载工作区文件…',
  'Could not load workspace files.': '无法加载工作区文件。',
  'No files are available in this workspace.': '此工作区没有可用的文件。',
  'No files match': '没有匹配的文件：',
  'Command Palette': '命令面板',
  'Search commands': '搜索命令',
  'Use Up and Down to navigate, Enter to run, or Escape to close.':
      '使用上、下方向键移动，Enter 执行，Escape 关闭。',
  'No commands are available.': '当前没有可用的命令。',
  'No commands match': '没有匹配的命令：',
  'No shortcut': '无快捷键',
  'How shortcuts behave while a terminal is focused.': '设置终端取得焦点时快捷键的行为。',
  'When a Terminal Is Focused': '终端取得焦点时',
  'App first lets Alera capture combinations the shell would otherwise receive. Terminal first defers to the shell.':
      '“应用程序优先”会让 Alera 拦截原本会传给 Shell 的组合键；“终端优先”则优先交由 Shell 处理。',
  'Stop Recording': '停止录制',
  'Change Shortcut': '更改快捷键',
  'Press keys… (Esc to cancel)': '请按下快捷键…（Esc 取消）',
  'Disabled': '已禁用',
  'Unassigned': '未分配',
  'Shortcut already in use': '快捷键已被使用',
  'Reassign': '重新分配',
  'Enter a shortcut like Ctrl+Shift+P.': '请输入快捷键，例如 Ctrl+Shift+P。',
  'A shortcut can only have one main key.': '快捷键只能有一个主要按键。',
  'Add a main key, like P or Enter.': '请加入主要按键，例如 P 或 Enter。',
  'Use either Mod or a platform-specific modifier, not both.':
      '请使用 Mod 或平台专用修饰键其中一种，不要同时使用。',
  'Include at least one modifier key.': '请至少包含一个修饰键。',
  'Press a non-modifier key too.': '请再按下一个非修饰键。',
  'Unsupported key.': '不支持此按键。',
  'Go to Tab 1': '前往标签页 1',
  'Go to Tab 2': '前往标签页 2',
  'Go to Tab 3': '前往标签页 3',
  'Go to Tab 4': '前往标签页 4',
  'Go to Tab 5': '前往标签页 5',
  'Go to Tab 6': '前往标签页 6',
  'Go to Tab 7': '前往标签页 7',
  'Go to Tab 8': '前往标签页 8',
  'Go to Last Tab': '前往最后一个标签页',
  'Open the settings dialog.': '打开设置对话框。',
  'Open the runtime-local automation manager.': '打开此运行时的自动化管理器。',
  'Search and open a file in the active workspace.': '搜索并打开当前工作区中的文件。',
  'Search and run an Alera command.': '搜索并执行 Alera 命令。',
  'Open the add-project dialog.': '打开添加项目对话框。',
  'Collapse or expand the project sidebar.': '折叠或展开项目侧边栏。',
  'Create a linked workspace for the active Git project.':
      '为当前的 Git 项目创建关联工作区。',
  'Open the active workspace in the configured external editor.':
      '在已设置的外部编辑器中打开当前工作区。',
  'Go to the previously selected workspace.': '前往先前选择的工作区。',
  'Go to the next workspace in navigation history.': '前往导航记录中的下一个工作区。',
  'Open workspace search.': '打开工作区搜索。',
  'Search the active terminal scrollback.': '搜索当前终端的滚动缓冲内容。',
  'Show or hide the prompt composer for the active terminal.':
      '显示或隐藏当前终端的提示词输入区。',
  'Open workspace search and replace.': '打开工作区搜索与替换。',
  'Save the active editor file.': '保存当前编辑器文件。',
  'Open a terminal tab in the active workspace.': '在当前工作区打开终端标签页。',
  'Close the active terminal tab.': '关闭当前的终端标签页。',
  'Select the next tab in the active pane.': '选择当前窗格中的下一个标签页。',
  'Select the previous tab in the active pane.': '选择当前窗格中的上一个标签页。',
  'Select the first tab in the active pane.': '选择当前窗格中的第一个标签页。',
  'Select the second tab in the active pane.': '选择当前窗格中的第二个标签页。',
  'Select the third tab in the active pane.': '选择当前窗格中的第三个标签页。',
  'Select the fourth tab in the active pane.': '选择当前窗格中的第四个标签页。',
  'Select the fifth tab in the active pane.': '选择当前窗格中的第五个标签页。',
  'Select the sixth tab in the active pane.': '选择当前窗格中的第六个标签页。',
  'Select the seventh tab in the active pane.': '选择当前窗格中的第七个标签页。',
  'Select the eighth tab in the active pane.': '选择当前窗格中的第八个标签页。',
  'Select the last tab in the active pane.': '选择当前窗格中的最后一个标签页。',
  'Split the active pane to the right with a new terminal.':
      '在当前窗格右侧分割并打开新的终端。',
  'Split the active pane downward with a new terminal.': '在当前窗格下方分割并打开新的终端。',
  'Merge the active pane back into its sibling.': '将当前窗格合并回相邻窗格。',
  'Global': '全局',
  'Workspace': '工作区',
  'Tabs': '标签页',
  'Panes': '窗格',
  'Open Automations': '打开自动化',
  'Open Workspace in External Editor': '在外部编辑器中打开工作区',
  'Toggle Sidebar': '切换侧边栏',
  'Go Back': '返回',
  'Go Forward': '前进',
  'Find in Files': '在文件中查找',
  'Find in Terminal': '在终端中查找',
  'Toggle Terminal Composer': '切换终端输入区',
  'Replace in Files': '在文件中替换',
  'Save File': '保存文件',
  'New Terminal Tab': '新建终端标签页',
  'Close Tab': '关闭标签页',
  'Next Tab': '下一个标签页',
  'Previous Tab': '上一个标签页',
  'Split Right': '向右分割',
  'Split Down': '向下分割',
  'Close Split': '关闭分割窗格',
  'Select Folder': '选择文件夹',
  'Select Parent Folder': '选择父文件夹',
  'Choose Parent Folder': '选择父文件夹',
  'Choose an existing local folder or clone a Git repository from a URL.':
      '选择现有本地文件夹，或从 URL 克隆 Git 仓库。',
  'Local Folder': '本地文件夹',
  'Clone From URL': '从 URL 克隆',
  'Project Path': '项目路径',
  'Destination Folder': '目标文件夹',
  'Auth Method': '认证方式',
  'Authentication': '验证方式',
  'Key': '密钥',
  'Password': '密码',
  'Platform': '平台',
  'Architecture': '架构',
  'Parent Workspace': '父工作区',
  'No Parent': '无父工作区',
  'Section Name': '区段名称',
  'Terminal Title': '终端标题',
  'Configuration is stored in your Alera account and can be read by the service. Review custom commands and prompts for embedded secrets. Credentials and device permissions stay local.':
      '配置会保存在你的 Alera 账户中，服务可读取这些配置。请检查自定义命令与提示词是否包含机密信息；凭据与设备权限仍只保留在本地。',
  'Review Changes': '查看变更',
  'History': '历史记录',
  'Retry Pending Upload': '重试待上传项目',
  'Shared version': '共享版本',
  'Comparing': '比较版本',
  'differences': '项差异',
  'unresolved': '项未解决',
  'Keep All Local': '全部保留本地版本',
  'Keep All Remote': '全部保留远程版本',
  'Both sides changed this value. Choose what to keep.':
      '本地与远程都修改了此值，请选择要保留哪一个。',
  'Local': '本地',
  'Remote': '远程',
  'Choose A Value': '选择一个值',
  'Keep Local': '保留本地版本',
  'Keep Remote': '保留远程版本',
  'Action Name': '操作名称',
  'Profile Name': '配置文件名称',
  'Result': '结果',
  'Unresolved': '未解决',
  '(Removed)': '（已移除）',
  'These changes apply only to': '这些变更只会应用到',
  'Apply To Device': '应用到设备',
  'Apply And Upload': '应用并上传',
  'Leaving this screen without applying keeps your configuration unchanged. If upload fails after applying, local changes remain pending.':
      '离开此界面而不应用时，设置会保持不变。若应用后上传失败，本地变更会保留为待上传状态。',
  'Version': '版本',
  'Compare': '比较',
  'Shell environment reloaded': 'Shell 环境已重新加载',
  'PATH entries': '个 PATH 项目',
  'Could not reload shell environment': '无法重新加载 Shell 环境',
  'Could not open link': '无法打开链接',
  'No external editor is installed.': '未安装支持的外部编辑器。',
  'Could not open file in the external editor.': '无法在外部编辑器中打开文件。',
  'Existing Branch *': '现有分支 *',
  'New Branch Name *': '新分支名称 *',
  'Workspace Name (Optional)': '工作区名称（可选）',
  'Search projects': '搜索项目',
  'Search Workspaces': '搜索工作区',
  'Search workspaces': '搜索工作区',
  'Replace': '替换',
  'Files to include': '要包含的文件',
  'Files to exclude': '要排除的文件',
  'Hide details': '隐藏详细信息',
  'Show details': '显示详细信息',
  'Hide replace': '隐藏替换字段',
  'Show replace': '显示替换字段',
  'Search Terminal': '搜索终端',
  'Search PDF': '搜索 PDF',
  'Add tag…': '添加标签…',
  'Add project…': '添加项目…',
  'Terminal Input': '终端输入',
  'Display Name (Optional)': '显示名称（可选）',
  'Alera will detect whether the folder is a Git repository. Non-Git folders only get a primary workspace.':
      'Alera 会检测文件夹是否为 Git 仓库；非 Git 文件夹只会创建主要工作区。',
  'Alera will run git clone into the destination folder and register the cloned repository.':
      'Alera 会在目标文件夹执行 git clone，并注册克隆完成的仓库。',
  'Native folder picker is not available; paste path manually.':
      '无法使用系统文件夹选择器，请手动粘贴路径。',

  'Edit': '编辑',
  'Back': '返回',
  'Next': '下一步',
  'Done': '完成',
  'Add': '添加',
  'Start': '启动',
  'Stop': '停止',
  'Select': '选择',
  'Confirm': '确认',
  'Update': '更新',
  'Download': '下载',
  'Approve': '批准',
  'Reject': '拒绝',
  'Open Usage': '打开用量',
  'Remove Token': '移除 Token',
  'Check For Updates': '检查更新',
  'Resume': '继续执行',
  'Extend': '延长',
  'Run': '执行',
  'Continue Active': '继续当前执行',
  'Cancel Active': '取消当前执行',
  'Save Automation': '保存自动化',
  'Run Now': '立即执行',
  'Restore': '恢复',
  'Trash': '移至回收站',
  'New Automation': '新建自动化',
  'Post Comment': '发布评论',
  'Link': '链接',
  'Create Stack': '创建 Stack',
  'Link Existing Pull Request': '关联现有 Pull Request',
  'Create Pull Request': '创建 Pull Request',
  'Test Command': '测试命令',
  'Add CCS Profile': '添加 CCS 配置文件',
  'Save Profile': '保存配置文件',
  'Check Environment': '检查环境',
  'Take Back This Terminal': '取回此终端',
  'Take Back All Terminals': '取回所有终端',
  'Take Back': '取回',
  'Add Git Project': '添加 Git 项目',
  'Use Custom Command': '使用自定义命令',
  'Continue Manually': '手动继续',
  'Open Workspace': '打开工作区',
  'Retry Agent': '重试 Agent',
  'Create And Start Agent': '创建并启动 Agent',
  'Cancel Download': '取消下载',
  'Remove Model': '移除模型',
  'Update Runtime': '更新 Runtime',
  'Kill All': '全部终止',
  'A reading diff is an AI-guided, non-applicable abbreviation of the original diff.':
      '阅读 Diff 是由 AI 引导生成、不可直接应用的原始 Diff 精简版本。',
  'This overview explains the behavioral changes selected while condensing the diff. It does not identify bugs or security findings. Open Condensed Diff to inspect the retained source changes, or return to the original diff for the complete patch.': '此概览说明精简 Diff 时保留的行为变更，不代表错误或安全检查结果。请打开“精简 Diff”查看保留的源代码变更，或返回原始 Diff 查看完整 Patch。',
  'Cached Result': '缓存结果',
  'Preparing reading diff': '正在准备阅读 Diff',
  'Loading cached reading diff': '正在加载缓存的阅读 Diff',
  'Loading the immutable diff and splitting it at safe boundaries.':
      '正在加载不可变更的 Diff，并在安全边界处分割。',
  'Using a previously generated and validated result.': '使用先前已生成并验证的结果。',
  'The agent is proposing safe elisions; Rust validates the plan.':
      'Agent 正在提出安全的省略方案；Rust 会验证该方案。',
  'Rust rejected the plan; the agent is replacing it once.':
      'Rust 已拒绝此方案；Agent 正在重新生成一次替代方案。',
  'Rust is merging the validated chunks into the final reading diff.':
      'Rust 正在将已验证的区块合并为最终阅读 Diff。',
  'Reading diff generation failed': '阅读 Diff 生成失败',
  'This manually runs the configured AI Assist agent and may consume subscription quota or other provider usage. The complete selected patch is provided, including portions hidden by preview truncation.': '这会手动执行已设置的 AI Assist Agent，可能消耗订阅额度或其他 Provider 用量。系统会提供完整的所选 Patch，包括预览截断而隐藏的部分。',
  'The result opens with a behavioral overview and a condensed, non-applicable diff. It is not a bug or security review.':
      '结果会先显示行为概览及不可直接应用的精简 Diff；这不是错误或安全审查。',
  'Agent': 'Agent',
  'Model': '模型',
  'Effort': '推理强度',
  'Access': '访问权限',
  'Diff Size': 'Diff 大小',
  'Chunks': '区块数',
  'Agent Default': 'Agent 默认值',
  'Repository Read Only': 'Repository 只读',
  'Diff Only': '仅限 Diff',
  'Could not prepare': '无法准备',
  'condensed diff': '精简 Diff',

  'Generate Reading Diff': '生成阅读 Diff',
  'Install Update': '安装更新',
  'Restart Alera': '重启 Alera',
  'Run Update': '执行更新',
  'View Output': '查看输出',
  'New Action': '新建操作',
  'Cancel Offer': '取消配对邀请',
  'Add Copy Rule': '添加复制规则',
  'Add Setup Command': '添加设置命令',
  'Use Repo File': '使用仓库文件',
  'Plan': '计划',
  'Bootstrap': '初始化',
  'Copy Output': '复制输出',
  'Restart Terminal': '重启终端',
  'Reconnect': '重新连接',
  'Amend': '修改 Commit',

  'Run Precheck': '执行前置检查',
  'Audited Draft Test': '审计草稿测试',
  'Approve Exact Revision': '批准指定版本',
  'Skip': '跳过',
  'Queue': '排入队列',
  'Run Latest Once': '执行最新版本一次',
  'Force Parallel': '强制并行执行',
  'Pause Automation': '暂停自动化',
  'Choose what to do with active runs.': '选择如何处理当前运行中的工作。',
  'Loading automation policy...': '正在加载自动化策略…',
  'Automation Policy Unavailable': '无法取得自动化策略',
  'Automation Permissions': '自动化权限',
  'Choose whether this profile may administer active definitions and whether it may execute them.':
      '选择此配置文件是否可管理作用中的自动化定义，以及是否可执行它们。',
  'May Activate Or Edit Active Automations': '可启用或编辑作用中的自动化',
  'Allow a managed agent using this profile to activate or edit an active definition.':
      '允许使用此配置文件的受管理 Agent 启用或编辑作用中的自动化定义。',
  'May Execute Automations': '可执行自动化',
  'Opt this profile into scheduled and manual automation execution.':
      '允许此配置文件执行计划与手动自动化。',
  'Project Automation Policy Unavailable': '无法取得项目自动化策略',
  'Automation Policy': '自动化策略',
  'Repository declaration is read from alera.toml. Local approval can only restrict execution.':
      'Repository 声明会从 alera.toml 读取；本地批准只能进一步限制执行。',
  'Repository Declares Automations': 'Repository 声明自动化',
  'The repository declares automation use in alera.toml.':
      'Repository 已在 alera.toml 声明使用自动化。',
  'Add an automation declaration to alera.toml before execution.':
      '执行前请先在 alera.toml 新增自动化声明。',
  'Require Local Approval': '需要本地批准',
  'Require an explicit human approval in addition to the repository declaration.':
      '除了 Repository 声明外，还需要明确的人工批准。',
  'Local Approval Granted': '已授予本地批准',
  'Grant the local approval required by a restrictive project policy.':
      '授予限制性项目策略所要求的本地批准。',
  'Loading Automation Settings': '正在加载自动化设置',
  'Reading runtime automation settings.': '正在读取运行时的自动化设置。',
  'Automation Settings Unavailable': '无法取得自动化设置',
  'Automation History And Autostart': '自动化历史与自动启动',
  'Keep scheduled work available without a window and control local retention.':
      '让计划工作在没有窗口时仍可执行，并控制本地保留期限。',
  'Start Automations At Login': '登录时启动自动化',
  'Start the persistent local automation host when you sign in. This is off by default.':
      '登录时启动常驻的本地自动化 Host；默认为关闭。',
  'Run History Retention': '执行历史保留期限',
  'Keep final runs for at most this many days.': '最多保留已完成执行记录这么多天。',
  'Audit Retention': '审计保留期限',
  'Keep automation audit events for at most this many days.':
      '最多保留自动化审计事件这么多天。',
  'Trash Retention': '回收站保留期限',
  'Permanently remove trashed definitions after this many days.':
      '回收站中的定义超过此天数后永久删除。',
  'days': '天',

  'Notify On Success': '成功时通知',
  'Prompt Preview': '提示词预览',
  'Automation unavailable': '无法取得自动化',
  'Pause': '暂停',
  'Runs': '执行记录',
  'Audit': '审计',
  'Slug': 'Slug',
  'Schedule': '计划',
  'Cron / time': 'Cron / 时间',
  'Target': '目标',
  'Policies': '策略',
  'Limits': '限制',
  'Tags': '标签',
  'Revision': '版本',
  'Prompt': '提示词',
  'Effective Policy': '生效策略',
  'Signature Timeline': '签名时间轴',
  'Overlap': '重叠处理',

  'No active run or upcoming occurrence.': '当前没有运行中或即将开始的工作。',
  'Scheduled occurrence': '计划执行',
  'No runs yet.': '尚无执行记录。',
  'No audit events yet.': '尚无审计事件。',
  'Import Automations': '导入自动化',
  'Edit Automation': '编辑自动化',
  'Project (Optional)': '项目（可选）',
  'Tag Ids (Comma-separated)': '标签 ID（以逗号分隔）',
  'Prompt Template': '提示词模板',
  'Five-field Cron': '五段 Cron',
  'Run At (UTC)': '执行时间（UTC）',
  'IANA Timezone': 'IANA 时区',
  'Start At (Optional ISO-8601 UTC)': '开始时间（可选，ISO-8601 UTC）',
  'End At (Optional ISO-8601 UTC)': '结束时间（可选，ISO-8601 UTC）',
  'Maximum Scheduled Runs (Optional)': '最大计划执行次数（可选）',
  'Source Workspace': '来源工作区',
  'Tab': '标签页',
  'Agent Conversation ID': 'Agent 对话 ID',
  'Agent Profile': 'Agent 配置文件',
  'Source Branch': '来源 Branch',
  'Workspace Name Template': '工作区名称模板',
  'Precheck Command (Optional)': '前置检查命令（可选）',
  'Precheck Timeout (Seconds)': '前置检查超时（秒）',
  'Setup': '设置',
  'Misfire': '错过计划',
  'Cleanup': '清理',
  'Queue Cap (Maximum 10)': '队列上限（最多 10）',
  'Inactivity Timeout (Seconds)': '空闲超时（秒）',
  'Heartbeat Interval (Seconds)': 'Heartbeat 间隔（秒）',
  'Retry Attempts (Maximum 3)': '重试次数（最多 3）',
  'Retry Backoff (Seconds)': '重试退避（秒）',
  'Circuit Failure Threshold': 'Circuit 失败阈值',
  'Circuit Open (Seconds)': 'Circuit 打开时间（秒）',
  'Select...': '请选择…',
  'One-time': '单次',
  'Existing Tab': '现有标签页',
  'Fresh Tab': '新标签页',
  'Managed Workspace': '受管理工作区',
  'Name, slug, and prompt template are required.': '名称、slug 与提示词模板为必填。',
  'The existing tab requires workspace, tab, and conversation ids.':
      '现有标签页需要 workspace、tab 与 conversation ID。',
  'The selected target requires its ids.': '所选目标需要填写对应 ID。',
  'Prompt template contains an unmatched closing delimiter.':
      '提示词模板包含未配对的结束分隔符。',
  'Prompt template contains an unterminated variable.': '提示词模板包含未结束的变量。',
  'Versioned JSON Catalog': '版本化 JSON Catalog',
  'Source Key To Local Id JSON': '来源 Key 到本地 ID 的 JSON',
  'Map every source key to an existing local id.': '将每个来源 Key 对应到现有的本地 ID。',
  'Automation created': '已创建自动化',
  'Automation saved': '已保存自动化',
  'Automation cloned': '已复制自动化',
  'Automation catalog copied to clipboard': '自动化 Catalog 已复制到剪贴板',
  'Automation catalog imported as drafts': '自动化 Catalog 已以草稿导入',
  'Automation approved': '已批准自动化',
  'Automation run started': '自动化执行已开始',
  'Automation paused': '自动化已暂停',
  'Automation resumed': '自动化已继续',
  'Automation cancellation requested': '已要求取消自动化',
  'Waiting run resumed': '等待中的执行已继续',
  'Waiting run extended': '已延长等待中的执行',
};
