part of 'alera_localizations.dart';

const Map<String, String> _traditionalChineseAgents = <String, String>{
  'Map Imported Targets': '對應匯入目標',
  'App First': '應用程式優先',
  'Terminal First': '終端機優先',
  'From Prompt': '從提示詞',
  'Manual': '手動',
  'Daily Activity': '每日活動',
  'Usage': '用量',
  'Local Host': '本機 Host',
  'Updating': '更新中',
  'Showing saved usage while new data loads in the background.':
      '正在背景載入新資料，同時顯示已儲存的用量資料。',
  'Update Failed': '更新失敗',
  '7 Days': '7 天',
  '30 Days': '30 天',
  '90 Days': '90 天',
  'Usage Unavailable': '無法取得用量',
  'No usage data is available for this host.': '此 Host 目前沒有可用的用量資料。',
  'Processed Tokens': '已處理 Token',
  'API-Equivalent Cost': 'API 等值成本',
  'Sessions': '工作階段',
  'Cached Input': '快取輸入',
  'Cache Savings': '快取節省',
  'Compared with full input rates': '與完整輸入費率相比',
  'Tokens read from Claude Code, Codex, and Grok Build transcripts on this host.':
      '從此 Host 上的 Claude Code、Codex 與 Grok Build 逐字稿讀取的 Token。',
  'Breakdown': '明細',
  'No Activity': '沒有活動',
  'No Daily Activity': '沒有每日活動',
  'Provider-reported costs': 'Provider 回報的成本',
  'Current model rates': '目前模型費率',
  'Cached model rates': '快取的模型費率',
  'Pricing unavailable': '無法取得定價',
  'Some model costs may be unavailable because pricing could not be loaded.':
      '由於無法載入定價，部分模型成本可能無法取得。',

  'Profiles': '設定檔',
  'Grouped': '分組',
  'Models': '模型',
  'Tokens': 'Token',
  'Cost': '成本',
  'Responses': '回應數',
  'Terminal unavailable': '終端機無法使用',
  'Restart Terminal?': '重新啟動終端機？',
  'This Device': '此裝置',
  'IP Address': 'IP 位址',
  'DNS Hostname': 'DNS 主機名稱',
  'Private Interface': '私有介面',
  'All changes for file': '此檔案的所有變更',
  'Amend Commit': '修改 Commit',
  'Overview': '總覽',
  'Condensed Diff': '精簡 Diff',
  'What Changed': '變更內容',
  'Chunk Analysis': '區塊分析',
  'Side-by-Side View': '並排檢視',
  'Unified View': '統一檢視',
  'Full File View': '整檔檢視',
  'Switch to Side-by-Side View': '切換至並排檢視',
  'Switch to Unified View': '切換至統一檢視',
  'Switch to Full File View': '切換至整檔檢視',
  'Switch to Diff Only': '切換至僅顯示差異',
  'Switch to Single-Column View': '切換至單欄檢視',
  'Original': '原始',
  'Modified': '修改後',
  'Empty': '空白',
  'Deleted': '已刪除',
  'Refresh Worktrees': '重新整理工作樹',
  'Confirm Before Closing Busy Terminals': '關閉忙碌終端機前確認',
  'Ask for confirmation before closing tabs with running processes or active agents.':
      '關閉仍有執行中程序或作用中代理程式的分頁前先要求確認。',
  'Close Unsaved Editor?': '關閉未儲存的編輯器？',
  'Close Unsaved Editors?': '關閉未儲存的編輯器分頁？',
  'Stop Running Agent?': '停止執行中的代理程式？',
  'Stop Running Command?': '停止執行中的命令？',
  'Close Busy Terminals?': '關閉忙碌的終端機？',
  'Stop And Close': '停止並關閉',
  'Closing will end the command and every process it started. Anything halfway through will stay halfway through.':
      '關閉後會終止此命令及它啟動的所有程序。任何尚未完成的操作都會停在目前狀態。',
  'New Branch': '新分支',
  'Existing Branch': '現有分支',
  'Loading files...': '正在載入檔案…',
  'No file changes': '沒有檔案變更',
  'None': '無',
  'Project': '專案',
  'Section': '區段',
  'All': '全部',
  'Default': '預設',
  'Non-Default': '非預設',
  'Copy Command': '複製指令',
  'Clone': '建立副本',
  'Collapse': '收合',
  'Expand': '展開',
  'Fonts': '字型',
  'No themes found.': '找不到佈景主題。',
  'Block': '方塊',
  'Bar': '直線',
  'Underline': '底線',
  'New Host': '新增主機',
  'SSH Targets': 'SSH 目標',
  'Connection': '連線',
  'SSH target used by the runtime host.': 'Runtime Host 使用的 SSH 目標。',
  'Runtime Bootstrap': '執行環境初始化',
  'Install the Alera runtime sidecar on this host.':
      '在此主機安裝 Alera Runtime sidecar。',
  'Bootstrap Plan': '初始化規劃',
  'Remote hosts unavailable': '無法取得遠端主機',
  'No remote hosts': '尚無遠端主機',
  'Add an SSH target to bootstrap a runtime.': '新增 SSH 目標以初始化執行環境。',
  'Remote runtime error': '遠端執行環境錯誤',
  'Not installed': '尚未安裝',
  'Planned': '已規劃',
  'Installing': '安裝中',
  'Installed': '已安裝',
  'Failed': '失敗',
  'Cancelled': '已取消',
  'Auto': '自動',
  'Alias, host, and username are required': '別名、主機與使用者名稱為必填。',
  'Port must be between 1 and 65535': '連接埠必須介於 1 到 65535。',
  'Cancel or wait for bootstrap before changing this host':
      '變更此主機前，請取消初始化或等待初始化完成。',
  'Remote runtime install started': '遠端執行環境已開始安裝',
  'No copy rules': '尚無複製規則',
  'No setup commands': '尚無設定指令',
  'Overwrite existing destination': '覆寫現有目的地',
  'Remove Copy Rule': '移除複製規則',
  'Remove Setup Command': '移除設定指令',
  'Delete Device': '刪除裝置',
  'Rename Device': '重新命名裝置',
  'Revoke Device': '撤銷裝置',
  'Select Runner': '選擇執行器',
  'Refresh models': '重新整理模型',
  'Refresh Models': '重新整理模型',
  'Refresh Personas': '重新整理 Persona',
  'Edit CCS Profile': '編輯 CCS 設定檔',
  'Remove CCS Profile': '移除 CCS 設定檔',
  'Reorder Agent Profile': '重新排序 Agent 設定檔',
  'Clone Profile': '複製設定檔',
  'New Profile': '新增設定檔',
  'Disable Shortcut': '停用快速鍵',
  'Close Image Preview': '關閉圖片預覽',
  'Close Terminal': '關閉終端機',
  'Copy Version': '複製版本',
  'Application Menu': '應用程式選單',
  'Refresh Usage': '重新整理用量',
  'Move Toolbar': '移動工具列',
  'Previous Match': '上一個符合項目',
  'Next Match': '下一個符合項目',
  'Close Search': '關閉搜尋',
  'Resource Manager': '資源管理員',
  'The runtime host is not responding. Use the host chip to restart it.':
      'Runtime Host 沒有回應。請使用 Host 狀態按鈕重新啟動。',
  'Total CPU across Alera and every terminal it spawned, as a share of everything this machine can run at once.':
      'Alera 與其啟動之所有終端機的 CPU 總用量，以此機器可同時執行的總容量為基準。',
  'Resident memory of Alera, the runtime host, and every terminal process.':
      'Alera、Runtime Host 與所有終端機程序目前占用的實體記憶體。',
  'Share of the machine memory these processes hold.': '這些程序占用整台機器記憶體的比例。',
  'Memory': '記憶體',
  'Measuring resource usage': '正在測量資源用量',
  'No terminal sessions are running': '目前沒有執行中的終端機工作階段',
  'remote': '遠端',
  'Unattributed Terminals': '未歸屬的終端機',
  'Kill Orphan Terminal': '終止孤立終端機',
  'Close Terminal Session': '關閉終端機工作階段',
  'App': '應用程式',
  'Runtime Host': 'Runtime Host',

  'Pane actions': '窗格操作',
  'Dismiss Error': '關閉錯誤',
  'New Workspace in This Project': '在此專案新增工作區',
  'Expand panel': '展開面板',
  'Collapse panel': '收合面板',
  'View Diff': '檢視 Diff',
  'Discard Changes': '捨棄變更',
  'Open Preview': '開啟預覽',
  'View options': '檢視選項',
  'Refresh Commits': '重新整理 Commits',
  'Copy Commit Hash': '複製 Commit Hash',
  'Copy Commit Subject': '複製 Commit 主旨',
  'Add Tag…': '新增 Tag…',
  'Create Branch Here…': '在此建立 Branch…',
  'Create Worktree Here…': '在此建立 Worktree…',
  'Checkout Commit': 'Checkout 此 Commit',
  'Cherry Pick': 'Cherry-pick',
  'Revert Commit': 'Revert 此 Commit',
  'Drop Commit': '移除 Commit',
  'Merge Into Current Branch': '合併到目前 Branch',
  'Merge into Current Branch': '合併到目前 Branch',
  'Rebase Current Branch Onto This Commit': '將目前 Branch Rebase 到此 Commit',
  'Reset Current Branch Here': '在此重設目前 Branch',
  'Create Archive…': '建立封存檔…',
  'Create Archive...': '建立封存檔...',
  'Current Branch': '目前 Branch',
  'Switch to Branch': '切換到 Branch',
  'Rename Branch...': '重新命名 Branch...',
  'Delete Branch': '刪除 Branch',
  'Open in New Worktree': '在新 Worktree 中開啟',
  'Checkout Remote Branch': 'Checkout 遠端 Branch',
  'Delete Remote Branch': '刪除遠端 Branch',
  'Pull into Current Branch': 'Pull 到目前 Branch',
  'Open in New Worktree...': '在新 Worktree 中開啟...',
  'Push Tag': 'Push Tag',
  'Copy Branch Name': '複製 Branch 名稱',
  'Copy Tag Name': '複製 Tag 名稱',
  'Stash Changes': 'Stash 變更',
  'Discard All Changes': '捨棄所有變更',
  'Commit Changes...': 'Commit 變更...',
  'Previous match': '上一個符合項目',
  'Next match': '下一個符合項目',
  'Zoom out': '縮小',
  'Zoom in': '放大',
  'Hide outline': '隱藏大綱',
  'Replace in file': '在檔案中取代',
  'Replace match': '取代符合項目',
  'Delete Tag': '刪除標籤',
  'Commit Actions': 'Commit 操作',
  'Clear search results': '清除搜尋結果',
  'Move Up': '上移',
  'Move Down': '下移',
  'Remove Workspace': '移除工作區',
  'Open Pull Request Diff': '開啟 Pull Request Diff',
  'Open Comment': '開啟留言',
  'Open Comment Location': '開啟留言位置',
  'Match case': '區分大小寫',
  'Match whole word': '全字符合',
  'Use regular expression': '使用正規表示式',
  'Preserve case': '保留大小寫',
  'Replace all': '全部取代',
  'Open source file': '開啟來源檔',
  'Open Editor': '開啟編輯器',
  'Open Check': '開啟檢查',
  'Pull Request Actions': 'Pull Request 操作',
  'Checks': '檢查',
  'No checks reported': '尚未回報任何檢查結果',
  'Edit Pull Request': '編輯 Pull Request',
  'Open In Browser': '在瀏覽器中開啟',
  'Title': '標題',
  'Base Branch': '基底分支',
  'The base branch is managed by the pull request stack.':
      '基底分支由 Pull Request Stack 管理。',
  'Draft': '草稿',
  'Merged': '已合併',
  'Closed': '已關閉',
  'Comments': '留言',
  'Start Conversation': '開始對話',
  'Add Comment': '新增留言',
  'Add a comment': '新增留言',
  'No comments yet': '目前還沒有留言',
  'Resolved': '已解決',
  'No details available': '沒有可用的詳細資訊',
  'Workflow': '工作流程',
  'Event': '事件',
  'Description': '說明',
  'Started': '開始時間',
  'Completed': '完成時間',
  '#123 or pull request URL': '#123 或 Pull Request URL',
  'Suggested pull request': '建議的 Pull Request',
  'CLI not found': '找不到 CLI',
  'Not authenticated': '尚未驗證身分',
  'No remote': '沒有 Remote',
  'This repository has no remote to detect a provider from.':
      '此 Repository 沒有 Remote，無法據此偵測 Provider。',
  'Provider not detected': '未偵測到 Provider',
  'Could not detect the git hosting provider. Set it in project settings.':
      '無法偵測 Git Hosting Provider，請在專案設定中指定。',
  'Unsupported provider': '不支援的 Provider',
  'This hosting provider is not supported yet.': '目前尚不支援此 Hosting Provider。',

  'Create Options': '建立選項',
  'Automations unavailable': '無法取得自動化',
  'No automations': '沒有自動化',
  'Select an automation': '選擇自動化',
  'State': '狀態',
  'Profile': '設定檔',
  'Tag': '標籤',

  'No automation details available.': '沒有可用的自動化詳細資料。',
  'Create a schedule to run approved work in a runtime-owned target.':
      '建立排程，在執行環境管理的目標上執行已核准工作。',
  'Choose an automation to inspect its schedule, target, and runs.':
      '選擇自動化以檢視排程、目標與執行紀錄。',
  'Linked workspaces require a Git project. Add one to get started.':
      '連結工作區需要 Git 專案；請先新增專案。',
  'Create an action to replace selected text with AI.': '建立動作，使用 AI 取代選取文字。',
  'Choose an action or create a new one.': '選擇既有動作或建立新動作。',
  'This action and its settings will be removed.': '此動作及其設定將被移除。',
  'No usage was found in this range.': '此範圍內沒有用量資料。',
  'No Claude Code, Codex, or Grok Build usage was found in this range.':
      '此範圍內沒有 Claude Code、Codex 或 Grok Build 用量資料。',
  'Default workspace': '預設工作區',
  'Pinned workspace': '已釘選工作區',
  'Workspace path copied': '已複製工作區路徑',
  'Workspace slept': '工作區已休眠',
  'No git remote configured for this workspace.': '此工作區未設定 Git remote。',
  'Could not open the browser.': '無法開啟瀏覽器。',
  'This editor tab has no file.': '此編輯器分頁沒有檔案。',
  'No commits yet': '尚無 Commit',
  'Could not load diff.': '無法載入 Diff。',
  'No diff available.': '沒有可用的 Diff。',
  'No stashes to pop': '沒有可套用的 Stash',

  'Edit Message': '編輯訊息',
  'Message': '訊息',
  'Saving': '儲存中',
  'Save And Restart': '儲存並重新開始',
  'Save Message': '儲存訊息',
  'Saving stops the active turn and replaces this message and all later responses. Files and actions already performed are not undone. Queued messages remain paused.':
      '儲存會停止目前的回合，並取代此訊息及之後的所有回覆。已執行的檔案變更與操作不會復原，佇列中的訊息會維持暫停。',
  'The message could not be saved. Your edit is still here.':
      '無法儲存訊息，你的編輯內容仍保留在這裡。',
  'Queued': '已排入佇列',
  'Paused': '已暫停',
  'Resume Queue': '繼續佇列',
  'Pause Queue': '暫停佇列',
  'Collapse Queue': '收合佇列',
  'Expand Queue': '展開佇列',
  'Check Delivery': '檢查傳送狀態',
  'Attachment': '附件',
  'Sending': '傳送中',
  'Steer': '引導',
  'Remove Queued Message': '移除佇列訊息',
  'Message Actions': '訊息操作',

  'Ship Changes?': '送出變更？',
  'Ship only staged changes, or stage all changes first and include them in the commit.':
      '僅送出已暫存的變更，或先暫存所有變更並將其納入 Commit。',
  'Ship Staged Changes': '送出已暫存變更',
  'Ship All Changes': '送出所有變更',
  'Runtime Still Has Work': '執行環境仍有工作進行中',
  'Quit And Leave Runtime Open': '結束 Alera 並讓執行環境保持運作',
  'Force Stop And Quit': '強制停止並結束 Alera',
  'Force Stop Runtime': '強制停止執行環境',
  'Force Stop': '強制停止',
  'The runtime still has active work.': '執行環境仍有進行中的工作。',
  'The runtime still has active work. Force stop terminates them.':
      '執行環境仍有進行中的工作。強制停止會終止這些工作。',
  'The runtime still has active work. You can quit and leave the runtime running, or force stop it.':
      '執行環境仍有進行中的工作。你可以結束 Alera 並讓執行環境保持運作，或強制停止它。',

  'Active Run': '執行中工作',
  'Update With': '使用以下方式更新',
};
