part of 'alera_localizations.dart';

const Map<String, String> _japaneseShell = <String, String>{
  // Workspace and editor shell.
  'Add Project': 'プロジェクトを追加',
  'New Workspace': '新規ワークスペース',
  'Open Settings': '設定を開く',
  'Quick Start': 'クイックスタート',
  'Keyboard Shortcuts': 'キーボードショートカット',
  'Explorer': 'エクスプローラー',
  'Source Control': 'ソース管理',
  'Pull Request': 'Pull Request',
  'Pull Requests': 'Pull Request',
  'Automations': 'オートメーション',
  'New Terminal': '新規ターミナル',
  'New Tab': '新規タブ',
  'Open in Zed': 'Zed で開く',
  'Open in Alera': 'Alera で開く',
  'Copy path': 'パスをコピー',
  'Copy relative path': '相対パスをコピー',
  'New file': '新規ファイル',
  'New folder': '新規フォルダー',
  'Collapse All': 'すべて折りたたむ',
  'Save all files': 'すべてのファイルを保存',

  'No projects yet': 'プロジェクトがありません',
  'Add a git repository to create workspaces with terminal tabs.':
      'Git リポジトリを追加すると、ターミナルタブ付きのワークスペースを作成できます。',
  'Add Your First Project': '最初のプロジェクトを追加',
  'Unpin Workspace': 'ワークスペースのピン留めを解除',
  'Pin Workspace': 'ワークスペースをピン留め',
  'Pin Workspace Tree': 'ワークスペースツリーをピン留め',
  'Unpin Workspace Tree': 'ワークスペースツリーのピン留めを解除',
  'Manage Tags': 'タグを管理',
  'Set Parent Workspace': '親ワークスペースを設定',
  'Clear Parent Workspace': '親ワークスペースをクリア',
  'Set Section': 'セクションを設定',
  'Clear Section': 'セクションをクリア',
  'Open in Browser': 'ブラウザーで開く',
  'Open in Project Settings': 'プロジェクト設定で開く',
  'Copy Path': 'パスをコピー',
  'Sleep': 'スリープ',
  'Folder name': 'フォルダー名',
  'File name': 'ファイル名',
  'Name': '名前',
  'Path copied': 'パスをコピーしました',
  'Relative path copied': '相対パスをコピーしました',
  'Duplicate': '複製',
  'Show ignored files': '無視されたファイルを表示',
  'Hide ignored files': '無視されたファイルを非表示',
  'Show hidden items': '隠し項目を表示',
  'Hide hidden items': '隠し項目を非表示',
  'Source control root': 'ソース管理のルート',
  'Clear Source Control Root': 'ソース管理のルートをクリア',
  'Use As Source Control Root': 'ソース管理のルートに設定',
  'Collapse folder': 'フォルダーを折りたたむ',
  'Move this item to the trash?': 'この項目をゴミ箱に移動しますか？',
  'Open File': 'ファイルを開く',
  'Reveal in Explorer': 'エクスプローラーで表示',
  'Stage': 'ステージ',
  'Unstage': 'ステージ解除',
  'Discard': '破棄',
  'All Changes': 'すべての変更',
  'Show Flat List': 'フラットリストを表示',
  'Show Tree': 'ツリー表示',
  'Show All Changes': 'すべての変更を表示',
  'Group By Staged State': 'ステージ状態でグループ化',
  'Hide File Filter': 'ファイルフィルターを非表示',
  'Search Files': 'ファイルを検索',
  'Expand All': 'すべて展開',
  'Filter files...': 'ファイルを絞り込み…',
  'Stop generating commit message': 'コミットメッセージの生成を停止',
  'Generate commit message with AI': 'AI でコミットメッセージを生成',
  'Source Control Actions': 'ソース管理の操作',
  'Commit': 'Commit',
  'Commit & Push': 'Commit して Push',
  'Commit & Sync': 'Commit して同期',
  'Commit Amend': '直前の Commit を修正',
  'Stage All': 'すべてステージ',
  'Unstage All': 'すべてステージ解除',
  'Discard All': 'すべて破棄',
  'Open Changes in Zed': '変更を Zed で開く',
  'Fetch': 'Fetch',
  'Pull': 'Pull',
  'Push': 'Push',
  'Sync': '同期',
  'Publish Branch': 'ブランチを公開',
  'Stash': 'Stash',
  'Stash Pop': 'Stash を適用',
  'Sleep Project': 'プロジェクトをスリープ',
  'Sleep Project?': 'プロジェクトをスリープしますか？',
  'Sleep All': 'すべてスリープ',
  'Project workspaces slept': 'プロジェクトのワークスペースをスリープしました',
  'Open with Default Application': '既定のアプリケーションで開く',
  'Refresh Outline': 'アウトラインを再読み込み',
  'Outline': 'アウトライン',
  'No symbols': 'シンボルがありません',
  'Show Outline': 'アウトラインを表示',
  'Diff Overview': 'Diff の概要',
  'All Branches': 'すべてのブランチ',
  'Current Branch': '現在のブランチ',
  'Current': '現在',
  'Search branches': 'ブランチを検索',
  'No matching branches': '一致するブランチがありません',
  'Branch Perspective': 'ブランチビュー',
  'Branch': 'ブランチ',
  'Waiting for input': '入力待ち',
  'Blocked': 'ブロック中',
  'Interrupted': '中断されました',
  'Done (Unread)': '完了（未読）',
  'Show Agent Runs': 'Agent の実行を表示',
  'Hide Agent Runs': 'Agent の実行を非表示',
  'Copy Commit Hash': 'Commit ハッシュをコピー',
  'Copy Commit Subject': 'Commit の件名をコピー',
  'Add Tag…': 'タグを追加…',
  'Create Branch Here…': 'ここにブランチを作成…',
  'Create Worktree Here…': 'ここに Worktree を作成…',
  'Checkout Commit': 'この Commit を Checkout',
  'Cherry Pick': 'Cherry Pick',
  'Revert Commit': 'Commit を取り消す',
  'Drop Commit': 'Commit を削除',
  'Merge Into Current Branch': '現在のブランチにマージ',
  'Rebase Current Branch Onto This Commit': '現在のブランチをこの Commit に Rebase',
  'Reset Current Branch Here': '現在のブランチをここにリセット',
  'Soft': 'Soft',
  'Mixed': 'Mixed',
  'Hard': 'Hard',
  'Create Archive…': 'アーカイブを作成…',
  'Copy Tag Name': 'タグ名をコピー',
  'Copy Branch Name': 'ブランチ名をコピー',
  'Switch to Branch': 'ブランチに切り替え',
  'Rename Branch...': 'ブランチ名を変更…',
  'Delete Branch': 'ブランチを削除',
  'Merge into Current Branch': '現在のブランチにマージ',
  'Create Archive...': 'アーカイブを作成…',
  'Open in New Worktree': '新しい Worktree で開く',
  'Checkout Remote Branch': 'リモートブランチを Checkout',
  'Delete Remote Branch': 'リモートブランチを削除',
  'Pull into Current Branch': '現在のブランチに Pull',
  'Open in New Worktree...': '新しい Worktree で開く…',
  'Push Tag': 'タグを Push',
  'Stash Changes': '変更を Stash',
  'Discard All Changes': 'すべての変更を破棄',
  'Commit Changes...': '変更を Commit…',
  'Create Branch Here': 'ここにブランチを作成',
  'Branch Name': 'ブランチ名',
  'Create Branch': 'ブランチを作成',
  'Create Worktree': 'Worktree を作成',
  'Create Archive': 'アーカイブを作成',
  'Archive Path': 'アーカイブのパス',
  'Add Tag': 'タグを追加',
  'Tag Name': 'タグ名',
  'Message (Optional)': 'メッセージ（任意）',
  'Tag name is required': 'タグ名は必須です。',
  'Drop Commit?': 'この Commit を削除しますか？',
  'Drop': '削除',
  'Merge Commit?': 'この Commit をマージしますか？',
  'Merge': 'マージ',
  'Rebase Current Branch?': '現在のブランチを Rebase しますか？',
  'Rebase': 'Rebase',
  'File saved': 'ファイルを保存しました',
  'Changes discarded': '変更を破棄しました',
  'File overwritten': 'ファイルを上書きしました',
  'Autosave paused because the file changed on disk.':
      'ディスク上でファイルが変更されたため、自動保存を一時停止しました。',
  'File changed on disk': 'ディスク上でファイルが変更されました',
  'Overwrite the file with the editor contents?': 'エディターの内容でファイルを上書きしますか？',
  'Overwrite': '上書き',
  'File cannot be edited': 'このファイルは編集できません',
  'File not found': 'ファイルが見つかりません',
  'File is outside the workspace': 'ファイルがワークスペースの外にあります',
  'File is protected': 'ファイルは保護されています',
  'File operation failed': 'ファイル操作に失敗しました',
  'Item already exists': '項目はすでに存在します',
  'Path is protected': 'パスは保護されています',
  'Path is outside the workspace': 'パスがワークスペースの外にあります',
  'Operation is unsupported': 'この操作はサポートされていません',
  'Item not found': '項目が見つかりません',
  'Quick Open': 'クイックオープン',
  'Search workspace files': 'ワークスペースのファイルを検索',
  'Include Git-ignored files': 'Git で無視されたファイルを含める',
  'Use Up and Down to navigate, Enter to open, or Escape to close.':
      '上下キーで移動、Enter で開く、Escape で閉じます。',
  'Loading workspace files...': 'ワークスペースのファイルを読み込んでいます…',
  'Could not load workspace files.': 'ワークスペースのファイルを読み込めませんでした。',
  'No files are available in this workspace.': 'このワークスペースに利用できるファイルがありません。',
  'No files match': '一致するファイルがありません:',
  'Command Palette': 'コマンドパレット',
  'Search commands': 'コマンドを検索',
  'Use Up and Down to navigate, Enter to run, or Escape to close.':
      '上下キーで移動、Enter で実行、Escape で閉じます。',
  'No commands are available.': '現在利用できるコマンドがありません。',
  'No commands match': '一致するコマンドがありません:',
  'No shortcut': 'ショートカットなし',
  'How shortcuts behave while a terminal is focused.':
      'ターミナルにフォーカスがあるときのショートカットの動作を設定します。',
  'When a Terminal Is Focused': 'ターミナルにフォーカスがあるとき',
  'App first lets Alera capture combinations the shell would otherwise receive. Terminal first defers to the shell.':
      '「アプリ優先」では、本来シェルが受け取るキーの組み合わせを Alera が横取りします。「ターミナル優先」ではシェルを優先します。',
  'Stop Recording': '記録を停止',
  'Change Shortcut': 'ショートカットを変更',
  'Press keys… (Esc to cancel)': 'キーを押してください…（Esc でキャンセル）',
  'Disabled': '無効',
  'Unassigned': '未割り当て',
  'Shortcut already in use': 'このショートカットは使用中です',
  'Reassign': '再割り当て',
  'Enter a shortcut like Ctrl+Shift+P.': 'Ctrl+Shift+P のようなショートカットを入力してください。',
  'A shortcut can only have one main key.': 'ショートカットに指定できるメインキーは 1 つだけです。',
  'Add a main key, like P or Enter.': 'P や Enter などのメインキーを追加してください。',
  'Use either Mod or a platform-specific modifier, not both.':
      'Mod かプラットフォーム固有の修飾キーのどちらか一方を使用してください。',
  'Include at least one modifier key.': '修飾キーを 1 つ以上含めてください。',
  'Press a non-modifier key too.': '修飾キー以外のキーも押してください。',
  'Unsupported key.': 'サポートされていないキーです。',
  'Go to Tab 1': 'タブ 1 に移動',
  'Go to Tab 2': 'タブ 2 に移動',
  'Go to Tab 3': 'タブ 3 に移動',
  'Go to Tab 4': 'タブ 4 に移動',
  'Go to Tab 5': 'タブ 5 に移動',
  'Go to Tab 6': 'タブ 6 に移動',
  'Go to Tab 7': 'タブ 7 に移動',
  'Go to Tab 8': 'タブ 8 に移動',
  'Go to Last Tab': '最後のタブに移動',
  'Open the settings dialog.': '設定ダイアログを開きます。',
  'Open the runtime-local automation manager.': 'このランタイムのオートメーションマネージャーを開きます。',
  'Search and open a file in the active workspace.':
      'アクティブなワークスペース内のファイルを検索して開きます。',
  'Search and run an Alera command.': 'Alera のコマンドを検索して実行します。',
  'Open the add-project dialog.': 'プロジェクト追加ダイアログを開きます。',
  'Collapse or expand the project sidebar.': 'プロジェクトのサイドバーを折りたたむ／展開します。',
  'Create a linked workspace for the active Git project.':
      'アクティブな Git プロジェクトのリンクされたワークスペースを作成します。',
  'Open the active workspace in the configured external editor.':
      'アクティブなワークスペースを、設定した外部エディターで開きます。',
  'Go to the previously selected workspace.': '直前に選択していたワークスペースに移動します。',
  'Go to the next workspace in navigation history.':
      'ナビゲーション履歴の次のワークスペースに移動します。',
  'Open workspace search.': 'ワークスペース検索を開きます。',
  'Search the active terminal scrollback.': 'アクティブなターミナルのスクロールバックを検索します。',
  'Show or hide the prompt composer for the active terminal.':
      'アクティブなターミナルのプロンプト入力欄を表示／非表示にします。',
  'Open workspace search and replace.': 'ワークスペースの検索と置換を開きます。',
  'Save the active editor file.': 'アクティブなエディターのファイルを保存します。',
  'Open a terminal tab in the active workspace.': 'アクティブなワークスペースでターミナルタブを開きます。',
  'Close the active terminal tab.': 'アクティブなターミナルタブを閉じます。',
  'Select the next tab in the active pane.': 'アクティブなペインの次のタブを選択します。',
  'Select the previous tab in the active pane.': 'アクティブなペインの前のタブを選択します。',
  'Select the first tab in the active pane.': 'アクティブなペインの 1 番目のタブを選択します。',
  'Select the second tab in the active pane.': 'アクティブなペインの 2 番目のタブを選択します。',
  'Select the third tab in the active pane.': 'アクティブなペインの 3 番目のタブを選択します。',
  'Select the fourth tab in the active pane.': 'アクティブなペインの 4 番目のタブを選択します。',
  'Select the fifth tab in the active pane.': 'アクティブなペインの 5 番目のタブを選択します。',
  'Select the sixth tab in the active pane.': 'アクティブなペインの 6 番目のタブを選択します。',
  'Select the seventh tab in the active pane.': 'アクティブなペインの 7 番目のタブを選択します。',
  'Select the eighth tab in the active pane.': 'アクティブなペインの 8 番目のタブを選択します。',
  'Select the last tab in the active pane.': 'アクティブなペインの最後のタブを選択します。',
  'Split the active pane to the right with a new terminal.':
      'アクティブなペインを右に分割し、新しいターミナルを開きます。',
  'Split the active pane downward with a new terminal.':
      'アクティブなペインを下に分割し、新しいターミナルを開きます。',
  'Merge the active pane back into its sibling.': 'アクティブなペインを隣のペインに統合します。',
  'Global': 'グローバル',
  'Workspace': 'ワークスペース',
  'Tabs': 'タブ',
  'Panes': 'ペイン',
  'Open Automations': 'オートメーションを開く',
  'Open Workspace in External Editor': 'ワークスペースを外部エディターで開く',
  'Toggle Sidebar': 'サイドバーの表示切り替え',
  'Go Back': '戻る',
  'Go Forward': '進む',
  'Find in Files': 'ファイル内を検索',
  'Find in Terminal': 'ターミナル内を検索',
  'Toggle Terminal Composer': 'ターミナル入力欄の表示切り替え',
  'Replace in Files': 'ファイル内を置換',
  'Save File': 'ファイルを保存',
  'New Terminal Tab': '新規ターミナルタブ',
  'Close Tab': 'タブを閉じる',
  'Next Tab': '次のタブ',
  'Previous Tab': '前のタブ',
  'Split Right': '右に分割',
  'Split Down': '下に分割',
  'Close Split': '分割ペインを閉じる',
  'Select Folder': 'フォルダーを選択',
  'Select Parent Folder': '親フォルダーを選択',
  'Choose Parent Folder': '親フォルダーを選択',
  'Choose an existing local folder or clone a Git repository from a URL.':
      '既存のローカルフォルダーを選択するか、URL から Git リポジトリをクローンします。',
  'Local Folder': 'ローカルフォルダー',
  'Clone From URL': 'URL からクローン',
  'Project Path': 'プロジェクトのパス',
  'Destination Folder': '保存先フォルダー',
  'Auth Method': '認証方式',
  'Authentication': '認証',
  'Key': 'キー',
  'Password': 'パスワード',
  'Platform': 'プラットフォーム',
  'Architecture': 'アーキテクチャ',
  'Parent Workspace': '親ワークスペース',
  'No Parent': '親なし',
  'Section Name': 'セクション名',
  'Terminal Title': 'ターミナルのタイトル',
  'Configuration is stored in your Alera account and can be read by the service. Review custom commands and prompts for embedded secrets. Credentials and device permissions stay local.': '設定は Alera アカウントに保存され、サービス側から読み取られる可能性があります。カスタムコマンドやプロンプトに機密情報が含まれていないか確認してください。認証情報とデバイスの権限はローカルに保持されます。',
  'Review Changes': '変更を確認',
  'History': '履歴',
  'Retry Pending Upload': '保留中のアップロードを再試行',
  'Shared version': '共有バージョン',
  'Comparing': '比較中',
  'differences': '件の差分',
  'unresolved': '件が未解決',
  'Keep All Local': 'すべてローカル版を保持',
  'Keep All Remote': 'すべてリモート版を保持',
  'Both sides changed this value. Choose what to keep.':
      'ローカルとリモートの両方でこの値が変更されています。保持する方を選択してください。',
  'Local': 'ローカル',
  'Remote': 'リモート',
  'Choose A Value': '値を選択',
  'Keep Local': 'ローカル版を保持',
  'Keep Remote': 'リモート版を保持',
  'Action Name': '操作名',
  'Profile Name': 'プロファイル名',
  'Result': '結果',
  'Unresolved': '未解決',
  '(Removed)': '（削除済み）',
  'These changes apply only to': 'これらの変更が適用される範囲:',
  'Apply To Device': 'デバイスに適用',
  'Apply And Upload': '適用してアップロード',
  'Leaving this screen without applying keeps your configuration unchanged. If upload fails after applying, local changes remain pending.':
      '適用せずにこの画面を離れた場合、設定は変更されません。適用後にアップロードが失敗した場合、ローカルの変更は保留のまま残ります。',
  'Version': 'バージョン',
  'Compare': '比較',
  'Shell environment reloaded': 'シェル環境を再読み込みしました',
  'PATH entries': '件の PATH エントリ',
  'Could not reload shell environment': 'シェル環境を再読み込みできませんでした',
  'Could not open link': 'リンクを開けませんでした',
  'No external editor is installed.': '対応する外部エディターがインストールされていません。',
  'Could not open file in the external editor.': '外部エディターでファイルを開けませんでした。',
  'Existing Branch *': '既存のブランチ *',
  'New Branch Name *': '新しいブランチ名 *',
  'Workspace Name (Optional)': 'ワークスペース名（任意）',
  'Search projects': 'プロジェクトを検索',
  'Search Workspaces': 'ワークスペースを検索',
  'Search workspaces': 'ワークスペースを検索',
  'Replace': '置換',
  'Files to include': '含めるファイル',
  'Files to exclude': '除外するファイル',
  'Hide details': '詳細を非表示',
  'Show details': '詳細を表示',
  'Hide replace': '置換欄を非表示',
  'Show replace': '置換欄を表示',
  'Search Terminal': 'ターミナルを検索',
  'Search PDF': 'PDF を検索',
  'Add tag…': 'タグを追加…',
  'Add project…': 'プロジェクトを追加…',
  'Terminal Input': 'ターミナル入力',
  'Display Name (Optional)': '表示名（任意）',
  'Alera will detect whether the folder is a Git repository. Non-Git folders only get a primary workspace.':
      'Alera はフォルダーが Git リポジトリかどうかを判定します。Git 以外のフォルダーにはプライマリワークスペースのみ作成されます。',
  'Alera will run git clone into the destination folder and register the cloned repository.':
      'Alera は保存先フォルダーで git clone を実行し、クローンしたリポジトリを登録します。',
  'Native folder picker is not available; paste path manually.':
      'OS のフォルダー選択ダイアログを利用できません。パスを手動で貼り付けてください。',

  'Edit': '編集',
  'Back': '戻る',
  'Next': '次へ',
  'Done': '完了',
  'Add': '追加',
  'Start': '開始',
  'Stop': '停止',
  'Select': '選択',
  'Confirm': '確認',
  'Update': '更新',
  'Download': 'ダウンロード',
  'Approve': '承認',
  'Reject': '却下',
  'Open Usage': '使用量を開く',
  'Remove Token': 'トークンを削除',
  'Check For Updates': '更新を確認',
  'Resume': '再開',
  'Extend': '延長',
  'Run': '実行',
  'Continue Active': '実行中のものを継続',
  'Cancel Active': '実行中のものをキャンセル',
  'Save Automation': 'オートメーションを保存',
  'Run Now': '今すぐ実行',
  'Restore': '復元',
  'Trash': 'ゴミ箱に移動',
  'New Automation': '新規オートメーション',
  'Post Comment': 'コメントを投稿',
  'Link': 'リンク',
  'Create Stack': 'Stack を作成',
  'Link Existing Pull Request': '既存の Pull Request を関連付け',
  'Create Pull Request': 'Pull Request を作成',
  'Test Command': 'コマンドをテスト',
  'Add CCS Profile': 'CCS プロファイルを追加',
  'Save Profile': 'プロファイルを保存',
  'Check Environment': '環境を確認',
  'Take Back This Terminal': 'このターミナルを取り戻す',
  'Take Back All Terminals': 'すべてのターミナルを取り戻す',
  'Take Back': '取り戻す',
  'Add Git Project': 'Git プロジェクトを追加',
  'Use Custom Command': 'カスタムコマンドを使用',
  'Continue Manually': '手動で続行',
  'Open Workspace': 'ワークスペースを開く',
  'Retry Agent': 'Agent を再試行',
  'Create And Start Agent': 'Agent を作成して開始',
  'Cancel Download': 'ダウンロードをキャンセル',
  'Remove Model': 'モデルを削除',
  'Update Runtime': 'Runtime を更新',
  'Kill All': 'すべて強制終了',
  'A reading diff is an AI-guided, non-applicable abbreviation of the original diff.':
      'リーディング Diff は、AI が要約した、そのままでは適用できない元 Diff の短縮版です。',
  'This overview explains the behavioral changes selected while condensing the diff. It does not identify bugs or security findings. Open Condensed Diff to inspect the retained source changes, or return to the original diff for the complete patch.': 'この概要は、Diff を要約する際に選ばれた挙動の変更点を説明するものです。バグやセキュリティ上の問題を検出するものではありません。残されたソース変更を確認するには「要約 Diff」を開き、完全なパッチを見るには元の Diff に戻ってください。',
  'Cached Result': 'キャッシュされた結果',
  'Preparing reading diff': 'リーディング Diff を準備しています',
  'Loading cached reading diff': 'キャッシュされたリーディング Diff を読み込んでいます',
  'Loading the immutable diff and splitting it at safe boundaries.':
      '変更されない Diff を読み込み、安全な境界で分割しています。',
  'Using a previously generated and validated result.':
      '以前に生成され検証済みの結果を使用しています。',
  'The agent is proposing safe elisions; Rust validates the plan.':
      'Agent が安全な省略案を提示し、Rust がその計画を検証します。',
  'Rust rejected the plan; the agent is replacing it once.':
      'Rust が計画を却下したため、Agent が一度だけ作り直しています。',
  'Rust is merging the validated chunks into the final reading diff.':
      'Rust が検証済みのチャンクを最終的なリーディング Diff に統合しています。',
  'Reading diff generation failed': 'リーディング Diff の生成に失敗しました',
  'This manually runs the configured AI Assist agent and may consume subscription quota or other provider usage. The complete selected patch is provided, including portions hidden by preview truncation.': '設定済みの AI Assist Agent を手動で実行します。サブスクリプションの割り当てやプロバイダーの使用量を消費する場合があります。プレビューで省略された部分も含め、選択したパッチ全体が送信されます。',
  'The result opens with a behavioral overview and a condensed, non-applicable diff. It is not a bug or security review.':
      '結果は挙動の概要と、そのままでは適用できない要約 Diff として表示されます。バグやセキュリティのレビューではありません。',
  'Agent': 'Agent',
  'Model': 'モデル',
  'Effort': '推論の深さ',
  'Access': 'アクセス権',
  'Diff Size': 'Diff のサイズ',
  'Chunks': 'チャンク数',
  'Agent Default': 'Agent の既定値',
  'Repository Read Only': 'Repository を読み取り専用',
  'Diff Only': 'Diff のみ',
  'Could not prepare': '準備できませんでした',
  'condensed diff': '要約 Diff',

  'Generate Reading Diff': 'リーディング Diff を生成',
  'Install Update': '更新をインストール',
  'Restart Alera': 'Alera を再起動',
  'Run Update': '更新を実行',
  'View Output': '出力を表示',
  'New Action': '新規操作',
  'Cancel Offer': '招待をキャンセル',
  'Add Copy Rule': 'コピールールを追加',
  'Add Setup Command': 'セットアップコマンドを追加',
  'Use Repo File': 'リポジトリのファイルを使用',
  'Plan': 'プラン',
  'Bootstrap': 'ブートストラップ',
  'Copy Output': '出力をコピー',
  'Restart Terminal': 'ターミナルを再起動',
  'Reconnect': '再接続',
  'Amend': 'Commit を修正',

  'Run Precheck': '事前チェックを実行',
  'Audited Draft Test': '監査付きドラフトテスト',
  'Approve Exact Revision': '指定リビジョンを承認',
  'Skip': 'スキップ',
  'Queue': 'キューに追加',
  'Run Latest Once': '最新版を 1 回実行',
  'Force Parallel': '並列実行を強制',
  'Pause Automation': 'オートメーションを一時停止',
  'Choose what to do with active runs.': '実行中のジョブの扱いを選択してください。',
  'Loading automation policy...': 'オートメーションポリシーを読み込んでいます…',
  'Automation Policy Unavailable': 'オートメーションポリシーを取得できません',
  'Automation Permissions': 'オートメーションの権限',
  'Choose whether this profile may administer active definitions and whether it may execute them.':
      'このプロファイルが有効な定義を管理できるか、また実行できるかを選択します。',
  'May Activate Or Edit Active Automations': '有効なオートメーションの有効化・編集を許可',
  'Allow a managed agent using this profile to activate or edit an active definition.':
      'このプロファイルを使う管理対象 Agent に、有効な定義の有効化と編集を許可します。',
  'May Execute Automations': 'オートメーションの実行を許可',
  'Opt this profile into scheduled and manual automation execution.':
      'このプロファイルでスケジュール実行と手動実行を許可します。',
  'Project Automation Policy Unavailable': 'プロジェクトのオートメーションポリシーを取得できません',
  'Automation Policy': 'オートメーションポリシー',
  'Repository declaration is read from alera.toml. Local approval can only restrict execution.':
      'Repository の宣言は alera.toml から読み込まれます。ローカルの承認は実行をさらに制限することしかできません。',
  'Repository Declares Automations': 'Repository がオートメーションを宣言',
  'The repository declares automation use in alera.toml.':
      'このリポジトリは alera.toml でオートメーションの使用を宣言しています。',
  'Add an automation declaration to alera.toml before execution.':
      '実行する前に alera.toml へオートメーションの宣言を追加してください。',
  'Require Local Approval': 'ローカルの承認を必須にする',
  'Require an explicit human approval in addition to the repository declaration.':
      'Repository の宣言に加えて、人による明示的な承認を必須にします。',
  'Local Approval Granted': 'ローカルの承認済み',
  'Grant the local approval required by a restrictive project policy.':
      '制限の厳しいプロジェクトポリシーが求めるローカルの承認を与えます。',
  'Loading Automation Settings': 'オートメーション設定を読み込んでいます',
  'Reading runtime automation settings.': 'ランタイムのオートメーション設定を読み取っています。',
  'Automation Settings Unavailable': 'オートメーション設定を取得できません',
  'Automation History And Autostart': 'オートメーションの履歴と自動起動',
  'Keep scheduled work available without a window and control local retention.':
      'ウィンドウがなくてもスケジュールされた処理を実行できるようにし、ローカルの保持期間を制御します。',
  'Start Automations At Login': 'ログイン時にオートメーションを開始',
  'Start the persistent local automation host when you sign in. This is off by default.':
      'サインイン時に常駐のローカルオートメーションホストを開始します。既定ではオフです。',
  'Run History Retention': '実行履歴の保持期間',
  'Keep final runs for at most this many days.': '完了した実行記録を最大でこの日数だけ保持します。',
  'Audit Retention': '監査ログの保持期間',
  'Keep automation audit events for at most this many days.':
      'オートメーションの監査イベントを最大でこの日数だけ保持します。',
  'Trash Retention': 'ゴミ箱の保持期間',
  'Permanently remove trashed definitions after this many days.':
      'ゴミ箱内の定義をこの日数の経過後に完全に削除します。',
  'days': '日',

  'Notify On Success': '成功時に通知',
  'Prompt Preview': 'プロンプトのプレビュー',
  'Automation unavailable': 'オートメーションを取得できません',
  'Pause': '一時停止',
  'Runs': '実行記録',
  'Audit': '監査',
  'Slug': 'Slug',
  'Schedule': 'スケジュール',
  'Cron / time': 'Cron / 時刻',
  'Target': 'ターゲット',
  'Policies': 'ポリシー',
  'Limits': '上限',
  'Tags': 'タグ',
  'Revision': 'リビジョン',
  'Prompt': 'プロンプト',
  'Effective Policy': '有効なポリシー',
  'Signature Timeline': '署名のタイムライン',
  'Overlap': '重複時の動作',

  'No active run or upcoming occurrence.': '実行中のジョブも予定されている実行もありません。',
  'Scheduled occurrence': 'スケジュールされた実行',
  'No runs yet.': '実行記録はまだありません。',
  'No audit events yet.': '監査イベントはまだありません。',
  'Import Automations': 'オートメーションをインポート',
  'Edit Automation': 'オートメーションを編集',
  'Project (Optional)': 'プロジェクト（任意）',
  'Tag Ids (Comma-separated)': 'タグ ID（カンマ区切り）',
  'Prompt Template': 'プロンプトテンプレート',
  'Five-field Cron': '5 フィールドの Cron',
  'Run At (UTC)': '実行時刻（UTC）',
  'IANA Timezone': 'IANA タイムゾーン',
  'Start At (Optional ISO-8601 UTC)': '開始日時（任意、ISO-8601 UTC）',
  'End At (Optional ISO-8601 UTC)': '終了日時（任意、ISO-8601 UTC）',
  'Maximum Scheduled Runs (Optional)': 'スケジュール実行の最大回数（任意）',
  'Source Workspace': 'ソースワークスペース',
  'Tab': 'タブ',
  'Agent Conversation ID': 'Agent の会話 ID',
  'Agent Profile': 'Agent プロファイル',
  'Source Branch': 'ソース Branch',
  'Workspace Name Template': 'ワークスペース名のテンプレート',
  'Precheck Command (Optional)': '事前チェックコマンド（任意）',
  'Precheck Timeout (Seconds)': '事前チェックのタイムアウト（秒）',
  'Setup': 'セットアップ',
  'Misfire': '実行漏れ時の動作',
  'Cleanup': 'クリーンアップ',
  'Queue Cap (Maximum 10)': 'キューの上限（最大 10）',
  'Inactivity Timeout (Seconds)': '無操作タイムアウト（秒）',
  'Heartbeat Interval (Seconds)': 'Heartbeat の間隔（秒）',
  'Retry Attempts (Maximum 3)': '再試行回数（最大 3）',
  'Retry Backoff (Seconds)': '再試行のバックオフ（秒）',
  'Circuit Failure Threshold': 'Circuit の失敗しきい値',
  'Circuit Open (Seconds)': 'Circuit を開いておく時間（秒）',
  'Select...': '選択してください…',
  'One-time': '1 回のみ',
  'Existing Tab': '既存のタブ',
  'Fresh Tab': '新しいタブ',
  'Managed Workspace': '管理対象ワークスペース',
  'Name, slug, and prompt template are required.': '名前、slug、プロンプトテンプレートは必須です。',
  'The existing tab requires workspace, tab, and conversation ids.':
      '既存のタブには workspace、tab、conversation の ID が必要です。',
  'The selected target requires its ids.': '選択したターゲットには対応する ID が必要です。',
  'Prompt template contains an unmatched closing delimiter.':
      'プロンプトテンプレートに対応しない閉じ区切り文字があります。',
  'Prompt template contains an unterminated variable.':
      'プロンプトテンプレートに閉じられていない変数があります。',
  'Versioned JSON Catalog': 'バージョン管理された JSON カタログ',
  'Source Key To Local Id JSON': 'ソースキーとローカル ID の対応 JSON',
  'Map every source key to an existing local id.':
      'すべてのソースキーを既存のローカル ID に対応付けてください。',
  'Automation created': 'オートメーションを作成しました',
  'Automation saved': 'オートメーションを保存しました',
  'Automation cloned': 'オートメーションを複製しました',
  'Automation catalog copied to clipboard': 'オートメーションカタログをクリップボードにコピーしました',
  'Automation catalog imported as drafts': 'オートメーションカタログをドラフトとしてインポートしました',
  'Automation approved': 'オートメーションを承認しました',
  'Automation run started': 'オートメーションの実行を開始しました',
  'Automation paused': 'オートメーションを一時停止しました',
  'Automation resumed': 'オートメーションを再開しました',
  'Automation cancellation requested': 'オートメーションのキャンセルを要求しました',
  'Waiting run resumed': '待機中の実行を再開しました',
  'Waiting run extended': '待機中の実行を延長しました',
};
