// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../git.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<String>> listBranches({required String path}) =>
    RustLib.instance.api.crateApiGitGitBranchListBranches(path: path);

Future<String> currentBranch({required String path}) =>
    RustLib.instance.api.crateApiGitGitBranchCurrentBranch(path: path);

Future<void> createAndCheckoutBranch({
  required String path,
  required String branch,
}) => RustLib.instance.api.crateApiGitGitBranchCreateAndCheckoutBranch(
  path: path,
  branch: branch,
);

Future<void> checkoutBranch({required String path, required String branch}) =>
    RustLib.instance.api.crateApiGitGitBranchCheckoutBranch(
      path: path,
      branch: branch,
    );

Future<bool> branchExists({required String repoPath, required String branch}) =>
    RustLib.instance.api.crateApiGitGitBranchBranchExists(
      repoPath: repoPath,
      branch: branch,
    );

Future<bool> isValidBranchName({required String name}) =>
    RustLib.instance.api.crateApiGitGitBranchIsValidBranchName(name: name);

Future<void> refreshSourceBranch({
  required String repoPath,
  required String sourceBranch,
}) => RustLib.instance.api.crateApiGitGitBranchRefreshSourceBranch(
  repoPath: repoPath,
  sourceBranch: sourceBranch,
);

Future<void> createBranchAtCommit({
  required String path,
  required String commitId,
  required String branch,
  required bool checkout,
}) => RustLib.instance.api.crateApiGitGitBranchCreateBranchAtCommit(
  path: path,
  commitId: commitId,
  branch: branch,
  checkout: checkout,
);

Future<String> checkoutRemoteBranch({
  required String path,
  required String remoteBranch,
}) => RustLib.instance.api.crateApiGitGitBranchCheckoutRemoteBranch(
  path: path,
  remoteBranch: remoteBranch,
);

Future<void> renameBranch({
  required String path,
  required String oldName,
  required String newName,
}) => RustLib.instance.api.crateApiGitGitBranchRenameBranch(
  path: path,
  oldName: oldName,
  newName: newName,
);
