// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../git.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> createTag({
  required String path,
  required String commitId,
  required String name,
  String? message,
}) => RustLib.instance.api.crateApiGitGitTagOpsCreateTag(
  path: path,
  commitId: commitId,
  name: name,
  message: message,
);

Future<void> deleteTag({required String path, required String name}) =>
    RustLib.instance.api.crateApiGitGitTagOpsDeleteTag(path: path, name: name);
