// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../git.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

Future<void> gitCheckoutCommit({
  required String path,
  required String commitId,
}) => RustLib.instance.api.crateApiGitGitCommitOpsGitCheckoutCommit(
  path: path,
  commitId: commitId,
);

Future<String> gitRevertCommit({
  required String path,
  required String commitId,
  int? mainlineParent,
}) => RustLib.instance.api.crateApiGitGitCommitOpsGitRevertCommit(
  path: path,
  commitId: commitId,
  mainlineParent: mainlineParent,
);

Future<void> gitResetToCommit({
  required String path,
  required String commitId,
  required GitResetMode mode,
}) => RustLib.instance.api.crateApiGitGitCommitOpsGitResetToCommit(
  path: path,
  commitId: commitId,
  mode: mode,
);

Future<String> gitCherryPickCommit({
  required String path,
  required String commitId,
  int? mainlineParent,
}) => RustLib.instance.api.crateApiGitGitCommitOpsGitCherryPickCommit(
  path: path,
  commitId: commitId,
  mainlineParent: mainlineParent,
);

Future<void> gitDropCommit({required String path, required String commitId}) =>
    RustLib.instance.api.crateApiGitGitCommitOpsGitDropCommit(
      path: path,
      commitId: commitId,
    );

Future<void> gitRebaseOnto({required String path, required String ontoRef}) =>
    RustLib.instance.api.crateApiGitGitCommitOpsGitRebaseOnto(
      path: path,
      ontoRef: ontoRef,
    );

enum GitResetMode { soft, mixed, hard }
