// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../git.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> pushTag({
  required String path,
  required String name,
  String? remote,
}) => RustLib.instance.api.crateApiGitGitRemoteOpsPushTag(
  path: path,
  name: name,
  remote: remote,
);

Future<void> deleteRemoteBranch({
  required String path,
  required String remote,
  required String branch,
}) => RustLib.instance.api.crateApiGitGitRemoteOpsDeleteRemoteBranch(
  path: path,
  remote: remote,
  branch: branch,
);
