// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `base64_url_no_padding`, `comparable_components`, `components_equal`, `copy_entity_preserving_links`, `create_preserved_symlink`, `create_resource_link`, `ensure_strict_descendant`, `entity_exists`, `mirror_entry`, `mirror_path`, `mirror_source_directory`, `normalize_absolute`, `overlay_pair`, `prepare_agent_runtime_overlay_with_linker`, `push_warning`, `read_directory_entries`, `remove_entity_if_exists`, `remove_file_or_link`, `remove_tree_counted`, `safe_remove_overlay`, `set_executable`, `unique_temp_path`, `write_copied_resource_marker`, `write_managed_file`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<AgentRuntimeOverlayResult> prepareAgentRuntimeOverlay({
  required AgentRuntimeOverlayRequest request,
}) => RustLib.instance.api
    .crateApiAgentRuntimeOverlayPrepareAgentRuntimeOverlay(request: request);

Future<AgentRuntimeOverlayCleanupResult> clearAgentRuntimeOverlays({
  required List<AgentRuntimeOverlayCleanupTarget> targets,
}) => RustLib.instance.api.crateApiAgentRuntimeOverlayClearAgentRuntimeOverlays(
  targets: targets,
);

class AgentRuntimeOverlayCleanupResult {
  final BigInt removedCount;
  final List<String> warnings;

  const AgentRuntimeOverlayCleanupResult({
    required this.removedCount,
    required this.warnings,
  });

  static Future<AgentRuntimeOverlayCleanupResult> default_() => RustLib
      .instance
      .api
      .crateApiAgentRuntimeOverlayAgentRuntimeOverlayCleanupResultDefault();

  @override
  int get hashCode => removedCount.hashCode ^ warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentRuntimeOverlayCleanupResult &&
          runtimeType == other.runtimeType &&
          removedCount == other.removedCount &&
          warnings == other.warnings;
}

class AgentRuntimeOverlayCleanupTarget {
  final String overlayRoot;
  final String overlayPath;

  const AgentRuntimeOverlayCleanupTarget({
    required this.overlayRoot,
    required this.overlayPath,
  });

  @override
  int get hashCode => overlayRoot.hashCode ^ overlayPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentRuntimeOverlayCleanupTarget &&
          runtimeType == other.runtimeType &&
          overlayRoot == other.overlayRoot &&
          overlayPath == other.overlayPath;
}

class AgentRuntimeOverlayManagedFile {
  final String path;
  final String allowedRoot;
  final String content;
  final AgentRuntimeOverlayWriteMode writeMode;
  final bool executable;

  const AgentRuntimeOverlayManagedFile({
    required this.path,
    required this.allowedRoot,
    required this.content,
    required this.writeMode,
    required this.executable,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      allowedRoot.hashCode ^
      content.hashCode ^
      writeMode.hashCode ^
      executable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentRuntimeOverlayManagedFile &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          allowedRoot == other.allowedRoot &&
          content == other.content &&
          writeMode == other.writeMode &&
          executable == other.executable;
}

class AgentRuntimeOverlayRequest {
  final String? overlayRoot;
  final String? overlayPath;
  final String? mirrorPath;
  final String? sourcePath;
  final String? managedSubdirectory;
  final List<String> managedFileNames;
  final List<AgentRuntimeOverlayManagedFile> managedFiles;

  const AgentRuntimeOverlayRequest({
    this.overlayRoot,
    this.overlayPath,
    this.mirrorPath,
    this.sourcePath,
    this.managedSubdirectory,
    required this.managedFileNames,
    required this.managedFiles,
  });

  @override
  int get hashCode =>
      overlayRoot.hashCode ^
      overlayPath.hashCode ^
      mirrorPath.hashCode ^
      sourcePath.hashCode ^
      managedSubdirectory.hashCode ^
      managedFileNames.hashCode ^
      managedFiles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentRuntimeOverlayRequest &&
          runtimeType == other.runtimeType &&
          overlayRoot == other.overlayRoot &&
          overlayPath == other.overlayPath &&
          mirrorPath == other.mirrorPath &&
          sourcePath == other.sourcePath &&
          managedSubdirectory == other.managedSubdirectory &&
          managedFileNames == other.managedFileNames &&
          managedFiles == other.managedFiles;
}

class AgentRuntimeOverlayResult {
  final bool sourceExists;
  final BigInt linkedCount;
  final BigInt copiedCount;
  final BigInt writtenCount;
  final BigInt removedCount;
  final List<String> warnings;

  const AgentRuntimeOverlayResult({
    required this.sourceExists,
    required this.linkedCount,
    required this.copiedCount,
    required this.writtenCount,
    required this.removedCount,
    required this.warnings,
  });

  static Future<AgentRuntimeOverlayResult> default_() => RustLib.instance.api
      .crateApiAgentRuntimeOverlayAgentRuntimeOverlayResultDefault();

  @override
  int get hashCode =>
      sourceExists.hashCode ^
      linkedCount.hashCode ^
      copiedCount.hashCode ^
      writtenCount.hashCode ^
      removedCount.hashCode ^
      warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentRuntimeOverlayResult &&
          runtimeType == other.runtimeType &&
          sourceExists == other.sourceExists &&
          linkedCount == other.linkedCount &&
          copiedCount == other.copiedCount &&
          writtenCount == other.writtenCount &&
          removedCount == other.removedCount &&
          warnings == other.warnings;
}

enum AgentRuntimeOverlayWriteMode { replace, createIfMissing }
