// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `batch_loop`, `coalesce_pending`, `flush_events`, `globals`, `handle_hook_request`, `handle_hook`, `is_http_hook_strategy`, `is_session_close_event`, `normalized_enabled_agents`, `optional_string`, `parse_hook_event`, `payload_value`, `required_string`, `runtime`, `valid_token`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AppState`, `Globals`, `ServerHandle`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

Future<AgentHookEndpointDto> startAgentHookReceiver({
  required String token,
  required List<String> enabledAgents,
}) => RustLib.instance.api.crateApiAgentHooksStartAgentHookReceiver(
  token: token,
  enabledAgents: enabledAgents,
);

Future<void> stopAgentHookReceiver() =>
    RustLib.instance.api.crateApiAgentHooksStopAgentHookReceiver();

Future<void> setAgentHookEnabledAgents({required List<String> enabledAgents}) =>
    RustLib.instance.api.crateApiAgentHooksSetAgentHookEnabledAgents(
      enabledAgents: enabledAgents,
    );

Stream<AgentHookEventBatchDto> watchAgentHookEventBatches() =>
    RustLib.instance.api.crateApiAgentHooksWatchAgentHookEventBatches();

class AgentHookEndpointDto {
  final int port;

  const AgentHookEndpointDto({required this.port});

  @override
  int get hashCode => port.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentHookEndpointDto &&
          runtimeType == other.runtimeType &&
          port == other.port;
}

class AgentHookEventBatchDto {
  final List<AgentHookEventDto> events;
  final int coalescedIntermediateCount;

  const AgentHookEventBatchDto({
    required this.events,
    required this.coalescedIntermediateCount,
  });

  @override
  int get hashCode => events.hashCode ^ coalescedIntermediateCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentHookEventBatchDto &&
          runtimeType == other.runtimeType &&
          events == other.events &&
          coalescedIntermediateCount == other.coalescedIntermediateCount;
}

class AgentHookEventDto {
  final String terminalSessionId;
  final String workspaceId;
  final String tabId;
  final String agentType;
  final String payloadJson;
  final String? hookEventName;
  final String? version;
  final String? inferredEventName;

  const AgentHookEventDto({
    required this.terminalSessionId,
    required this.workspaceId,
    required this.tabId,
    required this.agentType,
    required this.payloadJson,
    this.hookEventName,
    this.version,
    this.inferredEventName,
  });

  @override
  int get hashCode =>
      terminalSessionId.hashCode ^
      workspaceId.hashCode ^
      tabId.hashCode ^
      agentType.hashCode ^
      payloadJson.hashCode ^
      hookEventName.hashCode ^
      version.hashCode ^
      inferredEventName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentHookEventDto &&
          runtimeType == other.runtimeType &&
          terminalSessionId == other.terminalSessionId &&
          workspaceId == other.workspaceId &&
          tabId == other.tabId &&
          agentType == other.agentType &&
          payloadJson == other.payloadJson &&
          hookEventName == other.hookEventName &&
          version == other.version &&
          inferredEventName == other.inferredEventName;
}
