// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `collect_records`, `copy_runtime_resource_path`, `fingerprint_runtime_resource`, `hash_serialized_records`, `json_string`, `legacy_modified_micros`, `path_string`, `serialize_record`, `serialize_records`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FingerprintStyle`, `ResourceRecord`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

Future<String> fingerprintClaudeRuntimeResource({required String sourcePath}) =>
    RustLib.instance.api
        .crateApiAgentRuntimeResourcesFingerprintClaudeRuntimeResource(
          sourcePath: sourcePath,
        );

Future<String> fingerprintCodexRuntimeResource({required String sourcePath}) =>
    RustLib.instance.api
        .crateApiAgentRuntimeResourcesFingerprintCodexRuntimeResource(
          sourcePath: sourcePath,
        );

Future<void> copyRuntimeResource({
  required String sourcePath,
  required String targetPath,
}) => RustLib.instance.api.crateApiAgentRuntimeResourcesCopyRuntimeResource(
  sourcePath: sourcePath,
  targetPath: targetPath,
);
