// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `agent_descriptor_dto`

List<AgentDescriptorDto> agentDescriptors() =>
    RustLib.instance.api.crateApiAgentDescriptorsAgentDescriptors();

String? canonicalAgentId({required String id}) =>
    RustLib.instance.api.crateApiAgentDescriptorsCanonicalAgentId(id: id);

ManagedAgentLaunchDto previewManagedAgentLaunch({
  required String agentType,
  required String configJson,
}) => RustLib.instance.api.crateApiAgentDescriptorsPreviewManagedAgentLaunch(
  agentType: agentType,
  configJson: configJson,
);

class AgentDescriptorDto {
  final String id;
  final List<String> aliases;
  final String displayName;
  final String defaultCommand;
  final bool forceSubmit;
  final Uint8List interruptBytes;
  final String startupPrompt;
  final String? startupPromptFlag;
  final String hookStrategy;
  final String statusStrategy;
  final String? quotaProviderId;
  final bool transcriptUsage;
  final String modelOverride;
  final bool supportsPersona;
  final bool supportsCcsProfile;
  final String riskWarning;
  final String? riskWarningSevere;
  final List<AgentRiskRuleDto> riskRules;

  const AgentDescriptorDto({
    required this.id,
    required this.aliases,
    required this.displayName,
    required this.defaultCommand,
    required this.forceSubmit,
    required this.interruptBytes,
    required this.startupPrompt,
    this.startupPromptFlag,
    required this.hookStrategy,
    required this.statusStrategy,
    this.quotaProviderId,
    required this.transcriptUsage,
    required this.modelOverride,
    required this.supportsPersona,
    required this.supportsCcsProfile,
    required this.riskWarning,
    this.riskWarningSevere,
    required this.riskRules,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      aliases.hashCode ^
      displayName.hashCode ^
      defaultCommand.hashCode ^
      forceSubmit.hashCode ^
      interruptBytes.hashCode ^
      startupPrompt.hashCode ^
      startupPromptFlag.hashCode ^
      hookStrategy.hashCode ^
      statusStrategy.hashCode ^
      quotaProviderId.hashCode ^
      transcriptUsage.hashCode ^
      modelOverride.hashCode ^
      supportsPersona.hashCode ^
      supportsCcsProfile.hashCode ^
      riskWarning.hashCode ^
      riskWarningSevere.hashCode ^
      riskRules.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentDescriptorDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          aliases == other.aliases &&
          displayName == other.displayName &&
          defaultCommand == other.defaultCommand &&
          forceSubmit == other.forceSubmit &&
          interruptBytes == other.interruptBytes &&
          startupPrompt == other.startupPrompt &&
          startupPromptFlag == other.startupPromptFlag &&
          hookStrategy == other.hookStrategy &&
          statusStrategy == other.statusStrategy &&
          quotaProviderId == other.quotaProviderId &&
          transcriptUsage == other.transcriptUsage &&
          modelOverride == other.modelOverride &&
          supportsPersona == other.supportsPersona &&
          supportsCcsProfile == other.supportsCcsProfile &&
          riskWarning == other.riskWarning &&
          riskWarningSevere == other.riskWarningSevere &&
          riskRules == other.riskRules;
}

class AgentRiskRuleDto {
  final String key;
  final bool? expectedBool;
  final String? expectedStr;
  final String marker;
  final int score;

  const AgentRiskRuleDto({
    required this.key,
    this.expectedBool,
    this.expectedStr,
    required this.marker,
    required this.score,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      expectedBool.hashCode ^
      expectedStr.hashCode ^
      marker.hashCode ^
      score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentRiskRuleDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          expectedBool == other.expectedBool &&
          expectedStr == other.expectedStr &&
          marker == other.marker &&
          score == other.score;
}

class ManagedAgentLaunchDto {
  final String executable;
  final List<String> arguments;

  const ManagedAgentLaunchDto({
    required this.executable,
    required this.arguments,
  });

  @override
  int get hashCode => executable.hashCode ^ arguments.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ManagedAgentLaunchDto &&
          runtimeType == other.runtimeType &&
          executable == other.executable &&
          arguments == other.arguments;
}
