// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `add_log_directory`, `write_diagnostics_bundle_impl`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DiagnosticsArchiveError`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `from`, `from`

Future<void> writeDiagnosticsBundle({
  required String outputPath,
  required String metadataJson,
  String? appLogDirectory,
  String? runtimeLogDirectory,
}) => RustLib.instance.api.crateApiDiagnosticsWriteDiagnosticsBundle(
  outputPath: outputPath,
  metadataJson: metadataJson,
  appLogDirectory: appLogDirectory,
  runtimeLogDirectory: runtimeLogDirectory,
);
