// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `delete_workspace_relative_path`, `discard_status_entries`, `entries_for_area_and_scope`, `from_git2`, `from_io`, `git_cli_in_path`, `git_signature`, `is_parent_discardable`, `is_submodule_worktree_only`, `new`, `open_repo`, `pathspec_string`, `reject_out_of_scope_staged_entries`, `reject_out_of_scope_stash_pop`, `reject_out_of_scope_tracked_changes`, `reject_tree_diff_out_of_scope`, `relative_path`, `remove_index_path_if_present`, `repo_path_is_in_scope`, `repo_relative_path_from_workspace`, `repo_relative_path`, `repo_workdir_path_exists`, `scoped_pathspecs`, `split_clone_destination`, `stage_selected_path`, `stage_status_entries`, `stash_oid`, `unstage_selected_path`, `unstage_status_entries`, `workspace_path_is_in_scope`, `workspace_repo_relative_path`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

Future<bool> isGitRepository({required String path}) =>
    RustLib.instance.api.crateApiGitIsGitRepository(path: path);

Future<bool> isAncestor({
  required String path,
  required String ancestorRef,
  required String descendantRef,
}) => RustLib.instance.api.crateApiGitIsAncestor(
  path: path,
  ancestorRef: ancestorRef,
  descendantRef: descendantRef,
);

Future<GitStatusResult> gitStatus({required String path}) =>
    RustLib.instance.api.crateApiGitGitStatus(path: path);

Future<GitStatusResult> gitStatusForPath({
  required String path,
  required String filePath,
}) => RustLib.instance.api.crateApiGitGitStatusForPath(
  path: path,
  filePath: filePath,
);

Future<GitStatusResult> gitSubmoduleStatus({
  required String path,
  required String submodulePath,
  required GitChangeArea area,
}) => RustLib.instance.api.crateApiGitGitSubmoduleStatus(
  path: path,
  submodulePath: submodulePath,
  area: area,
);

Future<GitDiffResult> gitDiff({
  required String path,
  required String filePath,
  required GitChangeArea area,
}) => RustLib.instance.api.crateApiGitGitDiff(
  path: path,
  filePath: filePath,
  area: area,
);

Future<GitDiffResult> gitDiffAll({required String path, String? filePath}) =>
    RustLib.instance.api.crateApiGitGitDiffAll(path: path, filePath: filePath);

Future<GitDiffPage> gitDiffAllPage({
  required String path,
  required List<String> filePaths,
}) => RustLib.instance.api.crateApiGitGitDiffAllPage(
  path: path,
  filePaths: filePaths,
);

Future<GitHistoryResult> gitHistory({
  required String path,
  int? limit,
  String? baseRef,
  bool? includeAllRefs,
  int? offset,
}) => RustLib.instance.api.crateApiGitGitHistory(
  path: path,
  limit: limit,
  baseRef: baseRef,
  includeAllRefs: includeAllRefs,
  offset: offset,
);

Future<GitCommitCompareResult> gitCommitCompare({
  required String path,
  required String commitId,
}) => RustLib.instance.api.crateApiGitGitCommitCompare(
  path: path,
  commitId: commitId,
);

Future<GitCommitCompareResult> gitCompareRange({
  required String path,
  required String baseRef,
  required String headRef,
}) => RustLib.instance.api.crateApiGitGitCompareRange(
  path: path,
  baseRef: baseRef,
  headRef: headRef,
);

Future<GitDiffResult> gitCommitDiff({
  required String path,
  required String commitOid,
  String? parentOid,
  String? filePath,
  String? oldPath,
}) => RustLib.instance.api.crateApiGitGitCommitDiff(
  path: path,
  commitOid: commitOid,
  parentOid: parentOid,
  filePath: filePath,
  oldPath: oldPath,
);

/// Summarizes commits and the tree-to-tree patch from merge-base([base_ref],
/// [head_ref]) to [head_ref]. HEAD is used when no explicit head is provided.
Future<GitRangeContext> gitRangeContext({
  required String path,
  required String baseRef,
  int? commitLimit,
  String? headRef,
}) => RustLib.instance.api.crateApiGitGitRangeContext(
  path: path,
  baseRef: baseRef,
  commitLimit: commitLimit,
  headRef: headRef,
);

Future<GitRepositoryState> gitRepositoryState({required String path}) =>
    RustLib.instance.api.crateApiGitGitRepositoryState(path: path);

Future<void> gitStage({required String path, String? filePath}) =>
    RustLib.instance.api.crateApiGitGitStage(path: path, filePath: filePath);

Future<void> gitStageArea({
  required String path,
  required GitChangeArea area,
  String? filePath,
}) => RustLib.instance.api.crateApiGitGitStageArea(
  path: path,
  area: area,
  filePath: filePath,
);

Future<void> gitUnstage({required String path, String? filePath}) =>
    RustLib.instance.api.crateApiGitGitUnstage(path: path, filePath: filePath);

Future<void> gitUnstageArea({
  required String path,
  required GitChangeArea area,
  String? filePath,
}) => RustLib.instance.api.crateApiGitGitUnstageArea(
  path: path,
  area: area,
  filePath: filePath,
);

Future<void> gitDiscard({required String path, String? filePath}) =>
    RustLib.instance.api.crateApiGitGitDiscard(path: path, filePath: filePath);

Future<void> gitDiscardArea({
  required String path,
  required GitChangeArea area,
  String? filePath,
}) => RustLib.instance.api.crateApiGitGitDiscardArea(
  path: path,
  area: area,
  filePath: filePath,
);

Future<String> gitCommit({required String path, required String message}) =>
    RustLib.instance.api.crateApiGitGitCommit(path: path, message: message);

Future<String> gitCommitAmend({
  required String path,
  required String message,
}) => RustLib.instance.api.crateApiGitGitCommitAmend(
  path: path,
  message: message,
);

Future<void> gitFetch({required String path}) =>
    RustLib.instance.api.crateApiGitGitFetch(path: path);

Future<void> gitPull({required String path}) =>
    RustLib.instance.api.crateApiGitGitPull(path: path);

Future<void> gitPush({required String path}) =>
    RustLib.instance.api.crateApiGitGitPush(path: path);

Future<List<GitStashEntry>> gitListStashes({required String path}) =>
    RustLib.instance.api.crateApiGitGitListStashes(path: path);

Future<void> gitStash({required String path}) =>
    RustLib.instance.api.crateApiGitGitStash(path: path);

Future<void> gitStashPop({required String path, required int stashIndex}) =>
    RustLib.instance.api.crateApiGitGitStashPop(
      path: path,
      stashIndex: stashIndex,
    );

/// Adds a linked worktree at `path` for `target_branch`. By default this creates
/// `target_branch` from `source_branch`; when `reuse_existing_branch` is true,
/// `target_branch` must already exist locally.
Future<void> createWorktree({
  required String repoPath,
  required String targetBranch,
  required String path,
  required String sourceBranch,
  required bool reuseExistingBranch,
}) => RustLib.instance.api.crateApiGitCreateWorktree(
  repoPath: repoPath,
  targetBranch: targetBranch,
  path: path,
  sourceBranch: sourceBranch,
  reuseExistingBranch: reuseExistingBranch,
);

/// Removes the worktree whose checkout lives at `path`, deleting the working
/// tree files. Mirrors `git worktree remove --force <path>`.
Future<void> removeWorktree({
  required String repoPath,
  required String path,
  required bool force,
}) => RustLib.instance.api.crateApiGitRemoveWorktree(
  repoPath: repoPath,
  path: path,
  force: force,
);

/// Force-deletes a local branch. Mirrors `git branch -D <branch>`.
Future<void> deleteBranch({
  required String repoPath,
  required String branch,
  required bool force,
}) => RustLib.instance.api.crateApiGitDeleteBranch(
  repoPath: repoPath,
  branch: branch,
  force: force,
);

/// Lists the main work tree plus every linked worktree, with each entry's
/// branch short name. Mirrors `git worktree list --porcelain` (the main work
/// tree is included so callers can use its presence as a liveness guard).
Future<List<GitWorktreeEntry>> listWorktrees({required String repoPath}) =>
    RustLib.instance.api.crateApiGitListWorktrees(repoPath: repoPath);

/// Lists the repository's configured remotes with their fetch URLs. Used to
/// detect the git hosting provider (GitHub, Azure DevOps, ...) from the remote
/// identity. Remotes without a URL yield `None`.
Future<List<GitRemote>> listRemotes({required String path}) =>
    RustLib.instance.api.crateApiGitListRemotes(path: path);

/// Clones a repository into `destination_path` using the system `git` CLI so
/// the user's credential helper authenticates private remotes. Mirrors
/// `git clone --progress -- <url> <destination_path>`.
Future<void> cloneRepository({
  required String url,
  required String destinationPath,
}) => RustLib.instance.api.crateApiGitCloneRepository(
  url: url,
  destinationPath: destinationPath,
);

enum GitChangeArea { untracked, unstaged, staged }

class GitChangeEntry {
  final String path;
  final String? oldPath;
  final GitChangeArea area;
  final GitChangeStatus status;
  final int? added;
  final int? removed;
  final bool isBinary;
  final bool isLarge;
  final GitSubmoduleStatus? submodule;

  const GitChangeEntry({
    required this.path,
    this.oldPath,
    required this.area,
    required this.status,
    this.added,
    this.removed,
    required this.isBinary,
    required this.isLarge,
    this.submodule,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      oldPath.hashCode ^
      area.hashCode ^
      status.hashCode ^
      added.hashCode ^
      removed.hashCode ^
      isBinary.hashCode ^
      isLarge.hashCode ^
      submodule.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitChangeEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          oldPath == other.oldPath &&
          area == other.area &&
          status == other.status &&
          added == other.added &&
          removed == other.removed &&
          isBinary == other.isBinary &&
          isLarge == other.isLarge &&
          submodule == other.submodule;
}

class GitChangeGroup {
  final GitChangeArea area;
  final List<GitChangeEntry> entries;
  final List<GitChangeTreeRow> treeRows;

  const GitChangeGroup({
    required this.area,
    required this.entries,
    required this.treeRows,
  });

  @override
  int get hashCode => area.hashCode ^ entries.hashCode ^ treeRows.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitChangeGroup &&
          runtimeType == other.runtimeType &&
          area == other.area &&
          entries == other.entries &&
          treeRows == other.treeRows;
}

enum GitChangeStatus { modified, added, deleted, renamed, copied, untracked }

class GitChangeTreeRow {
  final GitChangeTreeRowKind kind;
  final String name;
  final String path;
  final int depth;
  final int fileCount;
  final GitChangeEntry? entry;

  const GitChangeTreeRow({
    required this.kind,
    required this.name,
    required this.path,
    required this.depth,
    required this.fileCount,
    this.entry,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      name.hashCode ^
      path.hashCode ^
      depth.hashCode ^
      fileCount.hashCode ^
      entry.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitChangeTreeRow &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          name == other.name &&
          path == other.path &&
          depth == other.depth &&
          fileCount == other.fileCount &&
          entry == other.entry;
}

enum GitChangeTreeRowKind { directory, file }

class GitCommitChangeEntry {
  final String path;
  final String? oldPath;
  final GitChangeStatus status;
  final int? added;
  final int? removed;

  const GitCommitChangeEntry({
    required this.path,
    this.oldPath,
    required this.status,
    this.added,
    this.removed,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      oldPath.hashCode ^
      status.hashCode ^
      added.hashCode ^
      removed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitCommitChangeEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          oldPath == other.oldPath &&
          status == other.status &&
          added == other.added &&
          removed == other.removed;
}

class GitCommitCompareResult {
  final GitCommitCompareSummary summary;
  final List<GitCommitChangeEntry> entries;

  const GitCommitCompareResult({required this.summary, required this.entries});

  @override
  int get hashCode => summary.hashCode ^ entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitCommitCompareResult &&
          runtimeType == other.runtimeType &&
          summary == other.summary &&
          entries == other.entries;
}

enum GitCommitCompareStatus { ready, invalidCommit, error }

class GitCommitCompareSummary {
  final String commitOid;
  final String? parentOid;
  final String compareRef;
  final String baseRef;
  final int changedFiles;
  final GitCommitCompareStatus status;
  final String? errorMessage;

  const GitCommitCompareSummary({
    required this.commitOid,
    this.parentOid,
    required this.compareRef,
    required this.baseRef,
    required this.changedFiles,
    required this.status,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      commitOid.hashCode ^
      parentOid.hashCode ^
      compareRef.hashCode ^
      baseRef.hashCode ^
      changedFiles.hashCode ^
      status.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitCommitCompareSummary &&
          runtimeType == other.runtimeType &&
          commitOid == other.commitOid &&
          parentOid == other.parentOid &&
          compareRef == other.compareRef &&
          baseRef == other.baseRef &&
          changedFiles == other.changedFiles &&
          status == other.status &&
          errorMessage == other.errorMessage;
}

class GitDiffFile {
  final String path;
  final String? oldPath;
  final GitChangeArea area;
  final GitChangeStatus status;
  final List<GitDiffLine> lines;
  final int? added;
  final int? removed;
  final bool isBinary;
  final bool isLarge;
  final bool isGitlink;
  final bool truncated;
  final bool linePreviewTruncated;

  const GitDiffFile({
    required this.path,
    this.oldPath,
    required this.area,
    required this.status,
    required this.lines,
    this.added,
    this.removed,
    required this.isBinary,
    required this.isLarge,
    required this.isGitlink,
    required this.truncated,
    required this.linePreviewTruncated,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      oldPath.hashCode ^
      area.hashCode ^
      status.hashCode ^
      lines.hashCode ^
      added.hashCode ^
      removed.hashCode ^
      isBinary.hashCode ^
      isLarge.hashCode ^
      isGitlink.hashCode ^
      truncated.hashCode ^
      linePreviewTruncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitDiffFile &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          oldPath == other.oldPath &&
          area == other.area &&
          status == other.status &&
          lines == other.lines &&
          added == other.added &&
          removed == other.removed &&
          isBinary == other.isBinary &&
          isLarge == other.isLarge &&
          isGitlink == other.isGitlink &&
          truncated == other.truncated &&
          linePreviewTruncated == other.linePreviewTruncated;
}

class GitDiffLine {
  final String text;
  final GitDiffLineKind kind;

  const GitDiffLine({required this.text, required this.kind});

  @override
  int get hashCode => text.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitDiffLine &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          kind == other.kind;
}

enum GitDiffLineKind { addition, deletion, hunk, header, context }

/// One bounded page of a combined working-tree diff.
class GitDiffPage {
  final List<GitDiffFile> files;
  final bool truncated;

  const GitDiffPage({required this.files, required this.truncated});

  @override
  int get hashCode => files.hashCode ^ truncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitDiffPage &&
          runtimeType == other.runtimeType &&
          files == other.files &&
          truncated == other.truncated;
}

class GitDiffResult {
  final List<GitDiffFile> files;
  final bool truncated;

  const GitDiffResult({required this.files, required this.truncated});

  @override
  int get hashCode => files.hashCode ^ truncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitDiffResult &&
          runtimeType == other.runtimeType &&
          files == other.files &&
          truncated == other.truncated;
}

class GitError implements FrbException {
  final GitErrorKind kind;
  final String context;

  const GitError({required this.kind, required this.context});

  @override
  int get hashCode => kind.hashCode ^ context.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          context == other.context;
}

enum GitErrorKind {
  notARepository,
  accessDenied,
  branchNotFound,
  branchAlreadyExists,
  invalidBranchName,
  worktreeAlreadyExists,
  worktreeNotFound,
  cloneFailed,
  gitCli,
  detachedHead,
  noUpstream,
  remoteNotFound,
  nothingToCommit,
  conflict,
  workspaceScope,
  missingIdentity,
  internal,
}

class GitHistoryItem {
  final String id;
  final List<String> parentIds;
  final String subject;
  final String message;
  final String? displayId;
  final String? author;
  final String? authorEmail;
  final PlatformInt64? timestamp;
  final List<GitHistoryItemRef> references;

  const GitHistoryItem({
    required this.id,
    required this.parentIds,
    required this.subject,
    required this.message,
    this.displayId,
    this.author,
    this.authorEmail,
    this.timestamp,
    required this.references,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      parentIds.hashCode ^
      subject.hashCode ^
      message.hashCode ^
      displayId.hashCode ^
      author.hashCode ^
      authorEmail.hashCode ^
      timestamp.hashCode ^
      references.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitHistoryItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          parentIds == other.parentIds &&
          subject == other.subject &&
          message == other.message &&
          displayId == other.displayId &&
          author == other.author &&
          authorEmail == other.authorEmail &&
          timestamp == other.timestamp &&
          references == other.references;
}

class GitHistoryItemRef {
  final String id;
  final String name;
  final String? revision;
  final GitHistoryRefCategory? category;

  const GitHistoryItemRef({
    required this.id,
    required this.name,
    this.revision,
    this.category,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ revision.hashCode ^ category.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitHistoryItemRef &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          revision == other.revision &&
          category == other.category;
}

enum GitHistoryRefCategory { branches, remoteBranches, tags, commits }

class GitHistoryResult {
  final List<GitHistoryItem> items;
  final GitHistoryItemRef? currentRef;
  final GitHistoryItemRef? remoteRef;
  final GitHistoryItemRef? baseRef;
  final String? mergeBase;
  final bool hasIncomingChanges;
  final bool hasOutgoingChanges;
  final bool hasMore;
  final int limit;

  const GitHistoryResult({
    required this.items,
    this.currentRef,
    this.remoteRef,
    this.baseRef,
    this.mergeBase,
    required this.hasIncomingChanges,
    required this.hasOutgoingChanges,
    required this.hasMore,
    required this.limit,
  });

  @override
  int get hashCode =>
      items.hashCode ^
      currentRef.hashCode ^
      remoteRef.hashCode ^
      baseRef.hashCode ^
      mergeBase.hashCode ^
      hasIncomingChanges.hashCode ^
      hasOutgoingChanges.hashCode ^
      hasMore.hashCode ^
      limit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitHistoryResult &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          currentRef == other.currentRef &&
          remoteRef == other.remoteRef &&
          baseRef == other.baseRef &&
          mergeBase == other.mergeBase &&
          hasIncomingChanges == other.hasIncomingChanges &&
          hasOutgoingChanges == other.hasOutgoingChanges &&
          hasMore == other.hasMore &&
          limit == other.limit;
}

/// One commit on the range from merge-base(base, HEAD) to HEAD.
class GitRangeCommit {
  final String oid;
  final String subject;
  final String message;

  const GitRangeCommit({
    required this.oid,
    required this.subject,
    required this.message,
  });

  @override
  int get hashCode => oid.hashCode ^ subject.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitRangeCommit &&
          runtimeType == other.runtimeType &&
          oid == other.oid &&
          subject == other.subject &&
          message == other.message;
}

/// Tree-to-tree range summary used for AI pull-request prompts.
class GitRangeContext {
  final String baseRef;
  final String headOid;
  final String? headBranch;
  final String? mergeBase;
  final List<GitRangeCommit> commits;
  final List<GitRangeFile> files;
  final String patch;

  const GitRangeContext({
    required this.baseRef,
    required this.headOid,
    this.headBranch,
    this.mergeBase,
    required this.commits,
    required this.files,
    required this.patch,
  });

  @override
  int get hashCode =>
      baseRef.hashCode ^
      headOid.hashCode ^
      headBranch.hashCode ^
      mergeBase.hashCode ^
      commits.hashCode ^
      files.hashCode ^
      patch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitRangeContext &&
          runtimeType == other.runtimeType &&
          baseRef == other.baseRef &&
          headOid == other.headOid &&
          headBranch == other.headBranch &&
          mergeBase == other.mergeBase &&
          commits == other.commits &&
          files == other.files &&
          patch == other.patch;
}

/// One file changed between merge-base(base, HEAD) and HEAD.
class GitRangeFile {
  final String path;
  final GitChangeStatus status;
  final int? added;
  final int? removed;

  const GitRangeFile({
    required this.path,
    required this.status,
    this.added,
    this.removed,
  });

  @override
  int get hashCode =>
      path.hashCode ^ status.hashCode ^ added.hashCode ^ removed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitRangeFile &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          status == other.status &&
          added == other.added &&
          removed == other.removed;
}

class GitRemote {
  final String name;
  final String? url;

  const GitRemote({required this.name, this.url});

  @override
  int get hashCode => name.hashCode ^ url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitRemote &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          url == other.url;
}

class GitRepositoryState {
  final String branch;
  final String? upstream;
  final int ahead;
  final int behind;
  final bool hasConflicts;
  final String? headMessage;

  const GitRepositoryState({
    required this.branch,
    this.upstream,
    required this.ahead,
    required this.behind,
    required this.hasConflicts,
    this.headMessage,
  });

  @override
  int get hashCode =>
      branch.hashCode ^
      upstream.hashCode ^
      ahead.hashCode ^
      behind.hashCode ^
      hasConflicts.hashCode ^
      headMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitRepositoryState &&
          runtimeType == other.runtimeType &&
          branch == other.branch &&
          upstream == other.upstream &&
          ahead == other.ahead &&
          behind == other.behind &&
          hasConflicts == other.hasConflicts &&
          headMessage == other.headMessage;
}

class GitStashEntry {
  final int index;
  final String reference;
  final String message;
  final String oid;

  const GitStashEntry({
    required this.index,
    required this.reference,
    required this.message,
    required this.oid,
  });

  @override
  int get hashCode =>
      index.hashCode ^ reference.hashCode ^ message.hashCode ^ oid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitStashEntry &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          reference == other.reference &&
          message == other.message &&
          oid == other.oid;
}

class GitStatusResult {
  final List<GitChangeEntry> entries;
  final List<GitChangeGroup> groups;

  const GitStatusResult({required this.entries, required this.groups});

  @override
  int get hashCode => entries.hashCode ^ groups.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitStatusResult &&
          runtimeType == other.runtimeType &&
          entries == other.entries &&
          groups == other.groups;
}

class GitSubmoduleStatus {
  final bool commitChanged;
  final bool trackedChanges;
  final bool untrackedChanges;
  final bool inspectable;

  const GitSubmoduleStatus({
    required this.commitChanged,
    required this.trackedChanges,
    required this.untrackedChanges,
    required this.inspectable,
  });

  @override
  int get hashCode =>
      commitChanged.hashCode ^
      trackedChanges.hashCode ^
      untrackedChanges.hashCode ^
      inspectable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitSubmoduleStatus &&
          runtimeType == other.runtimeType &&
          commitChanged == other.commitChanged &&
          trackedChanges == other.trackedChanges &&
          untrackedChanges == other.untrackedChanges &&
          inspectable == other.inspectable;
}

class GitWorktreeEntry {
  final String path;
  final String branch;

  const GitWorktreeEntry({required this.path, required this.branch});

  @override
  int get hashCode => path.hashCode ^ branch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitWorktreeEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          branch == other.branch;
}
