// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'git.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `blob_bytes`, `index_blob_bytes`, `tree_blob_bytes`, `workdir_file_bytes`

/// Raw bytes of one side of a diffed file, used for binary previews such as
/// images. Returns `None` when that side does not exist (added or deleted
/// files), the entry is not a blob, or the content exceeds
/// [`MAX_DIFF_BLOB_BYTES`].
Future<Uint8List?> gitDiffBlobBytes({
  required String path,
  required String filePath,
  String? oldPath,
  GitChangeArea? area,
  String? commitOid,
  String? parentOid,
  required bool oldSide,
}) => RustLib.instance.api.crateApiGitDiffBlobGitDiffBlobBytes(
  path: path,
  filePath: filePath,
  oldPath: oldPath,
  area: area,
  commitOid: commitOid,
  parentOid: parentOid,
  oldSide: oldSide,
);

Future<Uint8List?> gitFileRevisionBlobBytes({
  required String path,
  required String filePath,
  required String revisionOid,
  required bool oldSide,
}) => RustLib.instance.api.crateApiGitDiffBlobGitFileRevisionBlobBytes(
  path: path,
  filePath: filePath,
  revisionOid: revisionOid,
  oldSide: oldSide,
);
