// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `content_token`, `from_io`, `modified_millis`, `new`, `normalize_relative_path`, `resolve_existing`, `workspace_root`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

Future<MermanWorkspaceRender> renderMermanWorkspaceFile({
  required String workspacePath,
  required String relativePath,
}) => RustLib.instance.api.crateApiMermanViewerRenderMermanWorkspaceFile(
  workspacePath: workspacePath,
  relativePath: relativePath,
);

Future<String> renderMermanSource({
  required String source,
  required String diagramId,
}) => RustLib.instance.api.crateApiMermanViewerRenderMermanSource(
  source: source,
  diagramId: diagramId,
);

class MermanViewerError implements FrbException {
  final MermanViewerErrorKind kind;
  final String context;

  const MermanViewerError({required this.kind, required this.context});

  @override
  int get hashCode => kind.hashCode ^ context.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MermanViewerError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          context == other.context;
}

enum MermanViewerErrorKind {
  invalidPath,
  outsideWorkspace,
  notFound,
  unsupported,
  render,
  io,
}

class MermanWorkspaceRender {
  final String svg;
  final String contentToken;
  final PlatformInt64 modifiedMillis;
  final BigInt size;

  const MermanWorkspaceRender({
    required this.svg,
    required this.contentToken,
    required this.modifiedMillis,
    required this.size,
  });

  @override
  int get hashCode =>
      svg.hashCode ^
      contentToken.hashCode ^
      modifiedMillis.hashCode ^
      size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MermanWorkspaceRender &&
          runtimeType == other.runtimeType &&
          svg == other.svg &&
          contentToken == other.contentToken &&
          modifiedMillis == other.modifiedMillis &&
          size == other.size;
}
