use super::launch_specs::{
    AGY_LAUNCH_SPEC, AMP_LAUNCH_SPEC, CLAUDE_LAUNCH_SPEC, CODEX_LAUNCH_SPEC, COPILOT_LAUNCH_SPEC,
    CURSOR_LAUNCH_SPEC, DEVIN_LAUNCH_SPEC, FX_LAUNCH_SPEC, GROK_LAUNCH_SPEC, OPENCODE2_LAUNCH_SPEC,
    OPENCODE_LAUNCH_SPEC, PI_LAUNCH_SPEC,
};
use super::{
    AgentDescriptor, AgentHookStrategy, AgentModelOverride, AgentRiskRule, AgentStartupPrompt,
    AgentStatusNormalizationRule, AgentStatusNormalizationSpec, AgentStatusState,
    AgentStatusStrategy,
};

const CTRL_C: &[u8] = b"\x03";

const CODEX_RISK_RULES: &[AgentRiskRule] = &[
    AgentRiskRule {
        key: "bypassApprovalsAndSandbox",
        expected_bool: Some(true),
        expected_str: None,
        marker: "bypassApprovalsAndSandbox",
        score: 100,
    },
    AgentRiskRule {
        key: "sandbox",
        expected_bool: None,
        expected_str: Some("danger-full-access"),
        marker: "dangerFullAccess",
        score: 40,
    },
    AgentRiskRule {
        key: "approvalPolicy",
        expected_bool: None,
        expected_str: Some("never"),
        marker: "neverAsk",
        score: 30,
    },
];

const CLAUDE_RISK_RULES: &[AgentRiskRule] = &[
    AgentRiskRule {
        key: "permissionMode",
        expected_bool: None,
        expected_str: Some("bypassPermissions"),
        marker: "bypassPermissions",
        score: 100,
    },
    AgentRiskRule {
        key: "permissionMode",
        expected_bool: None,
        expected_str: Some("dontAsk"),
        marker: "dontAsk",
        score: 40,
    },
    AgentRiskRule {
        key: "allowSkipPermissions",
        expected_bool: Some(true),
        expected_str: None,
        marker: "allowSkipPermissions",
        score: 30,
    },
];

const COPILOT_RISK_RULES: &[AgentRiskRule] = &[
    AgentRiskRule {
        key: "allowAll",
        expected_bool: Some(true),
        expected_str: None,
        marker: "allowAll",
        score: 70,
    },
    AgentRiskRule {
        key: "mode",
        expected_bool: None,
        expected_str: Some("autopilot"),
        marker: "autopilot",
        score: 40,
    },
    AgentRiskRule {
        key: "noAskUser",
        expected_bool: Some(true),
        expected_str: None,
        marker: "noAskUser",
        score: 30,
    },
];

const CURSOR_RISK_RULES: &[AgentRiskRule] = &[
    AgentRiskRule {
        key: "permissionMode",
        expected_bool: None,
        expected_str: Some("force"),
        marker: "force",
        score: 70,
    },
    AgentRiskRule {
        key: "sandbox",
        expected_bool: None,
        expected_str: Some("disabled"),
        marker: "sandboxDisabled",
        score: 50,
    },
    AgentRiskRule {
        key: "trustWorkspace",
        expected_bool: Some(true),
        expected_str: None,
        marker: "trustWorkspace",
        score: 20,
    },
];

const AGY_RISK_RULES: &[AgentRiskRule] = &[AgentRiskRule {
    key: "skipPermissions",
    expected_bool: Some(true),
    expected_str: None,
    marker: "skipPermissions",
    score: 100,
}];

const OPENCODE_RISK_RULES: &[AgentRiskRule] = &[AgentRiskRule {
    key: "autoApprove",
    expected_bool: Some(true),
    expected_str: None,
    marker: "autoApprove",
    score: 60,
}];

const PI_RISK_RULES: &[AgentRiskRule] = &[AgentRiskRule {
    key: "projectTrust",
    expected_bool: None,
    expected_str: Some("approve"),
    marker: "projectTrust",
    score: 30,
}];

const GROK_RISK_RULES: &[AgentRiskRule] = &[
    AgentRiskRule {
        key: "permissionMode",
        expected_bool: None,
        expected_str: Some("bypassPermissions"),
        marker: "bypassPermissions",
        score: 100,
    },
    AgentRiskRule {
        key: "permissionMode",
        expected_bool: None,
        expected_str: Some("dontAsk"),
        marker: "dontAsk",
        score: 40,
    },
];

const DEVIN_RISK_RULES: &[AgentRiskRule] = &[
    AgentRiskRule {
        key: "permissionMode",
        expected_bool: None,
        expected_str: Some("dangerous"),
        marker: "dangerous",
        score: 100,
    },
    AgentRiskRule {
        key: "permissionMode",
        expected_bool: None,
        expected_str: Some("smart"),
        marker: "smart",
        score: 30,
    },
];

const NO_RISK_RULES: &[AgentRiskRule] = &[];

const CODEX_STATUS: &[AgentStatusNormalizationRule] = &[
    AgentStatusNormalizationRule::new("SessionStart", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("UserPromptSubmit", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("PostToolUse", AgentStatusState::Working),
    AgentStatusNormalizationRule::with_human_input(
        "PreToolUse",
        AgentStatusState::Working,
        AgentStatusState::Waiting,
    ),
    AgentStatusNormalizationRule::new("PermissionRequest", AgentStatusState::Waiting),
    AgentStatusNormalizationRule::new("Stop", AgentStatusState::Done),
    AgentStatusNormalizationRule::new("Interrupt", AgentStatusState::Done),
    AgentStatusNormalizationRule::new("SessionEnd", AgentStatusState::Done),
];
const CLAUDE_STATUS: &[AgentStatusNormalizationRule] = &[
    AgentStatusNormalizationRule::new("UserPromptSubmit", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("PostToolUse", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("PostToolUseFailure", AgentStatusState::Working),
    AgentStatusNormalizationRule::with_human_input(
        "PreToolUse",
        AgentStatusState::Working,
        AgentStatusState::Waiting,
    ),
    AgentStatusNormalizationRule::new("PermissionRequest", AgentStatusState::Waiting),
    AgentStatusNormalizationRule::new("AskUserQuestion", AgentStatusState::Waiting),
    AgentStatusNormalizationRule::new("Stop", AgentStatusState::Done),
    AgentStatusNormalizationRule::new("StopFailure", AgentStatusState::Done),
];
const COPILOT_STATUS: &[AgentStatusNormalizationRule] = &[
    AgentStatusNormalizationRule::new("SessionStart", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("UserPromptSubmit", AgentStatusState::Working),
    AgentStatusNormalizationRule::with_human_input(
        "PreToolUse",
        AgentStatusState::Working,
        AgentStatusState::Blocked,
    ),
    AgentStatusNormalizationRule::new("PostToolUse", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("PostToolUseFailure", AgentStatusState::Working),
    AgentStatusNormalizationRule::with_human_input(
        "PermissionRequest",
        AgentStatusState::Working,
        AgentStatusState::Blocked,
    ),
    AgentStatusNormalizationRule::new("ErrorOccurred", AgentStatusState::Done),
    AgentStatusNormalizationRule::new("Stop", AgentStatusState::Done),
    AgentStatusNormalizationRule::new("SessionEnd", AgentStatusState::Done),
];
const CURSOR_STATUS: &[AgentStatusNormalizationRule] = &[
    AgentStatusNormalizationRule::new("beforeSubmitPrompt", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("sessionStart", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("preToolUse", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("postToolUse", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("postToolUseFailure", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("beforeShellExecution", AgentStatusState::Waiting),
    AgentStatusNormalizationRule::new("beforeMCPExecution", AgentStatusState::Waiting),
    AgentStatusNormalizationRule::new("afterShellExecution", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("afterMCPExecution", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("afterAgentResponse", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("stop", AgentStatusState::Done),
    AgentStatusNormalizationRule::new("sessionEnd", AgentStatusState::Done),
];
const AGY_STATUS: &[AgentStatusNormalizationRule] = &[
    AgentStatusNormalizationRule::new("PreInvocation", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("PostInvocation", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("PostToolUse", AgentStatusState::Working),
    AgentStatusNormalizationRule::with_human_input(
        "PreToolUse",
        AgentStatusState::Working,
        AgentStatusState::Waiting,
    ),
    AgentStatusNormalizationRule::new("Stop", AgentStatusState::Done),
];
const OPENCODE_STATUS: &[AgentStatusNormalizationRule] = &[
    AgentStatusNormalizationRule::new("SessionBusy", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("MessagePart", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("PermissionRequest", AgentStatusState::Waiting),
    AgentStatusNormalizationRule::new("AskUserQuestion", AgentStatusState::Waiting),
    AgentStatusNormalizationRule::new("SessionIdle", AgentStatusState::Done),
];
const PI_STATUS: &[AgentStatusNormalizationRule] = &[
    AgentStatusNormalizationRule::new("before_agent_start", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("agent_start", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("tool_call", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("tool_execution_start", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("tool_execution_end", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("message_end", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("agent_end", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("agent_settled", AgentStatusState::Done),
    AgentStatusNormalizationRule::new("session_shutdown", AgentStatusState::Done),
];
const AMP_STATUS: &[AgentStatusNormalizationRule] = &[
    AgentStatusNormalizationRule::new("session.start", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("agent.start", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("tool.call", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("tool.result", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("agent.end", AgentStatusState::Done),
];
const GROK_STATUS: &[AgentStatusNormalizationRule] = &[
    AgentStatusNormalizationRule::new("UserPromptSubmit", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("PreToolUse", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("PostToolUse", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("PostToolUseFailure", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("Stop", AgentStatusState::Done),
    AgentStatusNormalizationRule::new("StopFailure", AgentStatusState::Done),
    AgentStatusNormalizationRule::new("SessionEnd", AgentStatusState::Done),
];
const DEVIN_STATUS: &[AgentStatusNormalizationRule] = &[
    AgentStatusNormalizationRule::new("SessionStart", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("UserPromptSubmit", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("PreToolUse", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("PostToolUse", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("PermissionRequest", AgentStatusState::Blocked),
    AgentStatusNormalizationRule::new("Stop", AgentStatusState::Done),
    AgentStatusNormalizationRule::new("SessionEnd", AgentStatusState::Done),
];
const FX_STATUS: &[AgentStatusNormalizationRule] = &[
    AgentStatusNormalizationRule::new("Working", AgentStatusState::Working),
    AgentStatusNormalizationRule::new("Blocked", AgentStatusState::Blocked),
    AgentStatusNormalizationRule::new("Idle", AgentStatusState::Done),
];

/// Spawnable agent adapters, one entry per `AgentType`. Order is significant:
/// UI lists and tests rely on it.
pub const AGENT_DESCRIPTORS: &[AgentDescriptor] = &[
    AgentDescriptor {
        id: "codex",
        aliases: &[],
        display_name: "Codex",
        default_command: "codex",
        force_submit: true,
        interrupt_bytes: CTRL_C,
        startup_prompt: AgentStartupPrompt::PositionalAfterTerminator,
        hook_strategy: AgentHookStrategy::RuntimeHome,
        status_strategy: AgentStatusStrategy::HookEventsWithTranscriptWatch,
        status_normalization: AgentStatusNormalizationSpec::new(CODEX_STATUS),
        quota_provider_id: Some("codex"),
        transcript_usage: true,
        model_override: AgentModelOverride::Supported,
        supports_persona: false,
        supports_ccs_profile: false,
        risk_warning: "This profile reduces Codex approval or sandbox protections.",
        risk_warning_severe: Some(
            "This profile will bypass Codex approvals and sandbox protections.",
        ),
        risk_rules: CODEX_RISK_RULES,
        launch_spec: CODEX_LAUNCH_SPEC,
    },
    AgentDescriptor {
        id: "claude",
        aliases: &[],
        display_name: "Claude Code",
        default_command: "claude",
        force_submit: true,
        interrupt_bytes: CTRL_C,
        startup_prompt: AgentStartupPrompt::PositionalAfterTerminator,
        hook_strategy: AgentHookStrategy::RuntimeHome,
        status_strategy: AgentStatusStrategy::HookEvents,
        status_normalization: AgentStatusNormalizationSpec::new(CLAUDE_STATUS),
        quota_provider_id: Some("claude"),
        transcript_usage: true,
        model_override: AgentModelOverride::Supported,
        supports_persona: true,
        supports_ccs_profile: true,
        risk_warning: "This profile lets Claude continue with reduced permission prompts.",
        risk_warning_severe: None,
        risk_rules: CLAUDE_RISK_RULES,
        launch_spec: CLAUDE_LAUNCH_SPEC,
    },
    AgentDescriptor {
        id: "copilot",
        aliases: &[],
        display_name: "GitHub Copilot",
        default_command: "copilot",
        force_submit: true,
        interrupt_bytes: CTRL_C,
        startup_prompt: AgentStartupPrompt::LongOption("--interactive"),
        hook_strategy: AgentHookStrategy::ConfigJson,
        status_strategy: AgentStatusStrategy::HookEvents,
        status_normalization: AgentStatusNormalizationSpec::new(COPILOT_STATUS),
        quota_provider_id: None,
        transcript_usage: false,
        model_override: AgentModelOverride::Supported,
        supports_persona: true,
        supports_ccs_profile: false,
        risk_warning: "This profile lets Copilot take broader actions with less supervision.",
        risk_warning_severe: None,
        risk_rules: COPILOT_RISK_RULES,
        launch_spec: COPILOT_LAUNCH_SPEC,
    },
    AgentDescriptor {
        id: "cursor",
        aliases: &[],
        display_name: "Cursor",
        default_command: "cursor-agent",
        force_submit: true,
        interrupt_bytes: CTRL_C,
        startup_prompt: AgentStartupPrompt::PositionalAfterTerminator,
        hook_strategy: AgentHookStrategy::SessionOverlay,
        status_strategy: AgentStatusStrategy::HookEvents,
        status_normalization: AgentStatusNormalizationSpec::new(CURSOR_STATUS),
        quota_provider_id: Some("cursor"),
        transcript_usage: false,
        model_override: AgentModelOverride::Supported,
        supports_persona: false,
        supports_ccs_profile: false,
        risk_warning: "This profile reduces Cursor review, sandbox, or trust protections.",
        risk_warning_severe: None,
        risk_rules: CURSOR_RISK_RULES,
        launch_spec: CURSOR_LAUNCH_SPEC,
    },
    AgentDescriptor {
        id: "agy",
        aliases: &["antigravity"],
        display_name: "Antigravity",
        default_command: "agy",
        force_submit: true,
        interrupt_bytes: CTRL_C,
        startup_prompt: AgentStartupPrompt::LongOption("--prompt-interactive"),
        hook_strategy: AgentHookStrategy::ConfigJson,
        status_strategy: AgentStatusStrategy::HookEvents,
        status_normalization: AgentStatusNormalizationSpec::new(AGY_STATUS),
        quota_provider_id: Some("agy"),
        transcript_usage: false,
        model_override: AgentModelOverride::Supported,
        supports_persona: true,
        supports_ccs_profile: false,
        risk_warning: "This profile lets Antigravity skip permission checks.",
        risk_warning_severe: None,
        risk_rules: AGY_RISK_RULES,
        launch_spec: AGY_LAUNCH_SPEC,
    },
    AgentDescriptor {
        id: "opencode",
        aliases: &[],
        display_name: "OpenCode",
        default_command: "opencode",
        force_submit: true,
        interrupt_bytes: CTRL_C,
        startup_prompt: AgentStartupPrompt::LongOption("--prompt"),
        hook_strategy: AgentHookStrategy::PluginScript,
        status_strategy: AgentStatusStrategy::HookEvents,
        status_normalization: AgentStatusNormalizationSpec::new(OPENCODE_STATUS),
        quota_provider_id: Some("opencode"),
        transcript_usage: false,
        model_override: AgentModelOverride::Supported,
        supports_persona: true,
        supports_ccs_profile: false,
        risk_warning: "This profile lets OpenCode approve actions automatically.",
        risk_warning_severe: None,
        risk_rules: OPENCODE_RISK_RULES,
        launch_spec: OPENCODE_LAUNCH_SPEC,
    },
    AgentDescriptor {
        // OpenCode 2 installs as `opencode2` beside v1's `opencode`.
        id: "opencode2",
        aliases: &[],
        display_name: "OpenCode 2",
        default_command: "opencode2",
        force_submit: true,
        interrupt_bytes: CTRL_C,
        startup_prompt: AgentStartupPrompt::LongOption("--prompt"),
        hook_strategy: AgentHookStrategy::PluginScript,
        status_strategy: AgentStatusStrategy::HookEvents,
        status_normalization: AgentStatusNormalizationSpec::new(OPENCODE_STATUS),
        quota_provider_id: None,
        transcript_usage: false,
        model_override: AgentModelOverride::ProfileOnly,
        supports_persona: true,
        supports_ccs_profile: false,
        risk_warning: "This profile lets OpenCode approve actions automatically.",
        risk_warning_severe: None,
        risk_rules: OPENCODE_RISK_RULES,
        launch_spec: OPENCODE2_LAUNCH_SPEC,
    },
    AgentDescriptor {
        id: "pi",
        aliases: &[],
        display_name: "Pi",
        default_command: "pi",
        force_submit: true,
        interrupt_bytes: CTRL_C,
        startup_prompt: AgentStartupPrompt::Positional,
        hook_strategy: AgentHookStrategy::PluginScript,
        status_strategy: AgentStatusStrategy::HookEvents,
        status_normalization: AgentStatusNormalizationSpec::new(PI_STATUS),
        quota_provider_id: None,
        transcript_usage: false,
        model_override: AgentModelOverride::Supported,
        supports_persona: false,
        supports_ccs_profile: false,
        risk_warning: "This profile pre-approves project trust for Pi.",
        risk_warning_severe: None,
        risk_rules: PI_RISK_RULES,
        launch_spec: PI_LAUNCH_SPEC,
    },
    AgentDescriptor {
        id: "amp",
        aliases: &[],
        display_name: "Amp",
        default_command: "amp",
        force_submit: true,
        interrupt_bytes: CTRL_C,
        startup_prompt: AgentStartupPrompt::StdinScript,
        hook_strategy: AgentHookStrategy::PluginScript,
        status_strategy: AgentStatusStrategy::HookEvents,
        status_normalization: AgentStatusNormalizationSpec::new(AMP_STATUS),
        quota_provider_id: None,
        transcript_usage: false,
        model_override: AgentModelOverride::Unsupported,
        supports_persona: false,
        supports_ccs_profile: false,
        risk_warning: "",
        risk_warning_severe: None,
        risk_rules: NO_RISK_RULES,
        launch_spec: AMP_LAUNCH_SPEC,
    },
    AgentDescriptor {
        id: "grok",
        aliases: &[],
        display_name: "Grok Build",
        default_command: "grok",
        force_submit: true,
        interrupt_bytes: CTRL_C,
        startup_prompt: AgentStartupPrompt::PositionalAfterTerminator,
        hook_strategy: AgentHookStrategy::ConfigJson,
        status_strategy: AgentStatusStrategy::HookEvents,
        status_normalization: AgentStatusNormalizationSpec::new(GROK_STATUS),
        quota_provider_id: Some("grok"),
        transcript_usage: true,
        model_override: AgentModelOverride::Supported,
        supports_persona: true,
        supports_ccs_profile: false,
        risk_warning: "This profile lets Grok Build continue with reduced permission prompts.",
        risk_warning_severe: None,
        risk_rules: GROK_RISK_RULES,
        launch_spec: GROK_LAUNCH_SPEC,
    },
    AgentDescriptor {
        id: "devin",
        aliases: &[],
        display_name: "Devin",
        default_command: "devin",
        force_submit: true,
        interrupt_bytes: CTRL_C,
        startup_prompt: AgentStartupPrompt::PositionalAfterTerminator,
        hook_strategy: AgentHookStrategy::ConfigJson,
        status_strategy: AgentStatusStrategy::HookEvents,
        status_normalization: AgentStatusNormalizationSpec::new(DEVIN_STATUS),
        quota_provider_id: Some("devin"),
        transcript_usage: false,
        model_override: AgentModelOverride::Supported,
        supports_persona: false,
        supports_ccs_profile: false,
        risk_warning: "This profile lets Devin take broader actions with less supervision.",
        risk_warning_severe: None,
        risk_rules: DEVIN_RISK_RULES,
        launch_spec: DEVIN_LAUNCH_SPEC,
    },
    AgentDescriptor {
        id: "fx",
        aliases: &[],
        display_name: "fx",
        default_command: "fx",
        force_submit: true,
        interrupt_bytes: CTRL_C,
        startup_prompt: AgentStartupPrompt::TerminalAfterReady,
        hook_strategy: AgentHookStrategy::HerdrSocket,
        status_strategy: AgentStatusStrategy::HerdrSocket,
        status_normalization: AgentStatusNormalizationSpec::new(FX_STATUS),
        quota_provider_id: None,
        transcript_usage: false,
        model_override: AgentModelOverride::Unsupported,
        supports_persona: false,
        supports_ccs_profile: false,
        risk_warning: "",
        risk_warning_severe: None,
        risk_rules: NO_RISK_RULES,
        launch_spec: FX_LAUNCH_SPEC,
    },
];
